package com.example.ui.theme

object LocalizationLessons {

    val lessonMaps: Map<String, Map<String, String>> = mapOf(
        "en" to mapOf(
            "html_1_title" to "Intro to HTML (Web Layout)",
            "html_1_desc" to "Mam's Spaza Shop Storefront",
            "css_2_title" to "Adding Style with CSS",
            "css_2_desc" to "Beautifying Your Online Catalog",
            "js_3_title" to "Interactive JS Calculations",
            "js_3_desc" to "Calculating Bread & Veggie Orders",
            "python_4_title" to "Python Crop Tracker",
            "python_4_desc" to "Harvesting & Pricing Predictions",
            "html_5_title" to "StoryBrand Landing Page",
            "html_5_desc" to "Create High-Converting Headers",
            "css_6_title" to "Visual Branding & Team Roles",
            "css_6_desc" to "Color-Coding SOPs & Roles",
            "js_7_title" to "Spaza Profit & Cash Flow",
            "js_7_desc" to "Recession-Proof Income Trackers",
            "html_8_title" to "Customer Feedback Form",
            "html_8_desc" to "Input Elements for Customer Leads",
            "python_9_title" to "90-Day Predictive Planner",
            "python_9_desc" to "Systems & Loop-Based Growth Trackers",
            "js_10_title" to "SOP Automation Dashboard",
            "js_10_desc" to "Scaling Spaza Systems Digitally",

            "html_1_s1_title" to "Welcome to HTML!",
            "html_1_s1_desc" to "HTML stands for HyperText Markup Language. It's the bone structure of every website! Today, we will code a responsive digital storefront for Mam's Spaza shop in Bloemfontein.",
            "html_1_s1_hint" to "Click Next to continue!",
            "html_1_s2_title" to "Writing Our First Header (<h1>)",
            "html_1_s2_desc" to "The <h1> tag defines the main heading. Write <h1>Mam's Spaza Shop</h1> to give our website a grand, colorful banner at the top!",
            "html_1_s2_hint" to "Type <h1>Mam's Spaza Shop</h1> in the simulator.",
            "html_1_s3_title" to "Listing Product Offerings (<p> & <ul>)",
            "html_1_s3_desc" to "To show paragraph text, we use <p>. To display a list, we use <ul> alongside <li> tags. Let's list what we have: Bread, Milk, and Rooibos tea!",
            "html_1_s3_hint" to "Add <p> and <ul> tags.",

            "css_2_s1_title" to "Styling Core Concepts",
            "css_2_s1_desc" to "CSS controls how elements look – colors, margins, fonts, and borders. Let's bring beautiful African warmth to Mam's shop with a Purple and Gold startup theme!",
            "css_2_s1_hint" to "Learn CSS basic styling rule",
            "css_2_s2_title" to "Modifying Colors (color & background)",
            "css_2_s2_desc" to "To set text color to gold, use color: gold;. To set a rich dark background, write background-color: #121212; inside the CSS selector.",
            "css_2_s2_hint" to "Use background-color and color selectors.",

            "js_3_s1_title" to "What is JavaScript?",
            "js_3_s1_desc" to "JavaScript makes websites interactive! It allows us to calculate purchases, update total price, and save orders without refreshing.",
            "js_3_s1_hint" to "Understand JS variables and logic",
            "js_3_s2_title" to "Writing Your First Calculator Function",
            "js_3_s2_desc" to "Let's write a function to calculate total order prices! We define variables with const and calculate the total.",
            "js_3_s2_hint" to "Develop calculation formula in Rand",

            "python_4_s1_title" to "Python for Smart Farming",
            "python_4_s1_desc" to "Python is fantastic for calculating crop harvest and market prices! In rural South Africa, farmers use data to forecast crop yield.",
            "python_4_s1_hint" to "Basic python syntax and prints",
            "python_4_s2_title" to "Conditional Pricing Estimator (if/else)",
            "python_4_s2_desc" to "Let's write an algorithm that checks temperature: If soil temperature is > 30 degrees Celsius, crop watering must double.",
            "python_4_s2_hint" to "Write conditional statements in Python.",

            "html_5_s1_title" to "Hero Section Title (<h1>)",
            "html_5_s1_desc" to "Under the StoryBrand framework, your customer is the Hero! Write a clear header <h1>Grow Your Business with KodeMamas</h1>.",
            "html_5_s1_hint" to "Type <h1>Grow Your Business with KodeMamas</h1> in the simulator.",
            "html_5_s2_title" to "Call to Action Button",
            "html_5_s2_desc" to "Make it easy for customers to join! Use <button> to create a prominent action button.",
            "html_5_s2_hint" to "Type <button>Join Training Now</button> in the simulator.",

            "css_6_s1_title" to "Team Roles & CSS Classes",
            "css_6_s1_desc" to "Documenting standard roles: .mama gets Gold, .student gets Indigo!",
            "css_6_s1_hint" to "Define class styling selectors in CSS.",

            "js_7_s1_title" to "Recession-Proof Pricing",
            "js_7_s1_desc" to "Know your numbers! Create an algorithm that adds income streams and subtracts expenses to output net profit in Rand.",
            "js_7_s1_hint" to "Calculate net profit in Rand.",

            "html_8_s1_title" to "Input Fields for Feedback",
            "html_8_s1_desc" to "Collect emails consistently to master your marketing. Create an email input field.",
            "html_8_s1_hint" to "Type <input type=\"email\" placeholder=\"Enter your email\" /> in the simulator.",

            "python_9_s1_title" to "90-Day Goal Forecaster",
            "python_9_s1_desc" to "Write a Python loop to forecast sales growing by 15% each month for the next 3 months.",
            "python_9_s1_hint" to "Write loop forecasting sales compounding.",

            "js_10_s1_title" to "Automating Daily Checklist Steps",
            "js_10_s1_desc" to "Only scale what already works by documenting SOPs. Write a JS loop that outputs the 6-Step Plan.",
            "js_10_s1_hint" to "Develop loops listing business SOPs."
        ),
        "zu" to mapOf(
            "html_1_title" to "Isingeniso ku-HTML (Web Layout)",
            "html_1_desc" to "Isitolo Sikamama se-Spaza e-Inthanethi",
            "css_2_title" to "Ukwengeza Isitayela nge-CSS",
            "css_2_desc" to "Ukwenza Ikhathalogi Yakho Ibe Nzihle",
            "js_3_title" to "Ukubala ne-JavaScript",
            "js_3_desc" to "Ukubala Isinkwa Nemiyalelo Ka-Tamatisi",
            "python_4_title" to "I-Python Yokulima Okuhlakaniphile",
            "python_4_desc" to "Ukubikezela Kokuvuna Nesivuno",
            "html_5_title" to "Ikhasi le-StoryBrand",
            "html_5_desc" to "Dala Izihloko Eziguqula Abathengi",
            "css_6_title" to "Visual Branding & Izindima zeThimba",
            "css_6_desc" to "Faka Umbala Kuma-SOP Nemisebenzi",
            "js_7_title" to "Inzuzo ye-Spaza & Imali Engenayo",
            "js_7_desc" to "Ukubala Imali Ukuze Uhlale Uvikelekile",
            "html_8_title" to "Ukusethwa Kwefomu Lemibono",
            "html_8_desc" to "Izinto Zokufaka Imininingwane Yekhasimende",
            "python_9_title" to "Uhlelo Lwezimali Lwezinsuku Ezingama-90",
            "python_9_desc" to "Izindlela Zokuhlola Ezisekelwe Kwizihibe",
            "js_10_title" to "SOP Task Automation Ideshibhodi",
            "js_10_desc" to "Ukwandisa Izinhlelo ze-Spaza Ngokwedijithali",

            "html_1_s1_title" to "Siyakwamukela ku-HTML!",
            "html_1_s1_desc" to "HTML yakha amathambo ewebhusayithi. Namuhla sizokwakha isitolo sika-Mama esiku-inthanethi nesilula emalokishini.",
            "html_1_s1_hint" to "Chofoza Okulandelayo ukuze uqhubeke!",
            "html_1_s2_title" to "Bhala Isihloko Esikhulu (<h1>)",
            "html_1_s2_desc" to "Ithegi ka-<h1> ihlonza isihloko esikhulu sesitolo. Bhala <h1>Mam's Spaza Shop</h1> ukuze sitolise iwebhusayithi yakho.",
            "html_1_s2_hint" to "Bhala <h1>Mam's Spaza Shop</h1> ku-simulator.",
            "html_1_s3_title" to "Uhlu Lwemikhiqizo (<p> & <ul>)",
            "html_1_s3_desc" to "Dala uhlu lwemikhiqizo njengesinkwa nobisi usebenzisa amathegi e-<ul> nelungu le-<li> kwiwebhusayithi yakho.",
            "html_1_s3_hint" to "Faka amathegi we-<p> nowe-<ul>.",

            "css_2_s1_title" to "Izisekelo ze-CSS",
            "css_2_s1_desc" to "I-CSS ishuna imibala nefomethi yewebhusayithi. Uhlelo lwethu lokusebenza luhlobe ngemibala yama-Khosi (Ophephuli noGolide).",
            "css_2_s1_hint" to "Funda umthetho wokuhlobisa we-CSS basic",
            "css_2_s2_title" to "Ukulungisa Imibala (color & background)",
            "css_2_s2_desc" to "Faka umbala wegolide (color: gold;) kanye nemuva emnyama (background-color: #121212;) kwi-webhusayithi yakho.",
            "css_2_s2_hint" to "Sebenzisa i-background-color ne-color.",

            "js_3_s1_title" to "Yini i-JavaScript?",
            "js_3_s1_desc" to "U-JavaScript wenza isizindalwazi sisebenze. Sizobala intengo yesinkwa nezithelo namakhasimende kwi-spaza.",
            "js_3_s1_hint" to "Qonda okuguquguqukayo kwe-JS kanye ne-logic",
            "js_3_s2_title" to "Bhala i-Calculator Yakho Yokugcina",
            "js_3_s2_desc" to "Bhala umsebenzi ka-JS obala i-total yamakhasimende ethu. Sisebenzisa amagama afana nelithi const.",
            "js_3_s2_hint" to "Thuthukisa indlela yokubala ngamaRandi",

            "python_4_s1_title" to "Python Yokulima Okuhlakaniphile",
            "python_4_s1_desc" to "I-Python iwusizo kakhulu ekubaleni isivuno semikhakha yezolimo ezabelweni zasekhaya letisizayo.",
            "python_4_s1_hint" to "I-Python basic syntax and prints",
            "python_4_s2_title" to "Umhloli Wezemvelo (if/else)",
            "python_4_s2_desc" to "Bhala i-Python ehlola izinga lokushisa lenhlabathi. Uma kushisa kakhulu (>30), kumele sichelele kabili.",
            "python_4_s2_hint" to "Bhala izitatimende ezinemibandela ku-Python.",

            "html_5_s1_title" to "Isihloko Se-Hero (<h1>)",
            "html_5_s1_desc" to "Ngaphansi kwe-StoryBrand, ikhasimende lakho iyi-Hero! Bhala isihloko esicacile.",
            "html_5_s1_hint" to "Bhala <h1>Grow Your Business with KodeMamas</h1> kwi-simulator.",
            "html_5_s2_title" to "Inkinobho Yokuthatha Isinyathelo",
            "html_5_s2_desc" to "Yenza kube lula ukuthenga! Sebenzisa i-<button>.",
            "html_5_s2_hint" to "Bhala <button>Join Training Now</button>.",

            "css_6_s1_title" to "Izindima zeThimba & CSS Classes",
            "css_6_s1_desc" to "I-CSS ishuna ama-SOP. O-Mama bathola Igolide, Abafundi bathola i-Indigo!",
            "css_6_s1_hint" to "Chaza izinkomba ze-CSS.",

            "js_7_s1_title" to "Ukubala Imali Yokuphepha",
            "js_7_s1_desc" to "Bala imali egciniwe net ngomsebenzi obala inzuzo.",
            "js_7_s1_hint" to "Bala inzuzo net ngamaRandi.",

            "html_8_s1_title" to "Izinkundla Zokufaka Impendulo",
            "html_8_s1_desc" to "Khoda into yokufaka i-imeyili yekhasimende.",
            "html_8_s1_hint" to "Faka <input type=\"email\" />.",

            "python_9_s1_title" to "Isibikezeli Sezinsuku Ezingama-90",
            "python_9_s1_desc" to "Bhala iluphu ye-Python ebikezela ukukhula.",
            "python_9_s1_hint" to "Bhala ikhodi ekhombisa inzuzo.",

            "js_10_s1_title" to "Ukuzenzakalela kwe-Checklist",
            "js_10_s1_desc" to "Bhala ama-SOP kwi-iluphu ye-JS ephrinta amaphuzu wethu we-6-Step Plan.",
            "js_10_s1_hint" to "Sebenzisa loops ezibhala ama-SOP."
        ),
        "xh" to mapOf(
            "html_1_title" to "Intshayelelo ye-HTML",
            "html_1_desc" to "Isitolo seSpaza sikaMama",
            "css_2_title" to "Ukongeza iSitayile nge-CSS",
            "css_2_desc" to "Ukwenza Ikhathalogu Yakho Ibe Ntle",
            "js_3_title" to "Ubalo ne-JavaScript",
            "js_3_desc" to "Ukubala Isonka Nemifuno",
            "python_4_title" to "I-Python yezoLimo oluPhucukileyo",
            "python_4_desc" to "Uqikelelo Lwesivuno naMaxabiso",
            "html_5_title" to "Ikhasi le-StoryBrand",
            "html_5_desc" to "Dala Izihloko Eziguqula Abathengi",
            "css_6_title" to "Visual Branding & Izindima zeQela",
            "css_6_desc" to "Faka Umbala Kuma-SOP Nemisebenzi",
            "js_7_title" to "Spaza Profit & Cash Flow",
            "js_7_desc" to "Ukubala Imali Ukuze Uhlale Ukhuselekile",
            "html_8_title" to "Ukusethwa Kwefomu Lemibono",
            "html_8_desc" to "Izinto Zokufaka Iinkcukacha Zabathengi",
            "python_9_title" to "Uhlelo Lwemali lweentsuku ezingama-90",
            "python_9_desc" to "Iindlela Zokuhlola Ezisekelwe Kwizihibe",
            "js_10_title" to "SOP Task Automation Ideshibhodi",
            "js_10_desc" to "Ukwandisa Izicelo zeSpaza Ngokwedijithali",

            "html_1_s1_title" to "Wamkelekile kwi-HTML!",
            "html_1_s1_desc" to "I-HTML yakha amathambo ewebhusayithi. Namhlanje siza kwakha isitolo se-inthanethi sikaMama saseBloemfontein.",
            "html_1_s1_hint" to "Cofa Okulandelayo ukuze uqhubeke!",
            "html_1_s2_title" to "Ukubhala Isihloko sethu sokuqala (<h1>)",
            "html_1_s2_desc" to "Ithegi ka-<h1> ichaza isihloko esikhulu. Bhala <h1>Mam's Spaza Shop</h1> ukunika iwebhusayithi yakho ibhana entle.",
            "html_1_s2_hint" to "Bhala <h1>Mam's Spaza Shop</h1> ku-simulator wetshathi.",
            "html_1_s3_title" to "Udederhu lweeMveliso (<p> & <ul>)",
            "html_1_s3_desc" to "Dala uluhlu lweemveliso ezifana nesonka nebisana usebenzisa iitshathi ze-<ul> kunye ne-<li> kwisayithi yakho.",
            "html_1_s3_hint" to "Faka iitshathi ze-<p> ne-<ul>.",

            "css_2_s1_title" to "Iikhonsepthi ze-CSS",
            "css_2_s1_desc" to "I-CSS ilungelelanisa imibala nefomathi yewebhusayithi. Izinto zethu ziza kuqaqamba ngemibala ephephuli negolide.",
            "css_2_s1_hint" to "Funda isiseko senkqubo ye-CSS",
            "css_2_s2_title" to "Ukutshintsha Imibala (color & background)",
            "css_2_s2_desc" to "Faka umbala wegolide (color: gold;) kunye nomphandle omnyama (background-color: #121212;) kwisakhiwo sakho.",
            "css_2_s2_hint" to "Sebenzisa i-background-color kunye ne-color.",

            "js_3_s1_title" to "Yintoni i-JavaScript?",
            "js_3_s1_desc" to "I-JavaScript yenza i-webhusayithi isebenze kakhulu. Siza kubala ixabiso lesonka nemifuno ngaxeshanye.",
            "js_3_s1_hint" to "Qonda ukuguquguquka kwe-JS kunye nelogic",
            "js_3_s2_title" to "Bhala iKhalkhuleyitha yakho yokuqala",
            "js_3_s2_desc" to "Bhala umsebenzi we-JS obala i-total ye-odolo yabathengi bethu usebenzisa variables ezifana ne-const.",
            "js_3_s2_hint" to "Dala i-formula yokubala nge-Rand",

            "python_4_s1_title" to "I-Python yezoLimo oluPhucukileyo",
            "python_4_s1_desc" to "I-Python ilunge kakhulu ekubaleni isivuno sethu semizi yolimo yaselokishini namaxabiso emaraka.",
            "python_4_s1_hint" to "Funda isiseko se-Python",
            "python_4_s2_title" to "Uvavanyo loBushushu Bomhlaba (if/else)",
            "python_4_s2_desc" to "Bhala ikhodi ye-Python ejonga ubushushu bomhlaba. Ukuba ubushushu bungaphezulu kuka-30, kufuneka amanzi aphindwe kabini.",
            "python_4_s2_hint" to "Bhala izitatimende ezinemiqathango kwi-Python.",

            "html_5_s1_title" to "Isihloko Se-Hero (<h1>)",
            "html_5_s1_desc" to "Ngaphantsi kwe-StoryBrand, umthengi wakho yi-Hero! Bhala isihloko.",
            "html_5_s1_hint" to "Bhala <h1>Grow Your Business with KodeMamas</h1> kwi-simulator.",
            "html_5_s2_title" to "Iqhosha Lokuthatha Inyathelo",
            "html_5_s2_desc" to "Yenza kube lula ukuthenga! Sebenzisa i-<button> tag.",
            "html_5_s2_hint" to "Bhala <button>Join Training Now</button>.",

            "css_6_s1_title" to "Iindima zeQela & CSS Classes",
            "css_6_s1_desc" to "Igolide kooMama, i-Indigo kubafundi!",
            "css_6_s1_hint" to "Chaza iiklasi ze-CSS.",

            "js_7_s1_title" to "Amaxabiso Akhuselekileyo",
            "js_7_s1_desc" to "Bala imali egciniweyo net.",
            "js_7_s1_hint" to "Bala inzuzo net ngeerandi.",

            "html_8_s1_title" to "Iindawo Zokufaka Impendulo",
            "html_8_s1_desc" to "Khowuda into yokufaka i-imeyile.",
            "html_8_s1_hint" to "Faka <input type=\"email\" />.",

            "python_9_s1_title" to "Isibikezeli Seentsuku ezingama-90",
            "python_9_s1_desc" to "Bhala iluphu ye-Python ebonisa ukukhula.",
            "python_9_s1_hint" to "Bhala ikhowudi ebonisa inzuzo.",

            "js_10_s1_title" to "Ukuzenzekela kwe-Checklist",
            "js_10_s1_desc" to "Bhala ii-SOP kwi-iluphu ye-JS.",
            "js_10_s1_hint" to "Sebenzisa iilophu ezibhala ii-SOP."
        ),
        "af" to mapOf(
            "html_1_title" to "Inleiding tot HTML-uitleg",
            "html_1_desc" to "Mam se Spaza-winkelfront",
            "css_2_title" to "Styl byvoeg met CSS",
            "css_2_desc" to "Verfraaiing van u aanlyn katalogus",
            "js_3_title" to "Interaktiewe JS-rekeninge",
            "js_3_desc" to "Berekening van brood en groente bestellings",
            "python_4_title" to "Python Oes Tracker",
            "python_4_desc" to "Oesvordering en prysvoorspellings",
            "html_5_title" to "StoryBrand Landingsblad",
            "html_5_desc" to "Skep Hoë-Omskakeling Opskrifte",
            "css_6_title" to "Visuele Handelsmerk & Spanklasse",
            "css_6_desc" to "Kleurkodering van SOPs en Rolle",
            "js_7_title" to "Spaza Wins & Kontantvloei",
            "js_7_desc" to "Resessiebestande Inkomstespoorders",
            "html_8_title" to "Kliëntterugvoer Vorm",
            "html_8_desc" to "Invoervelde vir Kliënteaanwysings",
            "python_9_title" to "90-Dae Voorspellende Beplanner",
            "python_9_desc" to "Stelsels & Lusgebaseerde Groeispoorders",
            "js_10_title" to "SOP Outomatisering Paneelbord",
            "js_10_desc" to "Digitale Skaal van Spazastelsels",

            "html_1_s1_title" to "Welkom by HTML!",
            "html_1_s1_desc" to "HTML bou die basiese struktuur van elke webwerf. Vandag bou ons Mam se aanlyn spaza-winkelfront in Bloemfontein.",
            "html_1_s1_hint" to "Klik Volgende om voort te gaan!",
            "html_1_s2_title" to "Skryf Ons Eerste Opskrif (<h1>)",
            "html_1_s2_desc" to "Die <h1> tag definieer die hoofopskrif. Skryf <h1>Mam's Spaza Shop</h1> om u winkel se banier akkuraat te vertoon.",
            "html_1_s2_hint" to "Tik <h1>Mam's Spaza Shop</h1> in die simuleerder.",
            "html_1_s3_title" to "Lys van Produkte (<p> & <ul>)",
            "html_1_s3_desc" to "Maak 'n lys van produkte soos vars brood en vars melk met behulp van die <p>, <ul> en <li> tags.",
            "html_1_s3_hint" to "Voeg <p> en <ul> tags by.",

            "css_2_s1_title" to "CSS-stileringskonsepte",
            "css_2_s1_desc" to "CSS beheer die kleure en uitleg. Ons eie spaza-webblad sal pragtig lyk met pers en goud temas.",
            "css_2_s1_hint" to "Leer die basiese reëls van CSS",
            "css_2_s2_title" to "Kleure Aanpas (color & background)",
            "css_2_s2_desc" to "Stel tekskleur na goud (color: gold;) en voeg 'n ryk donker agtergrond (background-color: #121212;) by.",
            "css_2_s2_hint" to "Gebruik agtergrondkleur en tekskleur eiers.",

            "js_3_s1_title" to "Wat is JavaScript?",
            "js_3_s1_desc" to "JavaScript maak u winkelfront interaktief! Ons gaan bestellings outomaties bereken sonder om te herlaai.",
            "js_3_s1_hint" to "Verstaan veranderlikes en JS-logika",
            "js_3_s2_title" to "Skryf jou Eerste Berekening",
            "js_3_s2_desc" to "Skryf 'n JS-funksie wat die totale prys van produkte in Rand korrek uitwerk deur veranderlikes te gebruik.",
            "js_3_s2_hint" to "Ontwikkel 'n berekeningformule in Suid-Afrikaanse Rand",

            "python_4_s1_title" to "Python vir Slim Boerdery",
            "python_4_s1_desc" to "Python is fantasties om oesopbrengste en markpryse in plaaslike gemeenskapstuine akkuraat te voorspel.",
            "python_4_s1_hint" to "Basiese Python-sintaks",
            "python_4_s2_title" to "Temperatuurkontroleerder (if/else)",
            "python_4_s2_desc" to "Skryf 'n Python-skrif wat grondtemperatuur meet en boere waarsku as besproeiing moet verdubbel (>30 grade).",
            "python_4_s2_hint" to "Skryf voorwaardelike stellings in Python.",

            "html_5_s1_title" to "Held Afdeling Opskrif (<h1>)",
            "html_5_s1_desc" to "Onder StoryBrand is u kliënt die Held! Skryf 'n duidelike opskrif.",
            "html_5_s1_hint" to "Tik <h1>Grow Your Business with KodeMamas</h1> in die simuleerder.",
            "html_5_s2_title" to "Oproep-tot-aksie Knoppie",
            "html_5_s2_desc" to "Maak dit maklik om aan te sluit! Gebruik <button>.",
            "html_5_s2_hint" to "Tik <button>Join Training Now</button>.",

            "css_6_s1_title" to "Spanrolle & CSS Klasse",
            "css_6_s1_desc" to "Goud vir Mammas, Indigo vir Studente!",
            "css_6_s1_hint" to "Definieer klasse in CSS.",

            "js_7_s1_title" to "Veilige Prysberekening",
            "js_7_s1_desc" to "Bereken netto wins in Rand.",
            "js_7_s1_hint" to "Bereken netto wins in Rand.",

            "html_8_s1_title" to "Terugvoer Invoervelde",
            "html_8_s1_desc" to "Skep 'n e-pos invoerveld.",
            "html_8_s1_hint" to "Tik <input type=\"email\" /> in.",

            "python_9_s1_title" to "90-Dae Voorspeller",
            "python_9_s1_desc" to "Skryf 'n Python-lus wat verkope voorspel.",
            "python_9_s1_hint" to "Skryf 'n saamgestelde verkoopslus.",

            "js_10_s1_title" to "Kontrolelys Outomatisering",
            "js_10_s1_desc" to "Skryf SOPs in 'n JS-lus.",
            "js_10_s1_hint" to "Gebruik lusse vir besigheids-SOPs."
        ),
        "nso" to mapOf(
            "html_1_title" to "Matseno a HTML (Web Layout)",
            "html_1_desc" to "Storefront ya Shop ya Spaza ya Mam",
            "css_2_title" to "Go oketša Style ka CSS",
            "css_2_desc" to "Moago wa wepsaete ya Spaza",
            "js_3_title" to "Dipalo tsa JS tsa go ithuta",
            "js_3_desc" to "Go bala ditaelo tša borotho le merogo",
            "python_4_title" to "Tsela ya Crop Tracker ka Python",
            "python_4_desc" to "Tlhahlobo tša dipalo tša puno",
            "html_5_title" to "Letlakala la StoryBrand",
            "html_5_desc" to "Hlama dihlogo tše di fetošago bareki",
            "css_6_title" to "Visual Branding & Dikarolo tša Sehlopha",
            "css_6_desc" to "Mebala ya di-SOP & maikarabelo",
            "js_7_title" to "Inzuzo ya Spaza & Phallo ya Tšhelete",
            "js_7_desc" to "Go bala tšhelete go dula o bolokegile",
            "html_8_title" to "Peakanyo ya Fomo ya Dintlha",
            "html_8_desc" to "Dintlha tša go faka dintlha tša bareki",
            "python_9_title" to "Peakanyo ya Matšatši a 90",
            "python_9_desc" to "Mekgwa ya go gola ya go šomiša loops",
            "js_10_title" to "SOP Task Automation Letlakala",
            "js_10_desc" to "Go godiša dikgwebo tša Spaza ka tsela ya digijithale",

            "html_1_s1_title" to "Re a go amogela go HTML!",
            "html_1_s1_desc" to "O amogetswe! HTML e tloša moago wa wepsaete. Lehono re tlo aga wepsaete ya lebenkele la spaza la Mam.",
            "html_1_s1_hint" to "Kgotla Next go tšwela pele!",
            "html_1_s2_title" to "Go ngwala Hlogo (<h1>)",
            "html_1_s2_desc" to "Ngwala hlogo e kgolo ya lebenkele ka tag ya <h1> go bontšha leina la gago la spaza ka botlalo.",
            "html_1_s2_hint" to "Ngwala <h1>Mam's Spaza Shop</h1> ka mo simulator.",
            "html_1_s3_title" to "Lenaneo la dilo (<p> & <ul>)",
            "html_1_s3_desc" to "Ngwala lelokelelo la dilo tša go reka go swana le borotho le maswi o šomiša ditaetšo tša <p>, <ul> le <li>.",
            "html_1_s3_hint" to "Oketša ditags tša <p> le <ul>.",

            "css_2_s1_title" to "Go Ithuta ka CSS",
            "css_2_s1_desc" to "CSS e laola mebala le moago. Wepsaete ya gago ya spaza e tlo phadima ka mebala ye mebotse ya phephole le gauta.",
            "css_2_s1_hint" to "Ithute ka melao ya motheo ya CSS",
            "css_2_s2_title" to "Go Fetola Mebala (color & background)",
            "css_2_s2_desc" to "Šomiša mmala wa gauta (color: gold;) le background ye ntsho (background-color: #121212;) go moago wa gago.",
            "css_2_s2_hint" to "Šomiša ditaetšo tša background-color le color.",

            "js_3_s1_title" to "Ke eng JavaScript?",
            "js_3_s1_desc" to "JS e dira wepsaete ya gago go phela! Re sa tlo bala madi a ditaelo tša borotho le merogo kapele.",
            "js_3_s1_hint" to "Kwišiša di-variables le dipalo tša JS",
            "js_3_s2_title" to "Ngwala Kakaretšo ya Dipalo",
            "js_3_s2_desc" to "Ngwala dipalo tša JS tšeo di balago madi a ditaelo tša bareki ka Rand o šomiša ditiro tša const.",
            "js_3_s2_hint" to "Aga mokgwa wa go bala ka Rand",

            "python_4_s1_title" to "Python ya Temo ya segajabone",
            "python_4_s1_desc" to "Python e thabiša kudu go bala dipalo tša go buna le dipalo tša go rekisa ka dirapeng tša selegae.",
            "python_4_s1_hint" to "Motheo wa go ngwala gakaone ka Python",
            "python_4_s2_title" to "Tekanyo ya go ruthela mabu (if/else)",
            "python_4_s2_desc" to "Ngwala Python e lekanyetšago go ruthela ga mabu. Ge go fisa go feta 30, tshela meetse gabeli.",
            "python_4_s2_hint" to "Ngwala ditatamente tša go lekola maemo ka Python.",

            "html_5_s1_title" to "Hlogo ya Karolo ya Hero (<h1>)",
            "html_5_s1_desc" to "Bareki ba gago ke bagale! Ngwala hlogo e botse.",
            "html_5_s1_hint" to "Ngwala <h1>Grow Your Business with KodeMamas</h1> kwi-simulator.",
            "html_5_s2_title" to "Inkinobho Yokuthatha Isinyathelo",
            "html_5_s2_desc" to "Šomiša <button> tag go hlama inkinobho.",
            "html_5_s2_hint" to "Ngwala <button>Join Training Now</button>.",

            "css_6_s1_title" to "Izindima weThimba & CSS Classes",
            "css_6_s1_desc" to "Mmala wa gauta go bo-Mama, mmala wa Indigo go barutwana!",
            "css_6_s1_hint" to "Chaza dintlha tša CSS.",

            "js_7_s1_title" to "Go bala tšhelete go dula o bolokegile",
            "js_7_s1_desc" to "Bala madi a bolokilwego net.",
            "js_7_s1_hint" to "Bala inzuzo net ka diranta.",

            "html_8_s1_title" to "Dintlha tša go faka Feedback",
            "html_8_s1_desc" to "Kgoboketša di-email ka mehla.",
            "html_8_s1_hint" to "Faka <input type=\"email\" />.",

            "python_9_s1_title" to "Isibikezeli Sezinsuku tša matšatši a 90",
            "python_9_s1_desc" to "Ngwala luphu ya Python ebikezelang go gola.",
            "python_9_s1_hint" to "Ngwala khoutu e bontšhang inzuzo.",

            "js_10_s1_title" to "Ukuzenzakalela kwe-Checklist",
            "js_10_s1_desc" to "Ngwala di-SOP tša gago.",
            "js_10_s1_hint" to "Šomiša loops go ngwala di-SOP tša kgwebo."
        ),
        "tn" to mapOf(
            "html_1_title" to "Matseno ko HTML layout",
            "html_1_desc" to "Storefront sa spaza sa ga Mam",
            "css_2_title" to "Go oketsa Setale ka CSS",
            "css_2_desc" to "Metshameko ya go nkgisa catalog",
            "js_3_title" to "JS e interaktibong dipalo",
            "js_3_desc" to "Go bala madi a ditaelo tsa rona",
            "python_4_title" to "Python Crop Tracker ya dipalo",
            "python_4_desc" to "Dipalo tsa madi a go reka ditsela",
            "html_5_title" to "Letlhare la StoryBrand",
            "html_5_desc" to "Tlhama dihlogo tse di fetolang bareki",
            "css_6_title" to "Boitshupo jwa Ponalo & Karolo tsa Sehopha",
            "css_6_desc" to "Go khouta ka mebala ga di-SOP",
            "js_7_title" to "Inzuzo ya Spaza & Phelelo ya Madi",
            "js_7_desc" to "Go bala madi go dula o bolokegile",
            "html_8_title" to "Peakanyo ya Fomo ya Bareki",
            "html_8_desc" to "Dintlha tsa go faka dintlha tsa bareki",
            "python_9_title" to "Peakanyo ya Malatsi a 90",
            "python_9_desc" to "Ditsela tsa go gola tsa go dirisa loops",
            "js_10_title" to "SOP Task Automation Letlhare",
            "js_10_desc" to "Go godisa dikgwebo tsa Spaza ka tsela ya digijithale",

            "html_1_s1_title" to "HTML e a go amogela!",
            "html_1_s1_desc" to "HTML e aga mmele wa wepsaete efe kapa efe. Gompieno re tla aga maraka a spaza sa ga Mam mo Bloemfontein.",
            "html_1_s1_hint" to "Tobetsa Next go tswelela!",
            "html_1_s2_title" to "Go Kwala Hlogo ya Rona (<h1>)",
            "html_1_s2_desc" to "Kwala hlogo e kgolo ya gago ka tag ya <h1> go bontsha leina la spaza sa gago mo godimo.",
            "html_1_s2_hint" to "Kwala <h1>Mam's Spaza Shop</h1> mo simulator.",
            "html_1_s3_title" to "Tsenya dilo mo lenaneong (<p> & <ul>)",
            "html_1_s3_desc" to "Dira lenaneo la dilo tse di rekiwang jaaka borotho le mashi ka ditsela tsa tags tsa <p>, <ul> le <li>.",
            "html_1_s3_hint" to "Tsenya ditags tsa <p> le <ul>.",

            "css_2_s1_title" to "Go Shuna ka CSS ka Bonolo",
            "css_2_s1_desc" to "CSS e laola mebala ya wepsaete. Lebenkele la rona le tla kganya ka mmala o mohibidu, o o phepole, le o mokgona.",
            "css_2_s1_hint" to "Ithute melao ya motheo ya go kgabisa ka CSS",
            "css_2_s2_title" to "Fetola Mebala (color & background)",
            "css_2_s2_desc" to "Tsenya mmala wa gauta (color: gold;) gaufi le bokgoni jo bontsho (background-color: #121212;) mo wepsaeteng.",
            "css_2_s2_hint" to "Kwala ditsela tsa gauta le background.",

            "js_3_s1_title" to "JavaScript ke eng?",
            "js_3_s1_desc" to "JS e dira gore maraka a gago a thuse bareki ka bonako! Re tla bala dipalo tsa madi a ditaelo tsa gago.",
            "js_3_s1_hint" to "Tlhaloganya di-variables gaufi le JS logic",
            "js_3_s2_title" to "Kwala Kakanyetso ya Gago ya JS",
            "js_3_s2_desc" to "Kwala dipalo tsa JS tse di balang madi otlhe a ditaelo tsa bareki ba rona ba ba rekayang rona.",
            "js_3_s2_hint" to "itsetse dipalo tsa ditsela ka madi a Rand",

            "python_4_s1_title" to "Python ya Temo e e Botlhale",
            "python_4_s1_desc" to "Python e siame thata go bala thobo mo masimong a rona a selegae le go itse madi a re tlang go a bona.",
            "python_4_s1_hint" to "Dipalo tsa motheo mo go Python",
            "python_4_s2_title" to "Go Tlhola Kemo ya Mabu (if/else)",
            "python_4_s2_desc" to "Kwala algoriteme ya Python e tlhola bolelo jwa mabu. Fa go le thutha go feta 30, oketsa ditsela x2.",
            "python_4_s2_hint" to "Kwala ditatamente tsa gago ka Python.",

            "html_5_s1_title" to "Hlogo ya Karolo ya Hero (<h1>)",
            "html_5_s1_desc" to "Bareki ba gago ke bagale! Kwala hlogo e botse.",
            "html_5_s1_hint" to "Kwala <h1>Grow Your Business with KodeMamas</h1> kwi-simulator.",
            "html_5_s2_title" to "Inkinobho Yokuthatha Isinyathelo",
            "html_5_s2_desc" to "Dirisa <button> tag go tlhama inkinobho.",
            "html_5_s2_hint" to "Kwala <button>Join Training Now</button>.",

            "css_6_s1_title" to "Izindima weThimba & CSS Classes",
            "css_6_s1_desc" to "Mmala wa gauta go bo-Mama, mmala wa Indigo go barutwana!",
            "css_6_s1_hint" to "Chaza dintlha tsa CSS.",

            "js_7_s1_title" to "Go bala madi go dula o bolokegile",
            "js_7_s1_desc" to "Bala madi a bolokilwego net.",
            "js_7_s1_hint" to "Bala inzuzo net ka diranta.",

            "html_8_s1_title" to "Dintlha tsa go faka Feedback",
            "html_8_s1_desc" to "Kgoboketsa di-email ka mehla.",
            "html_8_s1_hint" to "Faka <input type=\"email\" />.",

            "python_9_s1_title" to "Isibikezeli Sezinsuku tsa malatsi a 90",
            "python_9_s1_desc" to "Kwala luphu ya Python ebikezelang go gola.",
            "python_9_s1_hint" to "Kwala khoutu e bontshang inzuzo.",

            "js_10_s1_title" to "Ukuzenzakalela kwe-Checklist",
            "js_10_s1_desc" to "Kwala di-SOP tsa gago.",
            "js_10_s1_hint" to "Dirisa loops go kwala di-SOP tsa kgwebo."
        ),
        "st" to mapOf(
            "html_1_title" to "Kenyaletso ho HTML layout",
            "html_1_desc" to "Storefront ya spaza sa Mam",
            "css_2_title" to "Ho eketsa Style ka CSS",
            "css_2_desc" to "Ho natefisa buka ya mabenkele",
            "js_3_title" to "JS e interaktibong dipalo",
            "js_3_desc" to "Ubalo la ho jwala le ho rekisa",
            "python_4_title" to "Python Crop Tracker ya temo",
            "python_4_desc" to "Dipalo tsa madi a selemo sena",
            "html_5_title" to "Leqephe la StoryBrand",
            "html_5_desc" to "Theha dihlooho tse fetolang bareki",
            "css_6_title" to "Boitshupo ba Ponahalo & Karolo tsa Sehlopha",
            "css_6_desc" to "Ho khouta ka mebala ha di-SOP",
            "js_7_title" to "Inzuzo ya Spaza & Phallo ya Tjhelete",
            "js_7_desc" to "Ho bala tjhelete ho dula o bolokehile",
            "html_8_title" to "Ukusethwa ha Feedback Form",
            "html_8_desc" to "Dintlha tsa ho faka dintlha tsa bareki",
            "python_9_title" to "Peakanyo ya Matsatsi a 90",
            "python_9_desc" to "Ditsela tsa ho gola tsa ho sebedisa loops",
            "js_10_title" to "SOP Task Automation Leqephe",
            "js_10_desc" to "Ho hodisa dikgwebo tsa Spaza ka tsela ya digijithale",

            "html_1_s1_title" to "Re a o amohela ho HTML!",
            "html_1_s1_desc" to "HTML e haha mmele wa webosaete. Kajeno re tla haha webosaete ya lebenkele la spaza la Mam.",
            "html_1_s1_hint" to "Tobetsa Next ho tswela pele!",
            "html_1_s2_title" to "Ho Ngola Hlooho (<h1>)",
            "html_1_s2_desc" to "Ngola hlooho e kgolo ya lebenkele ka tag ya <h1>.",
            "html_1_s2_hint" to "Ngola <h1>Mam's Spaza Shop</h1> ho simulator.",
            "html_1_s3_title" to "Lenane la Dintho (<p> & <ul>)",
            "html_1_s3_desc" to "Etsa lenane la dintho tse rekiswang jwaloka bohobe le lebese ka tags tsa <p>, <ul> le <li>.",
            "html_1_s3_hint" to "Kenya ditags tsa <p> le <ul>.",

            "css_2_s1_title" to "Ho Ithuta ka CSS",
            "css_2_s1_desc" to "CSS e laola mebala le sebopeho sa webosaete.",
            "css_2_s1_hint" to "Ithute melao ya motheo ya CSS",
            "css_2_s2_title" to "Ho Fetola Mebala (color & background)",
            "css_2_s2_desc" to "Sebedisa mmala wa gauta le background e ntsho.",
            "css_2_s2_hint" to "Sebedisa ditaelo tsa background-color le color.",

            "js_3_s1_title" to "Ke eng JavaScript?",
            "js_3_s1_desc" to "JS e etsa hore webosaete ya hao e sebetse ka potlako!",
            "js_3_s1_hint" to "Utlwisisa di-variables le JS logic",
            "js_3_s2_title" to "Ngola Khalkhuleita ya Hao",
            "js_3_s2_desc" to "Ngola dipalo tsa JS tse balang tjhelete kaofela ya di-odara tsa bareki.",
            "js_3_s2_hint" to "Theha mokgwa wa ho bala ka Ranta",

            "python_4_s1_title" to "Python ya Temo e Bohlale",
            "python_4_s1_desc" to "Python e molemo haholo ho bala kotulo masimong a rona.",
            "python_4_s1_hint" to "Dipalo tsa motheo ho Python",
            "python_4_s2_title" to "Ho Hlahloba Boemo ba Mobu (if/else)",
            "python_4_s2_desc" to "Ngola Python e hlahlobang mocheso wa mobu.",
            "python_4_s2_hint" to "Ngola ditatamente tsa maemo ho Python.",

            "html_5_s1_title" to "Hlooho ya Karolo ya Hero (<h1>)",
            "html_5_s1_desc" to "Bareki ba hao ke bahale! Ngola hlooho e ntle.",
            "html_5_s1_hint" to "Ngola <h1>Grow Your Business with KodeMamas</h1> kwi-simulator.",
            "html_5_s2_title" to "Konopo ya ho nka Kgato",
            "html_5_s2_desc" to "Sebedisa <button> tag ho theha konopo.",
            "html_5_s2_hint" to "Ngola <button>Join Training Now</button>.",

            "css_6_s1_title" to "Dikarolo tsa Sehlopha & CSS Classes",
            "css_6_s1_desc" to "Mmala wa gauta ho bo-Mama, mmala wa Indigo ho barutwana!",
            "css_6_s1_hint" to "Chaza dintlha tsa CSS.",

            "js_7_s1_title" to "Ho bala tjhelete ho dula o bolokehile",
            "js_7_s1_desc" to "Bala tjhelete e bolokilweng net.",
            "js_7_s1_hint" to "Bala dipoelo net ka diranta.",

            "html_8_s1_title" to "Dintlha tsa ho faka Feedback",
            "html_8_s1_desc" to "Kgoboketsa di-email kamehla.",
            "html_8_s1_hint" to "Faka <input type=\"email\" />.",

            "python_9_s1_title" to "Isibikezeli sa Matsatsi a 90",
            "python_9_s1_desc" to "Ngola loop ya Python e bolelang ho gola.",
            "python_9_s1_hint" to "Ngola khoutu e bontshang dipoelo.",

            "js_10_s1_title" to "Ukuzenzakalela ha Checklist",
            "js_10_s1_desc" to "Ngola di-SOP tsa gago.",
            "js_10_s1_hint" to "Sebedisa loops ho ngola di-SOP tsa kgwebo."
        ),
        "ts" to mapOf(
            "html_1_title" to "Xingheniso eka HTML",
            "html_1_desc" to "Xitolo xa Spaza xa Mam eka Inthanete",
            "css_2_title" to "Ku Engetela Xitayili hi CSS",
            "css_2_desc" to "Ku Sasekisa Khathaloko ya Wena",
            "js_3_title" to "Ku Hlaya hi JavaScript",
            "js_3_desc" to "Ku Hlaya Xinkwa na Matamatisi",
            "python_4_title" to "Python eka Vurimi byo Tlhariha",
            "python_4_desc" to "Ku Vhumbha Ntshovelo na Mixavo",
            "html_5_title" to "Tidondzo ta StoryBrand",
            "html_5_desc" to "Endla tinhlokomhaka to guqula va-koki",
            "css_6_title" to "Vutivi bya Ponalo & Ndzima ta Ntlawa",
            "css_6_desc" to "Mivala ya di-SOP & vutihlamuleri",
            "js_7_title" to "Inzuzo ya Spaza & Ntsengo wa Mali",
            "js_7_desc" to "Ku bala mali ku hlayisa ntsengo",
            "html_8_title" to "Ukusethwa kwe fomu ya Feedback",
            "html_8_desc" to "Tifomu to faka dintlha ta bareki",
            "python_9_title" to "Ku bala mali ya ntsengo ya masiku ya 90",
            "python_9_desc" to "Tindlela to kurisa na ku tirhisa loops",
            "js_10_title" to "SOP Task Automation Ideshibhodi",
            "js_10_desc" to "Ku kurisa mabindzu ya Spaza hi ndlela ya digijithale",

            "html_1_s1_title" to "Hi amukele eka HTML!",
            "html_1_s1_desc" to "HTML yi aka miri wa sayiti. Namuntlha hi ta aka xitolo xa spaza xa Mam.",
            "html_1_s1_hint" to "Tsindzela Next ku ya emahlweni!",
            "html_1_s2_title" to "Ku Tsala Nhlokomhaka (<h1>)",
            "html_1_s2_desc" to "Tsala nhlokomhaka leyikulu hi tag ya <h1>.",
            "html_1_s2_hint" to "Tsala <h1>Mam's Spaza Shop</h1> eka simulator.",
            "html_1_s3_title" to "Nxaxamelo wa Swilo (<p> & <ul>)",
            "html_1_s3_desc" to "Endla nxaxamelo wa swilo swo xava hi ku tirhisa <p>, <ul> na <li>.",
            "html_1_s3_hint" to "Engetela ti-tag ta <p> na <ul>.",

            "css_2_s1_title" to "Swisekelo swa CSS",
            "css_2_s1_desc" to "CSS yi cinca mivala na xiyimo xa sayiti.",
            "css_2_s1_hint" to "Dyondza milawu ya CSS",
            "css_2_s2_title" to "Ku Cinca Mivala (color & background)",
            "css_2_s2_desc" to "Tirhisa muvala wa nsuku na muvala wa le ndzhaku wo dzwihala.",
            "css_2_s2_hint" to "Tirhisa background-color na color.",

            "js_3_s1_title" to "Xana JavaScript i Yini?",
            "js_3_s1_desc" to "JS yi endla sayiti yi tirha hi xihatla!",
            "js_3_s1_hint" to "Twisisa ti-variables na JS logic",
            "js_3_s2_title" to "Tsala Khalkhuleyita ya Wena",
            "js_3_s2_desc" to "Tsala ntirho wa JS lowu hlayaka ntsengo wa swilo leswi xaviweke.",
            "js_3_s2_hint" to "Endla ndlela yo hlaya hi tiRandi",

            "python_4_s1_title" to "Python eka Vurimi byo Tlhariha",
            "python_4_s1_desc" to "Python yi pfuna ngopfu ku hlaya ntshovelo emasin'wini.",
            "python_4_s1_hint" to "Swisekelo swa Python",
            "python_4_s2_title" to "Ku Kambela Mahiselo ya Misava (if/else)",
            "python_4_s2_desc" to "Tsala Python leyi kambelaka mahiselo ya misava.",
            "python_4_s2_hint" to "Tsala switatimende swa swiyimo eka Python.",

            "html_5_s1_title" to "Nhlokomhaka ya Hero (<h1>)",
            "html_5_s1_desc" to "Vakoki va wena i tinhenha! Tsala nhlokomhaka leyi.",
            "html_5_s1_hint" to "Tsala <h1>Grow Your Business with KodeMamas</h1> kwi-simulator.",
            "html_5_s2_title" to "Inkinobho Yokuthatha Isinyathelo",
            "html_5_s2_desc" to "Tirhisa <button> tag ku endla inkinobho.",
            "html_5_s2_hint" to "Tsala <button>Join Training Now</button>.",

            "css_6_s1_title" to "Izindima weThimba & CSS Classes",
            "css_6_s1_desc" to "Mmala wa gauta kobo-Mama, mmala wa Indigo kubafundi!",
            "css_6_s1_hint" to "Chaza dintlha ta CSS.",

            "js_7_s1_title" to "Ku bala mali ku hlayisa ntsengo",
            "js_7_s1_desc" to "Bala mali leyi hlayisiweke net.",
            "js_7_s1_hint" to "Bala inzuzo net hi tiRandi.",

            "html_8_s1_title" to "Dintlha ta ku faka Feedback",
            "html_8_s1_desc" to "Hlengeleta ti-email mikarhi hinkwayo.",
            "html_8_s1_hint" to "Faka <input type=\"email\" />.",

            "python_9_s1_title" to "Isibikezeli ya Masiku ya 90",
            "python_9_s1_desc" to "Tsala luphu ya Python ebikezelang ku kula.",
            "python_9_s1_hint" to "Tsala khoutu leyi kombisaka inzuzo.",

            "js_10_s1_title" to "Ukuzenzakalela kwe Checklist",
            "js_10_s1_desc" to "Tsala ti-SOP ta wena.",
            "js_10_s1_hint" to "Tirhisa loops ku tsala ti-SOP ta bindzu."
        ),
        "ss" to mapOf(
            "html_1_title" to "Singeno ku-HTML",
            "html_1_desc" to "Sitolo se-Spaza sa-Make e-Inthanethi",
            "css_2_title" to "Kwengeta Sitayela nge-CSS",
            "css_2_desc" to "Kwentela Kukhanya Kwekhathalogi Yakho",
            "js_3_title" to "Kubala nge-JavaScript",
            "js_3_desc" to "Kubala Sinkhwa ne-Tamatisi",
            "python_4_title" to "Python ku-Tekulima Lohlakaniphile",
            "python_4_desc" to "Kubiketela Sivuno Nemali Yentsengiso",
            "html_5_title" to "Ikhasi le-StoryBrand",
            "html_5_desc" to "Dala tifundvo letigucula batsengi",
            "css_6_title" to "Visual Branding & Tikhundla teliThimba",
            "css_6_desc" to "Faka umbala kuma-SOP nemisebenti",
            "js_7_title" to "Spaza Profit & Cash Flow",
            "js_7_desc" to "Abatoli bemali labasebaleni",
            "html_8_title" to "Ukusethwa kwefomu lemibono",
            "html_8_desc" to "Tinhlelo tekufaka iminingwane yelikhasimende",
            "python_9_title" to "Uhlelo Lwetimali lwamalanga lange-90",
            "python_9_desc" to "Tindlela tekuhlola letisekelwe etingonweni",
            "js_10_title" to "SOP Task Automation Ideshibhodi",
            "js_10_desc" to "Kukhulisa Tinhlelo teSpaza Ngokwedijithali",

            "html_1_s1_title" to "Samukelekile ku-HTML!",
            "html_1_s1_desc" to "I-HTML yakha luhlaka lwewebhusayithi. Lamuhla sitawakha sitolo saMake saseBloemfontein.",
            "html_1_s1_hint" to "Chofoza Lokulandzelako!",
            "html_1_s2_title" to "Kubhala Sihloko (<h1>)",
            "html_1_s2_desc" to "Bhala sihloko lesikhulu usebentisa i-tag ya-<h1>.",
            "html_1_s2_hint" to "Bhala <h1>Mam's Spaza Shop</h1> ku-simulator.",
            "html_1_s3_title" to "Luhlu Lwetintfo (<p> & <ul>)",
            "html_1_s3_desc" to "Dala luhlu lwetintfo letitsengiswako usebentisa <p>, <ul> kanye ne-<li>.",
            "html_1_s3_hint" to "Faka ema-tag a-<p> na-<ul>.",

            "css_2_s1_title" to "Tisekelo te-CSS",
            "css_2_s1_desc" to "I-CSS ilungisa imibala nekuma kwewebhusayithi.",
            "css_2_s1_hint" to "Fundza imitsetfo ye-CSS",
            "css_2_s2_title" to "Kushintja Imibala (color & background)",
            "css_2_s2_desc" to "Sebentisa umbala weligolide kanye ne-background lemnyama.",
            "css_2_s2_hint" to "Sebentisa background-color kanye ne-color.",

            "js_3_s1_title" to "Yini i-JavaScript?",
            "js_3_s1_desc" to "I-JS yenta iwebhusayithi isebente ngalokushesha!",
            "js_3_s1_hint" to "Kwisisa ema-variables ne-JS logic",
            "js_3_s2_title" to "Bhala Sibali Sakho",
            "js_3_s2_desc" to "Bhala umsebenti we-JS lobala inani lemali yetintfo letitsengiwe.",
            "js_3_s2_hint" to "Dala indlela yekubala ngemaRandi",

            "python_4_s1_title" to "Python ku-Tekulima",
            "python_4_s1_desc" to "I-Python ilusito kakhulu ekubaleni sivuno emasimini.",
            "python_4_s1_hint" to "Tisekelo te-Python",
            "python_4_s2_title" to "Kuhlola Kushisa Kwemhlaba (if/else)",
            "python_4_s2_desc" to "Bhala i-Python lehlola kushisa kwemhlaba.",
            "python_4_s2_hint" to "Bhala timo ku-Python.",

            "html_5_s1_title" to "Isihloko Se-Hero (<h1>)",
            "html_5_s1_desc" to "I-Hero batsengi bakho! Bhala isihloko.",
            "html_5_s1_hint" to "Bhala <h1>Grow Your Business with KodeMamas</h1> kwi-simulator.",
            "html_5_s2_title" to "Inkinobho Yokutsatsa Sinyatselo",
            "html_5_s2_desc" to "Sebenzisa i-<button> tag.",
            "html_5_s2_hint" to "Bhala <button>Join Training Now</button>.",

            "css_6_s1_title" to "Tinhla teliThimba & CSS Classes",
            "css_6_s1_desc" to "I-Gold kubo-Mama, i-Indigo kubafundi!",
            "css_6_s1_hint" to "Chaza tinhla te-CSS.",

            "js_7_s1_title" to "Amanani Lasebaleni",
            "js_7_s1_desc" to "Bala imali legciniwe net.",
            "js_7_s1_hint" to "Bala inzuzo net ngemaRandi.",

            "html_8_s1_title" to "Tinkhundla Tekufaka Impendulo",
            "html_8_s1_desc" to "Khoda intfo yekufaka i-imeyili.",
            "html_8_s1_hint" to "Faka <input type=\"email\" />.",

            "python_9_s1_title" to "Isibikezeli Semalanga lange-90",
            "python_9_s1_desc" to "Bhala iluphu ye-Python ebikezela kukhula.",
            "python_9_s1_hint" to "Bhala ikhodi lekhombisa inzuzo.",

            "js_10_s1_title" to "Ukuzenzakalela kwe Checklist",
            "js_10_s1_desc" to "Bhala ema-SOP.",
            "js_10_s1_hint" to "Sebenzisa loops letibhala ema-SOP."
        ),
        "ve" to mapOf(
            "html_1_title" to "U thoma nga HTML",
            "html_1_desc" to "Vhengele la Spaza la Make Inthanetheni",
            "css_2_title" to "U Engedza Tshitaila nga CSS",
            "css_2_desc" to "U Nakisa Khathaloko Yanu",
            "js_3_title" to "Mavhalelo nga JavaScript",
            "js_3_desc" to "Mavhalelo a Vhurotho na Mavhegele",
            "python_4_title" to "Python kha Vhulimi ha Vhutali",
            "python_4_desc" to "U Vhona Kannelo na Mitengo",
            "html_5_title" to "Ikhasi le-StoryBrand",
            "html_5_desc" to "Vhumbani zwithu zwi mamelaho vhathu",
            "css_6_title" to "Visual Branding & Dzindima dza Thimu",
            "css_6_desc" to "Mivala kha di-SOP na mishumo",
            "js_7_title" to "Spaza Profit & Cash Flow",
            "js_7_desc" to "Mavhalelo a madi o tsireledzeaho",
            "html_8_title" to "Ukusethwa kwefomu ya feedback",
            "html_8_desc" to "Zwikonisi zwa u fhela vhukoni ha vhathu",
            "python_9_title" to "Mavhalelo a maduvha a 90 a u vhona mbuelo",
            "python_9_desc" to "Tshandla tsha u hula kha loops",
            "js_10_title" to "SOP Task Automation Bodo",
            "js_10_desc" to "U hula ha masisitimi a Spaza hi ndlela ya digijithale",

            "html_1_s1_title" to "Ro vha tanganedza kha HTML!",
            "html_1_s1_desc" to "HTML i fhasa mmele wa webusaiti. Namusi ri do fhata vhengele la spaza la Make.",
            "html_1_s1_hint" to "Pfutsa Zwi Tevhelaho!",
            "html_1_s2_title" to "U Nwala Tshihloko (<h1>)",
            "html_1_s2_desc" to "Nwalani tshihloko tshihulwane nga tag ya <h1>.",
            "html_1_s2_hint" to "Nwalani <h1>Mam's Spaza Shop</h1> kha simulator.",
            "html_1_s3_title" to "Mutevhe wa Zwithu (<p> & <ul>)",
            "html_1_s3_desc" to "Itani mutevhe wa zwithu zwi rengiswaho nga <p>, <ul> na <li>.",
            "html_1_s3_hint" to "Engedzani tags dza <p> na <ul>.",

            "css_2_s1_title" to "Zwa Motheo zwa CSS",
            "css_2_s1_desc" to "CSS i vhona mivala na tshivhumbeo tsha webusaiti.",
            "css_2_s1_hint" to "Gudani milayo ya CSS",
            "css_2_s2_title" to "U Shandukisa Mivala (color & background)",
            "css_2_s2_desc" to "Shumisani muvala wa musuku na muvala wa murahu mutswu.",
            "css_2_s2_hint" to "Shumisani background-color na color.",

            "js_3_s1_title" to "JavaScript ndi Mini?",
            "js_3_s1_desc" to "JS i ita uri webusaiti i shume nga u tavhanya!",
            "js_3_s1_hint" to "Pfesani dzi-variables na JS logic",
            "js_3_s2_title" to "Nwalani Khalkhuleitha Yanu",
            "js_3_s2_desc" to "Nwalani mushumo wa JS u balaho thothala ya madi.",
            "js_3_s2_hint" to "Fhatani ndila ya u vhala nga Randa",

            "python_4_s1_title" to "Python kha Vhulimi",
            "python_4_s1_desc" to "Python i vhona kannelo na zwilimwa masimuni.",
            "python_4_s1_hint" to "Zwa motheo zwa Python",
            "python_4_s2_title" to "U Tolisa Mufhiso wa Mavu (if/else)",
            "python_4_s2_desc" to "Nwalani Python i tolisaho mufhiso wa mavu.",
            "python_4_s2_hint" to "Nwalani zwiimo kha Python.",

            "html_5_s1_title" to "Tshihloko tsha Hero (<h1>)",
            "html_5_s1_desc" to "Hero ndi vhakoki vhanu! Nwalani tshihloko.",
            "html_5_s1_hint" to "Nwalani <h1>Grow Your Business with KodeMamas</h1> kwi-simulator.",
            "html_5_s2_title" to "Inkinobho Yokuthatha Isinyathelo",
            "html_5_s2_desc" to "Shumisani <button> tag u vhumba inkinobho.",
            "html_5_s2_hint" to "Nwalani <button>Join Training Now</button>.",

            "css_6_s1_title" to "Dzindima dza Thimu & CSS Classes",
            "css_6_s1_desc" to "Gauta kha vho-Mama, Indigo kha vhagudi!",
            "css_6_s1_hint" to "Chaza dintlha dza CSS.",

            "js_7_s1_title" to "Mavhalelo o Tsireledzeaho",
            "js_7_s1_desc" to "Balani madi o vhumbiwaho net.",
            "js_7_s1_hint" to "Balani inzuzo net nga tiRandi.",

            "html_8_s1_title" to "Dzindima dza u fhela Feedback",
            "html_8_s1_desc" to "Kuvhanganyani ti-email mikarhi yothe.",
            "html_8_s1_hint" to "Fhakani <input type=\"email\" />.",

            "python_9_s1_title" to "Isibikezeli sa maduvha a 90",
            "python_9_s1_desc" to "Nwalani luphu lwa Python lu vhonisaho u hula.",
            "python_9_s1_hint" to "Nwalani khouti i sumbedzaho inzuzo.",

            "js_10_s1_title" to "Ukuzenzakalela kwe Checklist",
            "js_10_s1_desc" to "Nwalani di-SOP dza vhanu.",
            "js_10_s1_hint" to "Shumisani loops u nwala di-SOP dza bindzu."
        ),
        "nr" to mapOf(
            "html_1_title" to "Isingeniso ku-HTML",
            "html_1_desc" to "Isitolo se-Spaza saka-Mama e-Inthanethini",
            "css_2_title" to "Ukwengeza Isitayela nge-CSS",
            "css_2_desc" to "Ukwenza Ikhathalogi Yakho Ibe Ntle",
            "js_3_title" to "Ukubala nge-JavaScript",
            "js_3_desc" to "Ukubala Isikwa ne-Tamatisi",
            "python_4_title" to "Python ekuLimeni Okuhlakaniphileko",
            "python_4_desc" to "Ukubikezela Ukuvuna ne-Mitengo",
            "html_5_title" to "Ikhasi le-StoryBrand",
            "html_5_desc" to "Dala izihloko eziguqula abathengi",
            "css_6_title" to "Visual Branding & Izindima zeThimba",
            "css_6_desc" to "Faka umbala kuma-SOP nemisebenzi",
            "js_7_title" to "Spaza Profit & Cash Flow",
            "js_7_desc" to "Abalandeli bemali abavikelekile ekutholeni",
            "html_8_title" to "Ukusethwa kwefomu yemibono",
            "html_8_desc" to "Izinto zokufaka imininingwane yekhasimende",
            "python_9_title" to "Uhlelo Lwezimali lwamalanga lange-90",
            "python_9_desc" to "Izindlela zokuhlola ezisekelwe kwizihibe",
            "js_10_title" to "SOP Task Automation Ideshibhodi",
            "js_10_desc" to "Ukwandisa Izinhlelo zeSpaza Ngokwedijithali",

            "html_1_s1_title" to "Samukelekile ku-HTML!",
            "html_1_s1_desc" to "I-HTML yakha amathambo wewebhusayithi. Namhlanjesi sizokwakha isitolo sakaMama.",
            "html_1_s1_hint" to "Gandelela Okulandelako!",
            "html_1_s2_title" to "Ukutlola Isihloko (<h1>)",
            "html_1_s2_desc" to "Tlola isihloko esikhulu usebenzisa i-tag ka-<h1>.",
            "html_1_s2_hint" to "Tlola <h1>Mam's Spaza Shop</h1> ku-simulator.",
            "html_1_s3_title" to "Irhelo lePahla (<p> & <ul>)",
            "html_1_s3_desc" to "Dala irhelo lezinto ezithengiswako usebenzisa <p>, <ul> kanye ne-<li>.",
            "html_1_s3_hint" to "Faka ama-tag we-<p> nowe-<ul>.",

            "css_2_s1_title" to "Izisekelo ze-CSS",
            "css_2_s1_desc" to "I-CSS ilungisa imibala nokuma kwewebhusayithi.",
            "css_2_s1_hint" to "Funda imithetho ye-CSS",
            "css_2_s2_title" to "Ukutjhugulula Imibala (color & background)",
            "css_2_s2_desc" to "Sebenzisa umbala wegolide kanye ne-background enzima.",
            "css_2_s2_hint" to "Sebenzisa background-color kanye ne-color.",

            "js_3_s1_title" to "Yini i-JavaScript?",
            "js_3_s1_desc" to "I-JS yenza iwebhusayithi isebenze msinya!",
            "js_3_s1_hint" to "Zwisisa ama-variables ne-JS logic",
            "js_3_s2_title" to "Tlola Isibali Sakho",
            "js_3_s2_desc" to "Tlola umsebenzi we-JS obala inani lemali yezinto ezithengiweko.",
            "js_3_s2_hint" to "Yakha indlela yokubala ngamaRandi",

            "python_4_s1_title" to "Python ekuLimeni",
            "python_4_s1_desc" to "I-Python ilusito khulu ekubaleni isivuno emasimini.",
            "python_4_s1_hint" to "Izisekelo ze-Python",
            "python_4_s2_title" to "Ukuhlola Ukutjhisa Kwehlabathi (if/else)",
            "python_4_s2_desc" to "Tlola i-Python ehlola ukutjhisa kwehlabathi.",
            "python_4_s2_hint" to "Tlola iimemo ku-Python.",

            "html_5_s1_title" to "Isihloko Se-Hero (<h1>)",
            "html_5_s1_desc" to "I-Hero ngumthengi wakho! Bhala isihloko.",
            "html_5_s1_hint" to "Bhala <h1>Grow Your Business with KodeMamas</h1> kwi-simulator.",
            "html_5_s2_title" to "Inkinobho Yokuthatha Isinyathelo",
            "html_5_s2_desc" to "Sebenzisa i-<button> tag.",
            "html_5_s2_hint" to "Bhala <button>Join Training Now</button>.",

            "css_6_s1_title" to "Izindima zeThimba & CSS Classes",
            "css_6_s1_desc" to "I-Gold kobo-Mama, i-Indigo kubafundi!",
            "css_6_s1_hint" to "Chaza dintlha ze-CSS.",

            "js_7_s1_title" to "Amanani Avikelekile",
            "js_7_s1_desc" to "Bala imali egciniwe net.",
            "js_7_s1_hint" to "Bala inzuzo net ngamaRandi.",

            "html_8_s1_title" to "Izinkundla Zokufaka Impendulo",
            "html_8_s1_desc" to "Khoda into yokufaka i-imeyili.",
            "html_8_s1_hint" to "Faka <input type=\"email\" />.",

            "python_9_s1_title" to "Isibikezeli Samalanga lange-90",
            "python_9_s1_desc" to "Bhala iluphu ye-Python ebikezela ukukhula.",
            "python_9_s1_hint" to "Bhala ikhodi ekhombisa inzuzo.",

            "js_10_s1_title" to "Ukuzenzakalela kwe Checklist",
            "js_10_s1_desc" to "Bhala ama-SOP.",
            "js_10_s1_hint" to "Sebenzisa loops ezibhala ama-SOP."
        ),
        "sasl" to mapOf(
            "html_1_title" to "[Visual Sign] Intro to HTML",
            "html_1_desc" to "[Visual Sign] Spaza Shop Storefront",
            "css_2_title" to "[Visual Sign] Adding Style with CSS",
            "css_2_desc" to "[Visual Sign] Online Catalog Beautification",
            "js_3_title" to "[Visual Sign] JS Interactive Calculations",
            "js_3_desc" to "[Visual Sign] Bread & Veggie Orders",
            "python_4_title" to "[Visual Sign] Python Smart Farming",
            "python_4_desc" to "[Visual Sign] Crop Yield Predictions",
            "html_5_title" to "[Visual Sign] StoryBrand Landing Page",
            "html_5_desc" to "[Visual Sign] Create High-Converting Headers",
            "css_6_title" to "[Visual Sign] Visual Branding & Team Roles",
            "css_6_desc" to "[Visual Sign] Color-Coding SOPs & Responsibilities",
            "js_7_title" to "[Visual Sign] Spaza Profit & Cash Flow",
            "js_7_desc" to "[Visual Sign] Income Trackers",
            "html_8_title" to "[Visual Sign] Customer Feedback Form Setup",
            "html_8_desc" to "[Visual Sign] Input Elements for Leads",
            "python_9_title" to "[Visual Sign] Predictive Revenue Planner",
            "python_9_desc" to "[Visual Sign] Systems & Loops",
            "js_10_title" to "[Visual Sign] SOP Task Automation Dashboard",
            "js_10_desc" to "[Visual Sign] Scaling Spaza Digitally",

            "html_1_s1_title" to "[Visual Sign] Welcome to HTML!",
            "html_1_s1_desc" to "[Visual Sign] HTML builds web layouts. Today we build Mam's online spaza storefront.",
            "html_1_s1_hint" to "[Visual Sign] Tap Next video to continue!",
            "html_1_s2_title" to "[Visual Sign] Writing Header (<h1>)",
            "html_1_s2_desc" to "[Visual Sign] Use <h1> tag to create large shop banner: <h1>Mam's Spaza Shop</h1>.",
            "html_1_s2_hint" to "[Visual Sign] Type <h1>Mam's Spaza Shop</h1> in simulator.",
            "html_1_s3_title" to "[Visual Sign] Product Listing (<p> & <ul>)",
            "html_1_s3_desc" to "[Visual Sign] List shop products with <p>, <ul>, and <li> tags.",
            "html_1_s3_hint" to "[Visual Sign] Add <p> and <ul> tags.",

            "css_2_s1_title" to "[Visual Sign] CSS Styling Concepts",
            "css_2_s1_desc" to "[Visual Sign] CSS manages colors and visuals on your shop page.",
            "css_2_s1_hint" to "[Visual Sign] Learn CSS styling basics",
            "css_2_s2_title" to "[Visual Sign] Changing Colors",
            "css_2_s2_desc" to "[Visual Sign] Set gold text color and dark background.",
            "css_2_s2_hint" to "[Visual Sign] Use background-color and color.",

            "js_3_s1_title" to "[Visual Sign] What is JavaScript?",
            "js_3_s1_desc" to "[Visual Sign] JavaScript handles rapid live calculations in the storefront cart.",
            "js_3_s1_hint" to "[Visual Sign] Understand JS variables",
            "js_3_s2_title" to "[Visual Sign] Cart Calculator Function",
            "js_3_s2_desc" to "[Visual Sign] Write a function calculating total item costs.",
            "js_3_s2_hint" to "[Visual Sign] Build calculation formula in Rand",

            "python_4_s1_title" to "[Visual Sign] Python Smart Agriculture",
            "python_4_s1_desc" to "[Visual Sign] Python forecasts local crop yields.",
            "python_4_s1_hint" to "[Visual Sign] Python syntax fundamentals",
            "python_4_s2_title" to "[Visual Sign] Soil Temperature Check (if/else)",
            "python_4_s2_desc" to "[Visual Sign] Condition checks if soil temp > 30 degrees.",
            "python_4_s2_hint" to "[Visual Sign] Write if/else statements.",

            "html_5_s1_title" to "[Visual Sign] Hero Section Title (<h1>)",
            "html_5_s1_desc" to "[Visual Sign] Under StoryBrand, your customer is the Hero! Write a clear header <h1>Grow Your Business with KodeMamas</h1>.",
            "html_5_s1_hint" to "[Visual Sign] Type <h1>Grow Your Business with KodeMamas</h1> in the simulator.",
            "html_5_s2_title" to "[Visual Sign] Action Button",
            "html_5_s2_desc" to "[Visual Sign] Use <button> tag to make buy now button.",
            "html_5_s2_hint" to "[Visual Sign] Type <button>Join Training Now</button>.",

            "css_6_s1_title" to "[Visual Sign] Roles & CSS Classes",
            "css_6_s1_desc" to "[Visual Sign] Gold color for Mamas, Indigo for Students!",
            "css_6_s1_hint" to "[Visual Sign] Define CSS classes.",

            "js_7_s1_title" to "[Visual Sign] Cash Reserves",
            "js_7_s1_desc" to "[Visual Sign] Create algorithm adding incomes, subtracting expenses.",
            "js_7_s1_hint" to "[Visual Sign] Calculate net profit in Rands.",

            "html_8_s1_title" to "[Visual Sign] Email Feedbacks",
            "html_8_s1_desc" to "[Visual Sign] Create email input elements.",
            "html_8_s1_hint" to "[Visual Sign] Type <input type=\"email\" />.",

            "python_9_s1_title" to "[Visual Sign] 90-Day Forecaster",
            "python_9_s1_desc" to "[Visual Sign] Python loops forecasting sales growing by 15% monthly.",
            "python_9_s1_hint" to "[Visual Sign] Write loop forecasting sales.",

            "js_10_s1_title" to "[Visual Sign] Automating SOP Checklists",
            "js_10_s1_desc" to "[Visual Sign] Write JS loop listing daily checklist steps.",
            "js_10_s1_hint" to "[Visual Sign] Develop loops listing SOPs."
        )
    )
}
