package com.example.ui.theme

object Localization {

    val languages = listOf(
        com.example.data.Language.ENGLISH,
        com.example.data.Language.ZULU,
        com.example.data.Language.XHOSA,
        com.example.data.Language.AFRIKAANS,
        com.example.data.Language.SEPEDI,
        com.example.data.Language.TSWANA,
        com.example.data.Language.SOTHO,
        com.example.data.Language.TSONGA,
        com.example.data.Language.SWAZI,
        com.example.data.Language.VENDA,
        com.example.data.Language.NDEBELE,
        com.example.data.Language.SIGN_LANGUAGE
    )

    private val translations = mapOf(
        "en" to mapOf(
            "learn_coding" to "Learn coding in your language",
            "offline_online" to "Offline + Online Lessons",
            "built_for_sa" to "Built for South African Communities",
            "get_started" to "Let's Begin",
            "dashboard" to "Dashboard",
            "builds" to "Builds",
            "lessons" to "Lessons",
            "quizzes" to "Quizzes",
            "ai_assistant" to "AI Assistant",
            "community" to "Community",
            "profile" to "My Profile",
            "premium" to "Mentorship",
            "total_xp" to "Total XP",
            "streak" to "Streak Days",
            "unlocked" to "Unlocked",
            "locked" to "Locked",
            "downloaded" to "Downloaded",
            "download_class" to "Download Lesson",
            "data_saver" to "Data-Saving Mode",
            "online_status" to "Online Mode",
            "offline_status" to "Offline Mode",
            "ask_something" to "Ask me a coding question...",
            "careers" to "Careers Support",
            "one_on_one" to "1-on-1 Mentorship",
            "cv_builder" to "CV & Resume Builder",
            "interviews" to "Interview Prep",
            "networking" to "SA Tech Network",
            "daily_challenges" to "Daily Challenge",
            "submit_code" to "Run & Verify Code",
            "congrats" to "Halala! Completed!",
            "get_certificate" to "Claim Certificate",
            "founder_story" to "Meet Founder Nokwazi Nobuhle Xaba",
            "founder_desc" to "KodeMamas was founded by Nokwazi Nobuhle Xaba, a passionate tech student studying IT and Computer Science in Bloemfontein. Dedicated to digital inclusion, she created KodeMamas to empower South African mothers, girls, students, and township and rural communities to learn coding in their mother tongue both offline and online.",
            "testimonials" to "Mamas Success Stories",
            "data_saver_desc" to "Compresses images & limits server requests to save your expensive mobile data.",
            "enter_msg" to "Type a message...",
            "in_your_language" to "In Your Language 🇿🇦:"
        ),
        "zu" to mapOf( // isiZulu
            "learn_coding" to "Funda amakhodi ngolimi lwakho",
            "offline_online" to "Izifundo ngezikhathi zonke",
            "built_for_sa" to "Yakhelwe imiphakathi yaseNingizimu Afrika",
            "get_started" to "Asiqale Impilo Entsha",
            "dashboard" to "Ikhasi Lami",
            "lessons" to "Izifundo",
            "quizzes" to "Imibuzo",
            "ai_assistant" to "Umsizi we-AI",
            "community" to "I-Forum",
            "profile" to "Iphrofayili",
            "premium" to "Ubeluleki",
            "total_xp" to "XP Ephelele",
            "streak" to "Izinsuku Zolandelayo",
            "unlocked" to "Kuvuliwe",
            "locked" to "Kukhiyiwe",
            "downloaded" to "Kulandiwe",
            "download_class" to "Landa Isifundo",
            "data_saver" to "Yokonga I-Data",
            "online_status" to "Ku-Inthanethi",
            "offline_status" to "Akukho-Inthanethi",
            "ask_something" to "Ngingakusiza ngani namuhla...",
            "careers" to "Umseshi weMisebenzi",
            "one_on_one" to "1-on-1 Umqeqeshi",
            "cv_builder" to "Umakhi we-CV lula",
            "interviews" to "Ukulungiselela Interviews",
            "networking" to "Inethiwekhi ye-Tech",
            "daily_challenges" to "Inselelo Yanamuhla",
            "submit_code" to "Hlola Amakhodi Lami",
            "congrats" to "Halala! Ugcinile!",
            "get_certificate" to "Thola Isitifiketi",
            "founder_story" to "Umsunguli: Nokwazi Nobuhle Xaba",
            "founder_desc" to "I-KodeMamas yasungulwa nguNokwazi Nobuhle Xaba, umfundi wezobuchwepheshe ofundela i-IT ne-Computer Science eBloemfontein. Yakhelwe ukunika amandla omama, amantombazane, nentsha yasemalokishini nasemaphandleni ukufunda amakhodi ngolimi lwabo lwebele ngaphandle kokukhathazeka nge-data.",
            "testimonials" to "Halala naba-Mama ethu",
            "data_saver_desc" to "Kwehlisa isithombe kunciphisa ukusebenza kwe-data yeselula ematasa.",
            "enter_msg" to "Bhala umlayezo kumsizi...",
            "in_your_language" to "Ngolimi Lwakho 🇿🇦:"
        ),
        "xh" to mapOf( // isiXhosa
            "learn_coding" to "Funda ukukhowuda ngolimi lwakho",
            "offline_online" to "Izifundo ze-Offline ne-Online",
            "built_for_sa" to "Yenzelwe uluntu lwaseMzantsi Afrika",
            "get_started" to "Masisungule",
            "dashboard" to "Ideshibhodi",
            "lessons" to "Izifundo",
            "quizzes" to "Imibuzo",
            "ai_assistant" to "Incedi ye-AI",
            "community" to "Uluntu lwethu",
            "profile" to "Ikhasi Lami",
            "premium" to "Ubomi be-Tech",
            "total_xp" to "XP Iyonke",
            "streak" to "Iintsuku Zesitrayiki",
            "unlocked" to "Ivuliwe",
            "locked" to "Ivaliwe",
            "downloaded" to "Ilandiwe",
            "download_class" to "Khuphela Isifundo",
            "data_saver" to "Ukuchenga iDatha",
            "online_status" to "Une-Inthanethi",
            "offline_status" to "Ngaphandle kwe-Inthanethi",
            "ask_something" to "Buza umbuzo wokukhowuda apha...",
            "careers" to "Ingcebiso yeKhondo",
            "one_on_one" to "Ubambiswano noMcebisi",
            "cv_builder" to "Umakhi weCV emfitshane",
            "interviews" to "Imibuzo yodliwanondlebe",
            "networking" to "Uthungelwano lweTech",
            "daily_challenges" to "Inselele yeMihla",
            "submit_code" to "Run kwaye iQinisekise",
            "congrats" to "Camagu! Ugqibile!",
            "get_certificate" to "Thatha iSatifikethi",
            "founder_story" to "Umsunguli: Nokwazi Nobuhle Xaba",
            "founder_desc" to "KodeMamas yasungulwa nguNokwazi Nobuhle Xaba, umfundi we-IT kunye ne-Computer Science eBloemfontein. Idalelwe ukunika amandla omama, amantombazana, kunye noluntu lwasemaphandleni nelaselokishini ukuba bafunde ukukhowuda ngolwimi lwabo lweenkobe.",
            "testimonials" to "Amabali Abaphumeleleyo",
            "data_saver_desc" to "Oku kunciphisa amandla datha yeselula ngokukhawuleza okukhulu.",
            "enter_msg" to "Bhala umbhalo...",
            "in_your_language" to "Ngelimi Lakho 🇿🇦:"
        ),
        "af" to mapOf( // Afrikaans
            "learn_coding" to "Leer kodeer in jou eie taal",
            "offline_online" to "Alyn- en Vanlyn-lesse",
            "built_for_sa" to "Gebou vir Suid-Afrikaanse Gemeenskappe",
            "get_started" to "Laat Ons Begin",
            "dashboard" to "Paneelbord",
            "lessons" to "Lesse",
            "quizzes" to "Vasvrae",
            "ai_assistant" to "AI-Kletsbot",
            "community" to "Gemeenskap",
            "profile" to "My Profiel",
            "premium" to "Mentorskap",
            "total_xp" to "Totale XP",
            "streak" to "Onaaneenlopende Dae",
            "unlocked" to "Ontsluit",
            "locked" to "Gesluit",
            "downloaded" to "Afgestoor",
            "download_class" to "Laai Les Af",
            "data_saver" to "Databesparing",
            "online_status" to "Aanlyn-modus",
            "offline_status" to "Vanlyn-modus",
            "ask_something" to "Vra my 'n programmeringsvraag...",
            "careers" to "Inligtingsdiens",
            "one_on_one" to "1-op-1 Mentorskap",
            "cv_builder" to "CV-Bouer",
            "interviews" to "Onderhoudsvoorbereiding",
            "networking" to "SA Tegniese Netwerk",
            "daily_challenges" to "Daaglikse Uitdaging",
            "submit_code" to "Voer Kode Uit",
            "congrats" to "Geluk! Voltooid!",
            "get_certificate" to "Eis Sertifikaat",
            "founder_story" to "Stigter: Nokwazi Nobuhle Xaba",
            "founder_desc" to "KodeMamas is gestig deur Nokwazi Nobuhle Xaba, 'n tegnologiestudent wat IT en Rekenaarwetenskap in Bloemfontein studeer. Sy het KodeMamas ontwikkel om Suid-Afrikaanse ma's, meisies en township-gemeenskappe te bemagtig om in hul moedertaal aanlyn en vanlyn te leer kodeer.",
            "testimonials" to "Suksesverhale van Mamas",
            "data_saver_desc" to "Verminder prentkwaliteit en bedienerversoeke om mobiele data te bespaar.",
            "enter_msg" to "Skryf 'n boodskap...",
            "in_your_language" to "In Jou Taal 🇿🇦:"
        ),
        "nso" to mapOf( // Sepedi
            "learn_coding" to "Lera go khouta ka leleme la gago",
            "offline_online" to "Dithuto tsa Offline & Online",
            "built_for_sa" to "E agetšwe ditšhaba tša Afrika Borwa",
            "get_started" to "A re Simolole",
            "dashboard" to "Letlakala",
            "lessons" to "Dithuto",
            "quizzes" to "Dipotšišo",
            "ai_assistant" to "Mothuši wa AI",
            "community" to "Lekgotla",
            "profile" to "Porofele",
            "premium" to "Baeletši",
            "total_xp" to "XP Ka moka",
            "streak" to "Matšatši a go Latelana",
            "unlocked" to "E butšwe",
            "locked" to "E tswaletšwe",
            "downloaded" to "E laolotšwe",
            "download_class" to "Laolla Thuto",
            "data_saver" to "Sekongi se Data",
            "online_status" to "O Online",
            "offline_status" to "O Offline",
            "ask_something" to "Mpotšiše potšišo ka go khouta...",
            "careers" to "Thuto ya Mošomo",
            "one_on_one" to "1-go-1 Keletšo",
            "cv_builder" to "Moagi wa CV",
            "interviews" to "Ipeakanyetšo Potsolotšo",
            "networking" to "Neteweke ya Setsebi",
            "daily_challenges" to "Tlhahlobo ya Letšatši",
            "submit_code" to "Leka Khoutu",
            "congrats" to "Re go Lebola!",
            "get_certificate" to "Thola Setifikeiti",
            "founder_story" to "Mothomi: Nokwazi Nobuhle Xaba",
            "founder_desc" to "KodeMamas e thomilwe ke Nokwazi Nobuhle Xaba, moithuti wa IT le Saense ya Khomphutha kua Bloemfontein, go matlafatša bomme le bafsa go ithuta go khouta ka maleme a bona a Afrika Borwa.",
            "testimonials" to "Tsa Katlego ya Mamas",
            "data_saver_desc" to "E fokotša data e šomišwago mo founung ya gago.",
            "enter_msg" to "Ngwala molaetša...",
            "in_your_language" to "Ka Leleme la Gago 🇿🇦:"
        ),
        "tn" to mapOf( // Setswana
            "learn_coding" to "Ithute go khouta ka puo ya gago",
            "offline_online" to "Dithuto tsa Offline le Online",
            "built_for_sa" to "E kailwe go tshegetsa Ma-Afrika-Borwa",
            "get_started" to "A re Simolole",
            "dashboard" to "Letlhare la Taolo",
            "lessons" to "Dithuto",
            "quizzes" to "Dipotso tsa Botlhale",
            "ai_assistant" to "Mothusi wa AI",
            "community" to "Lekgotla la Rona",
            "profile" to "Porofele yame",
            "premium" to "Thuto-Mogolo",
            "total_xp" to "XP Gotlhe",
            "streak" to "Malatsi a go latelana",
            "unlocked" to "E buletswe",
            "locked" to "E tswetswe",
            "downloaded" to "E laotswe",
            "download_class" to "Laolla Thuto e",
            "data_saver" to "Mo-Sete-Datha",
            "online_status" to "O Online",
            "offline_status" to "O Offline",
            "ask_something" to "Ke go thuse ka potso efe ya khouthu...",
            "careers" to "Tshegetso ya Tsa Tiro",
            "one_on_one" to "1-on-1 Thupelo",
            "cv_builder" to "Moagi wa CV yo o bofefo",
            "interviews" to "Ipaakanyetso Dipotsolotso",
            "networking" to "SA Tech Network",
            "daily_challenges" to "Ntlha sa Letsatsi",
            "submit_code" to "Leka Khoutu e",
            "congrats" to "Pula! O feditse!",
            "get_certificate" to "Tsaya Setifikeiti",
            "founder_story" to "Mosimolodi: Nokwazi Nobuhle Xaba",
            "founder_desc" to "KodeMamas e simolotswe ke Nokwazi Nobuhle Xaba, moithuti wa IT le Computer Science ko Bloemfontein. Maikaelelo ke go tshegetsa bomme le basha go ithuta go khouta ka dipuo tsa segabone.",
            "testimonials" to "Diphuthego tsa Phuthego",
            "data_saver_desc" to "Bula datha e monyana go boloka madi a gago.",
            "enter_msg" to "Kwala molaetsa...",
            "in_your_language" to "Ka Puo ya Gago 🇿🇦:"
        ),
        "st" to mapOf( // Southern Sotho
            "learn_coding" to "Ithute ho khouta ka puo ya gago",
            "offline_online" to "Dithuto tsa Offline le Online",
            "built_for_sa" to "E agetswe baahi ba Afrika Borwa",
            "get_started" to "A re Qale",
            "dashboard" to "Laola mona",
            "lessons" to "Dithuto",
            "quizzes" to "Dipotso",
            "ai_assistant" to "Mothusi wa AI",
            "community" to "Lekgotla",
            "profile" to "Porofele ya ka",
            "premium" to "Keletso e Phahameng",
            "total_xp" to "XP kaofela",
            "streak" to "Matsatsi a latellanang",
            "unlocked" to "E butswe",
            "locked" to "E tswetswe",
            "downloaded" to "E laolotswe",
            "download_class" to "Laolla Thuto ena",
            "data_saver" to "Ho Boloka Data",
            "online_status" to "O lula Online",
            "offline_status" to "O lula Offline",
            "ask_something" to "Mpotse potso ya khoutu...",
            "careers" to "Tshehetso ya Mosebetsi",
            "one_on_one" to "Keletso ya 1-ho-1",
            "cv_builder" to "Moetsi wa CV o bofefo",
            "interviews" to "Ipeakanyetso Dipuisano",
            "networking" to "Netweke ya SA Tech",
            "daily_challenges" to "Tlhahlobo ya Letsatsi",
            "submit_code" to "Matha & Netefatsa Khoutu",
            "congrats" to "Halala! O phethile!",
            "get_certificate" to "Nka Setifikeiti",
            "founder_story" to "Mothehi: Nokwazi Nobuhle Xaba",
            "founder_desc" to "KodeMamas e qadilwe ke Nokwazi Nobuhle Xaba, moithuti wa theknoloji ya IT le Computer Science mane Bloemfontein. O e ahetse ho matlafatsa bomme, banana le batjha ba metse ya rona ho ithuta coding ka puo ya lapeng.",
            "testimonials" to "Dipalo tsa Katleho ya Mamas",
            "data_saver_desc" to "E fokotsa tshebeliso ya datha founung ya gago.",
            "enter_msg" to "Ngola molaetsa...",
            "in_your_language" to "Ka Puuo ya Gago 🇿🇦:"
        ),
        "ts" to mapOf( // Xitsonga
            "learn_coding" to "Dondzela ku khoda hi ririmi ra wena",
            "offline_online" to "Tidondzo ta Offline na Online",
            "built_for_sa" to "Yi ageteriwe vaaki va Afrika Dzonga",
            "get_started" to "A hi Sunguleni",
            "dashboard" to "Ideshibhodi",
            "lessons" to "Tidondzo",
            "quizzes" to "Swivutiso",
            "ai_assistant" to "Mupfuni wa AI",
            "community" to "Nhlangano wa hina",
            "profile" to "Phrofayili ya mina",
            "premium" to "Vuleteri",
            "total_xp" to "XP Hinkwayo",
            "streak" to "Masiku yo landelanisa",
            "unlocked" to "Yi pfuriwile",
            "locked" to "Yi khomiwile",
            "downloaded" to "Yi kokiwe",
            "download_class" to "Koka Dondzo leyi",
            "data_saver" to "Ku hlayisa Data",
            "online_status" to "U na Inthanete",
            "offline_status" to "U hava Inthanete",
            "ask_something" to "Ndzi vutise xivutiso xa khodingi...",
            "careers" to "Nseketelo wa Ntiro",
            "one_on_one" to "Vuleteri bya 1-hi-1",
            "cv_builder" to "Muaki wa CV hi ku olova",
            "interviews" to "Ku lunghiselela Inthavhiyu",
            "networking" to "Ntlhanu wa SA Tech",
            "daily_challenges" to "Ntlhontlho wa Siku",
            "submit_code" to "Tshimbila na ku tiyisekisa",
            "congrats" to "Inkomu! U hetile!",
            "get_certificate" to "Lava Setifiketi",
            "founder_story" to "Musunguri: Nokwazi Nobuhle Xaba",
            "founder_desc" to "KodeMamas yi sunguriwile hi Nokwazi Nobuhle Xaba, mudyondzi wa IT na Sayense ya Khomphyuta eBloemfontein, ku nyika matimba eka vamama na vantshwa ku dyondza ku khoda hi ririmi ra vona ra le kaya.",
            "testimonials" to "Matimu ya ku humelela ka Vamama",
            "data_saver_desc" to "Yi hunguta ku tirhisiwa ka datha eka ritingo ra wena.",
            "enter_msg" to "Tsala hungu...",
            "in_your_language" to "Hi Ririmi ra Wena 🇿🇦:"
        ),
        "ss" to mapOf( // siSwati
            "learn_coding" to "Fundza kukhoda ngelulwimi lwakho",
            "offline_online" to "Tifundvo te-Offline ne-Online",
            "built_for_sa" to "Yentelwe imiphakatsi yaseNingizimu Afrika",
            "get_started" to "Asicale",
            "dashboard" to "Ideshibhodi",
            "lessons" to "Tifundvo",
            "quizzes" to "Imibuto",
            "ai_assistant" to "Mshini we-AI wokusita",
            "community" to "Sive setfu",
            "profile" to "Iphrofayili yami",
            "premium" to "Kuceceshwa",
            "total_xp" to "XP Seisonke",
            "streak" to "Malanga lalandzelanako",
            "unlocked" to "Kuvuliwe",
            "locked" to "Kuvaliwe",
            "downloaded" to "Kulandiwe",
            "download_class" to "Landa Sifundvo simanjemanje",
            "data_saver" to "Konga Idatha",
            "online_status" to "Umanjemanje",
            "offline_status" to "Ngaphandle kwenethiwekhi",
            "ask_something" to "Mbutise umbulo wekhodingi...",
            "careers" to "Litfuba leMisebenti",
            "one_on_one" to "Kuceceshwa kwe-1-ku-1" ,
            "cv_builder" to "Umakhi we-CV lula",
            "interviews" to "Kutilungiselela Inthavyu",
            "networking" to "Inethiwekhi ye-Tech yase-SA",
            "daily_challenges" to "Inselelo yelilanga",
            "submit_code" to "Calisa futsi Ucinisekise",
            "congrats" to "Halala! Ugcinile!",
            "get_certificate" to "Tsatsa Sitifiketi",
            "founder_story" to "Msunguli: Nokwazi Nobuhle Xaba",
            "founder_desc" to "KodeMamas yacalwa nguNokwazi Nobuhle Xaba, umfundzi wetheknoloji lofundzela i-IT ne-Computer Science eBloemfontein, kute kusitakale bomake nebantfwana bafundze kukhoda ngelulwimi lwelikhaya.",
            "testimonials" to "Tindzaba tekuhumelela kwaboMama",
            "data_saver_desc" to "Kunciphisa kudliwa kwedatha kutfoni yakho.",
            "enter_msg" to "Bhala umlayeto...",
            "in_your_language" to "Ngelulwimi Lwakho 🇿🇦:"
        ),
        "ve" to mapOf( // Tshivenda
            "learn_coding" to "Gudani u khoda nga luambo lwanu",
            "offline_online" to "Ngudo dza Offline na Online",
            "built_for_sa" to "Yo fhatelwa zwitshavha zwa Afrika Tshipembe",
            "get_started" to "Kha ri thome",
            "dashboard" to "Bodo ya u laola",
            "lessons" to "Ngudo",
            "quizzes" to "Mbudziso",
            "ai_assistant" to "Muthusi wa AI",
            "community" to "Tshitshavha tshashu",
            "profile" to "Phurofayili yanga",
            "premium" to "Vhulanga-ndaela",
            "total_xp" to "XP yothe",
            "streak" to "Maduvha o teledzanaho",
            "unlocked" to "Zwo vhululwaho",
            "locked" to "Zwo khiwiwaho",
            "downloaded" to "Zwo tangohedzwaho",
            "download_class" to "Kokiwa Ngudo hei",
            "data_saver" to "U vhulunga Data",
            "online_status" to "Kha Inthanete",
            "offline_status" to "Nnda ha Inthanete",
            "ask_something" to "Nvhudziseni mbudziso ya u khoda...",
            "careers" to "Thikhinthi ya dza Mishumo",
            "one_on_one" to "Ngudo dza 1-kha-1",
            "cv_builder" to "Mu fhati wa CV nga u tavhanya",
            "interviews" to "U diladzela Ndavhedzano",
            "networking" to "Nethiweke ya dza Thekino",
            "daily_challenges" to "Mbudziso dza Duvha",
            "submit_code" to "U shuma na u khunyeledza",
            "congrats" to "Dakalo! No fhedza!",
            "get_certificate" to "Dzhiani Setifiketi",
            "founder_story" to "Musiki: Nokwazi Nobuhle Xaba",
            "founder_desc" to "KodeMamas yo thonwa nga Nokwazi Nobuhle Xaba, mutshudeni wa zwa IT na Computer Science ngei Bloemfontein, u itela u fha vhomama na vhaswa maanda a u guda u khoda nga luambo lwavho.",
            "testimonials" to "Mikovhe ya u tunda ha Vhomama",
            "data_saver_desc" to "Zwi fhungudza kushumisello kwa data kha lutingo lwanu.",
            "enter_msg" to "Nwalani mulaedza...",
            "in_your_language" to "Nga Luambo Lwanu 🇿🇦:"
        ),
        "nr" to mapOf( // isiNdebele
            "learn_coding" to "Funda amakhodi ngolimi lwakho",
            "offline_online" to "Izifundo ze-Offline ne-Online",
            "built_for_sa" to "Yenzelwe imiphakathi ye-Afrika yeSewula",
            "get_started" to "Asithome",
            "dashboard" to "Ideshibhodi",
            "lessons" to "Izifundo",
            "quizzes" to "Imibuzo",
            "ai_assistant" to "Umsizi we-AI",
            "community" to "Isitshaba sethu",
            "profile" to "Iphrofayili yami",
            "premium" to "Ubeluleki",
            "total_xp" to "XP Yoke",
            "streak" to "Amalanga alandelanako",
            "unlocked" to "Ivulwe",
            "locked" to "Ivaliwe",
            "downloaded" to "Ilandiwe",
            "download_class" to "Thwebula Isifundo lesi",
            "data_saver" to "Ubulungi be-Data",
            "online_status" to "Une-Inthanethi",
            "offline_status" to "Ngaphandle kwe-Inthanethi",
            "ask_something" to "Mbuze umbuzo wekhodingi...",
            "careers" to "Urhasulu lweMisebenzi",
            "one_on_one" to "Isiluleko se-1-ku-1",
            "cv_builder" to "Umakhi we-CV lula",
            "interviews" to "Izilungiselelo ze-Inthavyu",
            "networking" to "SA Chobho we-Tech",
            "daily_challenges" to "Inselelo yelanga",
            "submit_code" to "Gijima ubuye Uqinisekise",
            "congrats" to "Halala! Uphelisile!",
            "get_certificate" to "Thatha Isitifiketi",
            "founder_story" to "Umsunguli: Nokwazi Nobuhle Xaba",
            "founder_desc" to "KodeMamas yasungulwa nguNokwazi Nobuhle Xaba, umfundi we-IT ne-Computer Science eBloemfontein, kute asekele abomama, amantombazana nabatjha bafunde ukukhoda ngelimi lekhabo.",
            "testimonials" to "Iindaba zokuphumelela kwabomama",
            "data_saver_desc" to "Kunciphisa ukusebenza kwe-data yeselula ematasa.",
            "enter_msg" to "Bhala umlayezo...",
            "in_your_language" to "Ngolimi Lwakho 🇿🇦:"
        ),
        "sasl" to mapOf( // SASL
            "learn_coding" to "Learn coding in Sign Language (SASL)",
            "offline_online" to "Visual Offline & Online Lessons",
            "built_for_sa" to "Built for Deaf & Hearing South Africans",
            "get_started" to "Start learning (Visual)",
            "dashboard" to "Visual Board",
            "lessons" to "Visual Lessons",
            "quizzes" to "Visual Quizzes",
            "ai_assistant" to "Visual AI Chat",
            "community" to "Deaf Community Space",
            "profile" to "My Profile (Visual)",
            "premium" to "SASL Sign Mentorship",
            "total_xp" to "Visual XP Score",
            "streak" to "Daily Video Streak",
            "unlocked" to "Unlocked Video",
            "locked" to "Locked Video",
            "downloaded" to "Saved Offline",
            "download_class" to "Download Signed Video",
            "data_saver" to "Video Quality Saver",
            "online_status" to "Stream Live Video",
            "offline_status" to "Viewing Offline Videos",
            "ask_something" to "Ask code (Signs or Texts)...",
            "careers" to "Deaf Careers Hub",
            "one_on_one" to "Signed 1-on-1 Help",
            "cv_builder" to "Visual Portfolio Builder",
            "interviews" to "Deaf Interview Prep",
            "networking" to "SA Sign-Tech Network",
            "daily_challenges" to "Daily Visual Challenge",
            "submit_code" to "Submit Code Model",
            "congrats" to "Thumbs up! Hand Wave! (Completed!)",
            "get_certificate" to "Receive Signed Certificate",
            "founder_story" to "Founder: Nokwazi Nobuhle Xaba",
            "founder_desc" to "Founded by Nokwazi Nobuhle Xaba, an IT & Computer Science student in Bloemfontein. Dedicated to digital inclusion, empowering Deaf and hearing South Africans to code in their own language offline and online.",
            "testimonials" to "Deaf Success Vibrations",
            "data_saver_desc" to "Uses compressed video signages to protect your data caps.",
            "enter_msg" to "Select signs...",
            "in_your_language" to "In Sign Language (SASL) 🇿🇦:"
        )
    )

    fun translate(key: String, lang: String): String {
        val dict = translations[lang] ?: translations["en"]!!
        return dict[key] ?: translations["en"]!![key] ?: key
    }
}
