package com.example.ui.theme

object LocalizationUi {

    val uiMaps: Map<String, Map<String, String>> = mapOf(
        "en" to mapOf(
            "learn_coding" to "Learn coding in your language",
            "offline_online" to "Offline + Online Lessons",
            "built_for_sa" to "Built for South African Communities",
            "get_started" to "Let's Begin",
            "dashboard" to "Dashboard",
            "lessons" to "Lessons",
            "quizzes" to "Quizzes",
            "ai_assistant" to "AI Chatbot",
            "community" to "Community",
            "profile" to "My Profile",
            "premium" to "Mentorship",
            "total_xp" to "Total XP",
            "streak" to "Streak Days",
            "unlocked" to "Unlocked",
            "locked" to "Locked",
            "downloaded" to "Downloaded",
            "download_class" to "Download Lesson",
            "data_saver" to "Data-Saving Mode",
            "online_status" to "Online Mode",
            "offline_status" to "Offline Mode",
            "ask_something" to "Ask me a coding question...",
            "careers" to "Careers Support",
            "one_on_one" to "1-on-1 Mentorship",
            "cv_builder" to "CV & Resume Builder",
            "interviews" to "Interview Prep",
            "networking" to "SA Tech Network",
            "daily_challenges" to "Daily Challenge",
            "submit_code" to "Run & Verify Code",
            "congrats" to "Congratulations! Completed!",
            "get_certificate" to "Claim Certificate",
            "founder_story" to "Meet the Founder",
            "founder_desc" to "KodeMamas was started in Bloemfontein by Nokwazi Nobuhle Xaba, a dedicated founder and tech mentor who believes coding can break the cycle of poverty. We teach moms, girls, and communities to code to create their own digital futures.",
            "testimonials" to "Mamas Success Stories",
            "data_saver_desc" to "Compresses images & limits server requests to save your expensive mobile data.",
            "enter_msg" to "Type a message...",
            "in_your_language" to "In Your Language 🇿🇦:",
            "mobile_coding_path" to "Your Mobile Coding Path",
            "mobile_coding_desc" to "Select an interactive course below to build South African spaza applications and smart prediction crops forecasts.",
            "unlock_all" to "Unlock All",
            "previous_step" to "Previous",
            "next_step" to "Next Step",
            "launch_assessment" to "Launch Assessment ⭐",
            "verify_answer" to "Verify Answer",
            "complete_quiz" to "Complete Quiz! 🏁",
            "next_question" to "Next Question",
            "back_to_path" to "Back to Path Map",
            "compiler_success" to "COMPILER SUCCESS!",
            "compliance_alert" to "COMPLIANCE ALERT",
            "quiz_correct_msg" to "Halala! Correct Answer! 🎉",
            "quiz_wrong_msg" to "Hawu! Not quite right.",
            "multiple_choice_quiz" to "MULTIPLE CHOICE QUIZ",
            "mobile_editor_title" to "KODEMAMAS MOBILE EDITOR",
            "requirement_label" to "Requirement: ",
            "concept_label" to "CONCEPT",
            "course_label" to "Course: ",
            "step_label" to "Step",
            "quiz_label" to "Quiz",
            "tiny_mission_title" to "TINY LEARNING MISSION",
            "mission_button_work" to "Mission: Make Button Work",
            "sa_code_pipeline" to "South African Code Pipeline",
            "pipeline_desc" to "Every skill is taught inside your project. Here is the JavaScript event pipeline for your announcement board:",
            "pipeline_event" to "Event\n(click)",
            "pipeline_function" to "Function\n(postNotice)",
            "pipeline_action" to "Action\n(updateUI)",
            "need_help_hints" to "Need help? Use tiered hints before revealing explicit code:",
            "hint_1_btn" to "Hint 1",
            "hint_2_btn" to "Hint 2",
            "hint_3_btn" to "Hint 3",
            "what_build_title" to "WHAT DO YOU WANT TO BUILD?",
            "what_build_desc" to "Select an intent category or create a custom problem card",
            "problem_lab_btn" to "+ Problem Lab",
            "active_problem_builds" to "ACTIVE PROBLEM BUILDS",
            "all_builds_filter" to "🌟 All Builds",
            "capitec_title" to "Capitec Bank Details",
            "account_info" to "Account Number: 2121743886\nBank: Capitec Bank\nHolder: KodeMamas Academy",
            "payment_inst" to "Use your name as reference. Your local student profile activates instantly.",
            "save_btn" to "Save Offline Profile ⚡",
            "cancel_btn" to "Cancel"
        ),
        "zu" to mapOf(
            "learn_coding" to "Funda amakhodi ngolimi lwakho",
            "offline_online" to "Izifundo ze-Offline ne-Online",
            "built_for_sa" to "Yakhelwe Imiphakathi yaseNingizimu Afrika",
            "get_started" to "Asiqale Manje",
            "dashboard" to "Ideshibhodi",
            "lessons" to "Izifundo",
            "quizzes" to "Imibuzo",
            "ai_assistant" to "I-AI Chatbot",
            "community" to "Umphakathi",
            "profile" to "Iphrofayili Yami",
            "premium" to "Ubeluleki",
            "total_xp" to "Isamba se-XP",
            "streak" to "Izinsuku Ezilandelanayo",
            "unlocked" to "Kuvuliwe",
            "locked" to "Kuvaliwe",
            "downloaded" to "Kulandiwe",
            "download_class" to "Landa Isifundo",
            "data_saver" to "Imodi Yokonga Idatha",
            "online_status" to "Imodi Ye-inthanethi",
            "offline_status" to "Imodi Ye-Offline",
            "ask_something" to "Ngibuze umbuzo wokubhala amakhodi...",
            "careers" to "Ukusekelwa Kwemisebenzi",
            "one_on_one" to "Ubeluleki Nguwe Naye",
            "cv_builder" to "Umakhi we-CV nephothifoliyo",
            "interviews" to "Ukulungiselela Inhlolokhono",
            "networking" to "Inethiwekhi Yezobuchwepheshe e-SA",
            "daily_challenges" to "Inselelo Yosuku",
            "submit_code" to "Qalisa Uqinisekise Ikhodi",
            "congrats" to "Siyakuhalalisela! Uqedile!",
            "get_certificate" to "Thola Isitifiketi Sakho",
            "founder_story" to "Hlangana Nomsunguli",
            "founder_desc" to "I-KodeMamas yasungulwa eBloemfontein nguNokwazi Nobuhle Xaba, umsunguli ozinikele nothisha wezobuchwepheshe okholelwa ukuthi ukubhala amakhodi kunganqoba ubumpofu.",
            "testimonials" to "Izindaba Zempumelelo Zomama",
            "data_saver_desc" to "Kunciphisa izithombe kunciphise nokubiza amaseva ukuze kongiwe idatha yakho ebiza kakhulu.",
            "enter_msg" to "Bhala umyalezo...",
            "in_your_language" to "NgesiZulu 🇿🇦:",
            "mobile_coding_path" to "Indlela Yakho Yokufunda Amakhodi",
            "mobile_coding_desc" to "Khetha isifundo ngezansi ukuze wakhe izinhlelo zokusebenza ze-spaza nokubikezela kokuvuna.",
            "unlock_all" to "Vula Konke",
            "previous_step" to "Okwedlule",
            "next_step" to "Isinyathelo Esilandelayo",
            "launch_assessment" to "Qala Ukuhlola ⭐",
            "verify_answer" to "Qinisekisa Impendulo",
            "complete_quiz" to "Qeda Imibuzo! 🏁",
            "next_question" to "Umbuzo Olandelayo",
            "back_to_path" to "Buyela Ebalazweni Lezifundo",
            "compiler_success" to "IKHODI IPHELELE YAPHUMELELA!",
            "compliance_alert" to "ISIXWAYISO SEKHODI",
            "quiz_correct_msg" to "Halala! Impendulo Ilungile! 🎉",
            "quiz_wrong_msg" to "Hawu! Akukalungi kahle.",
            "multiple_choice_quiz" to "IMIBUZO ENGEZINGA ELIPHAKATHI",
            "mobile_editor_title" to "ISIHLELI SAMAKHODI SASEFONINI",
            "requirement_label" to "Okudingekayo: ",
            "concept_label" to "ISIHLOKO",
            "course_label" to "Isifundo: ",
            "step_label" to "Isinyathelo",
            "quiz_label" to "Imibuzo",
            "tiny_mission_title" to "INSELELO ENKANE YOKUFUNDA",
            "mission_button_work" to "Inhloso: Yenza Inkinobho Isebenze",
            "sa_code_pipeline" to "Indlela Yokusebenza Kwekhodi yaseNingizimu Afrika",
            "pipeline_desc" to "Lonke ikhono lifundiswa ngaphakathi kwephrojekthi yakho:",
            "pipeline_event" to "Isigameko\n(Ukuchofoza)",
            "pipeline_function" to "Umsebenzi\n(Thumela)",
            "pipeline_action" to "Isenzo\n(Shintsha UI)",
            "need_help_hints" to "Udinga usizo? Sebenzisa amacebiso:",
            "hint_1_btn" to "Icebiso 1",
            "hint_2_btn" to "Icebiso 2",
            "hint_3_btn" to "Icebiso 3",
            "what_build_title" to "YINI OFUNA UKUYAKHA?",
            "what_build_desc" to "Khetha umkhakha noma wakhe ikhadi lenkinga entsha",
            "problem_lab_btn" to "+ Problem Lab",
            "active_problem_builds" to "IZINTO EZAKHIWAYO EZISEBENZAYO",
            "all_builds_filter" to "🌟 Zonke Izakhiwo",
            "capitec_title" to "Imininingwane yeBhange laseCapitec",
            "account_info" to "Inombolo Ye-Akhawunti: 2121743886\nIbhange: iCapitec Bank\nUmnikazi: KodeMamas Academy",
            "payment_inst" to "Sebenzisa igama lakho njengereferensi.",
            "save_btn" to "Gcina Iphrofayili ⚡",
            "cancel_btn" to "Kansela"
        ),
        "xh" to mapOf(
            "learn_coding" to "Funda ukubhala iikhowudi ngolwimi lwakho",
            "offline_online" to "Izifundo ze-Offline ne-Online",
            "built_for_sa" to "Yenzelwe Uluntu lwaseMzantsi Afrika",
            "get_started" to "Masiqale Ngoku",
            "dashboard" to "Ideshibhodi",
            "lessons" to "Izifundo",
            "quizzes" to "Imibuzo",
            "ai_assistant" to "I-AI Chatbot",
            "community" to "Uluntu",
            "profile" to "Iprofayili Yam",
            "premium" to "Ukucebisa",
            "total_xp" to "I-XP Epheleleyo",
            "streak" to "Iintsuku Zilandelelana",
            "unlocked" to "Ivuliwe",
            "locked" to "Ivaliwe",
            "downloaded" to "Ikhutshelwe",
            "download_class" to "Khuphela Isifundo",
            "data_saver" to "Ukonga iDatha",
            "online_status" to "Imowudi ye-Intanethi",
            "offline_status" to "Imowudi ye-Offline",
            "ask_something" to "Ndibuze umbuzo wokukhowuda...",
            "careers" to "Inkxaso yeMisebenzi",
            "one_on_one" to "Ukucebisana Nguwe Wedwa",
            "cv_builder" to "Umakhi we-CV",
            "interviews" to "Ulungiselelo lodliwano-ndlebe",
            "networking" to "Inethiwekhi yeThekhinoloji",
            "daily_challenges" to "Umngeni Wosuku",
            "submit_code" to "Sebenzisa Uqinisekise Ikhowudi",
            "congrats" to "Sivuyisana Nawe! Ugqibile!",
            "get_certificate" to "Fumana Isitifiketi Sakho",
            "founder_story" to "Dibana noMsunguli",
            "founder_desc" to "IKodeMamas yaqalwa eBloemfontein nguNokwazi Nobuhle Xaba ukuxhobisa amabhinqa.",
            "testimonials" to "Amabali Empumelelo",
            "data_saver_desc" to "Igcina idatha yakho yeselula ngokunciphisa imifanekiso.",
            "enter_msg" to "Bhala umyalezo...",
            "in_your_language" to "NgesiXhosa 🇿🇦:",
            "mobile_coding_path" to "Indlela Yakho Yokukhowuda",
            "mobile_coding_desc" to "Khetha isifundo ngezantsi ukwakha izicelo ze-spaza.",
            "unlock_all" to "Vula Zonke",
            "previous_step" to "Edlulileyo",
            "next_step" to "Inyathelo Elilandelayo",
            "launch_assessment" to "Qala Uvavanyo ⭐",
            "verify_answer" to "Qinisekisa Impendulo",
            "complete_quiz" to "Gqiba Imibuzo! 🏁",
            "next_question" to "Umbuzo Olandelayo",
            "back_to_path" to "Buyela Kwimephu Yezifundo",
            "compiler_success" to "IKHOWUDI IPHUMELELE!",
            "compliance_alert" to "ISILUMKISO SEHOWUDI",
            "quiz_correct_msg" to "Halala! Impendulo Ichubekile! 🎉",
            "quiz_wrong_msg" to "Hayi! Khangela kwakhona.",
            "multiple_choice_quiz" to "IMIBUZO ENEZIKHETHO EZININZI",
            "mobile_editor_title" to "ISIHLELI SEHOWUDI ESISEFONINI",
            "requirement_label" to "Imfuneko: ",
            "concept_label" to "INGCINGA",
            "course_label" to "Isifundo: ",
            "step_label" to "Inyathelo",
            "quiz_label" to "Imibuzo",
            "tiny_mission_title" to "UTHUMO OLUNCINCI LOKUFUNDA",
            "mission_button_work" to "Uthumo: Yenza Iqhosha Lisebenze",
            "sa_code_pipeline" to "Indlela Yokusebenza Kwekhowudi eMzantsi Afrika",
            "pipeline_desc" to "Zonke izakhono zifundiswa ngaphakathi kweprojekthi yakho:",
            "pipeline_event" to "Isiganeko\n(Cofa)",
            "pipeline_function" to "Umsebenzi\n(Thumela)",
            "pipeline_action" to "Inyathelo\n(Hlaziya UI)",
            "need_help_hints" to "Ufuna uncedo? Sebenzisa iingcebiso:",
            "hint_1_btn" to "Icebiso 1",
            "hint_2_btn" to "Icebiso 2",
            "hint_3_btn" to "Icebiso 3",
            "what_build_title" to "UFUNA UKWAKHA NTONI?",
            "what_build_desc" to "Khetha udidi okanye wenze ikhadi lengxaki",
            "problem_lab_btn" to "+ Problem Lab",
            "active_problem_builds" to "IZAKHIWO EZIKHUTHELEYO",
            "all_builds_filter" to "🌟 Zonke Izakhiwo",
            "capitec_title" to "Iinkcukacha zeBhanki yaseCapitec",
            "account_info" to "Inombolo ye-Akhawunti: 2121743886\nIBhanki: iCapitec Bank\nUmnini: KodeMamas Academy",
            "payment_inst" to "Sebenzisa igama lakho njengesikhombisi.",
            "save_btn" to "Gcina Iprofayili ⚡",
            "cancel_btn" to "Rhoxisa"
        ),
        "af" to mapOf(
            "learn_coding" to "Leer kodeer in jou eie taal",
            "offline_online" to "Vanlyn + Aanlyn Lesse",
            "built_for_sa" to "Gebou vir Suid-Afrikaanse Gemeenskappe",
            "get_started" to "Kom Ons Begin",
            "dashboard" to "Dashboard",
            "lessons" to "Lesse",
            "quizzes" to "Vasvrae",
            "ai_assistant" to "KI Geselskapsbot",
            "community" to "Gemeenskap",
            "profile" to "My Profiel",
            "premium" to "Mentorskap",
            "total_xp" to "Totale XP",
            "streak" to "Opeenvolgende Dae",
            "unlocked" to "Oopgesluit",
            "locked" to "Gesluit",
            "downloaded" to "Afgelaai",
            "download_class" to "Laai Les Af",
            "data_saver" to "Data-Spaar Modus",
            "online_status" to "Aanlyn Modus",
            "offline_status" to "Vanlyn Modus",
            "ask_something" to "Vra my 'n kodeer-vraag...",
            "careers" to "Loopbaanondersteuning",
            "one_on_one" to "1-tot-1 Mentorskap",
            "cv_builder" to "CV & Portefeuljebouer",
            "interviews" to "Onderhoudvoorbereiding",
            "networking" to "SA Tegnologie Netwerk",
            "daily_challenges" to "Daaglikse Uitdaging",
            "submit_code" to "Hardloop & Verifieer Kode",
            "congrats" to "Veels Geluk! Voltooi!",
            "get_certificate" to "Eis Jou Sertifikaat",
            "founder_story" to "Ontmoet die Stigter",
            "founder_desc" to "KodeMamas is in Bloemfontein gestig deur Nokwazi Nobuhle Xaba om vroue te bemagtig.",
            "testimonials" to "Suksesverhale",
            "data_saver_desc" to "Bespaar duur mobiele data deur beelde saam te pers.",
            "enter_msg" to "Tik 'n boodskap...",
            "in_your_language" to "In Afrikaans 🇿🇦:",
            "mobile_coding_path" to "Jou Mobiele Kodeerpad",
            "mobile_coding_desc" to "Kies 'n interaktiewe kursus hieronder om spaza-toepassings te bou.",
            "unlock_all" to "Sluit Alles Oop",
            "previous_step" to "Vorige",
            "next_step" to "Volgende Stap",
            "launch_assessment" to "Begin Assessering ⭐",
            "verify_answer" to "Bevestig Antwoord",
            "complete_quiz" to "Voltooi Vasvra! 🏁",
            "next_question" to "Volgende Vraag",
            "back_to_path" to "Terug na Padkaart",
            "compiler_success" to "KODE SUKSESVOL VERIFIEER!",
            "compliance_alert" to "KODE WAARSKUWING",
            "quiz_correct_msg" to "Uitstekend! Korrekte Antwoord! 🎉",
            "quiz_wrong_msg" to "Oeps! Probeer weer.",
            "multiple_choice_quiz" to "MEERKEUSEVASVRA",
            "mobile_editor_title" to "KODEMAMAS MOBIELE REDIGEERDER",
            "requirement_label" to "Vereiste: ",
            "concept_label" to "KONSEK",
            "course_label" to "Kursus: ",
            "step_label" to "Stap",
            "quiz_label" to "Vasvra",
            "tiny_mission_title" to "KLEIN LEERMISSIE",
            "mission_button_work" to "Missie: Laat Knoppie Werk",
            "sa_code_pipeline" to "Suid-Afrikaanse Kode Pyplyn",
            "pipeline_desc" to "Elke vaardigheid word binne u projek geleer:",
            "pipeline_event" to "Gebeurtenis\n(Kliek)",
            "pipeline_function" to "Funksie\n(Plaas)",
            "pipeline_action" to "Aksie\n(Dateer UI op)",
            "need_help_hints" to "Hulp nodig? Gebruik wenke:",
            "hint_1_btn" to "Wenk 1",
            "hint_2_btn" to "Wenk 2",
            "hint_3_btn" to "Wenk 3",
            "what_build_title" to "WAT WIL JY BOU?",
            "what_build_desc" to "Kies 'n kategorie of skep 'n probleemkaart",
            "problem_lab_btn" to "+ Problem Lab",
            "active_problem_builds" to "AKTIEWE PROBLEEMBOUWERK",
            "all_builds_filter" to "🌟 Alle Bouwerke",
            "capitec_title" to "Capitec Bank Besonderhede",
            "account_info" to "Rekeningnommer: 2121743886\nBank: Capitec Bank\nBegunstigde: KodeMamas Academy",
            "payment_inst" to "Gebruik u naam as verwysing.",
            "save_btn" to "Stoor Profiel ⚡",
            "cancel_btn" to "Kanselleer"
        ),
        "nso" to mapOf(
            "learn_coding" to "Ithute go khouta ka leleme la gago",
            "offline_online" to "Dithuto tša Offline le Online",
            "built_for_sa" to "E agetšwe Ditšhaba tša Afrika Borwa",
            "get_started" to "A re Thome",
            "dashboard" to "Deshpoto",
            "lessons" to "Dithuto",
            "quizzes" to "Dipotšišo",
            "ai_assistant" to "AI Chatbot",
            "community" to "Setšhaba",
            "profile" to "Phorofaele ya ka",
            "premium" to "Baeletši",
            "total_xp" to "Palomoka ya XP",
            "streak" to "Matšatši a go Latelana",
            "unlocked" to "Bulegile",
            "locked" to "Tswaletšwe",
            "downloaded" to "Laolotšwe",
            "download_class" to "Laolla Thuto",
            "data_saver" to "Mokgwa wa go Boloka Data",
            "online_status" to "Mokgwa wa Inthanete",
            "offline_status" to "Mokgwa wa Offline",
            "ask_something" to "Mpotšiše potšišo ya khoutu...",
            "careers" to "Thekgo ya Mešomo",
            "one_on_one" to "Boeletši bja Motho le Motho",
            "cv_builder" to "Moagi wa CV",
            "interviews" to "Peakanyo ya Dipotšišo",
            "networking" to "Kgokagano ya Theknolotši",
            "daily_challenges" to "Tlhakatlano ya Letšatši",
            "submit_code" to "Hlahloba & Netefatša Khoutu",
            "congrats" to "Re a go lebogiša! O feditše!",
            "get_certificate" to "Tšea Setifikeiti",
            "founder_story" to "Kopana le Mosomiši",
            "founder_desc" to "KodeMamas e thomile Bloemfontein ke Nokwazi Nobuhle Xaba.",
            "testimonials" to "Dikanegelo tša Katlego",
            "data_saver_desc" to "E boloka data ya founu ka go fokotša diswantšho.",
            "enter_msg" to "Ngwala molaetša...",
            "in_your_language" to "Ka Sepedi 🇿🇦:",
            "mobile_coding_path" to "Tsela ya Gago ya go Khouta",
            "mobile_coding_desc" to "Kgetha thuto ka tlase go aga ditshepedišo tša spaza.",
            "unlock_all" to "Bula Tšohle",
            "previous_step" to "Fetilego",
            "next_step" to "Kgato e Latelago",
            "launch_assessment" to "Thoma Tekolo ⭐",
            "verify_answer" to "Netefatša Karabo",
            "complete_quiz" to "Fetša Dipotšišo! 🏁",
            "next_question" to "Potšišo e Latelago",
            "back_to_path" to "Boela Mepeng ya Dithuto",
            "compiler_success" to "KHOUTU E PHUMETŠWE GABOTSE!",
            "compliance_alert" to "TEMOŠO YA KHOUTU",
            "quiz_correct_msg" to "Re a go lebogiša! Karabo e Nepagetše! 🎉",
            "quiz_wrong_msg" to "Aowa! Leka gape.",
            "multiple_choice_quiz" to "DIPOTŠIŠO TŠA GO KGETHA",
            "mobile_editor_title" to "SERULAGANYI SA KHOUTU MO FOUNUNG",
            "requirement_label" to "Senyakego: ",
            "concept_label" to "MOGOPOLO",
            "course_label" to "Thuto: ",
            "step_label" to "Kgato",
            "quiz_label" to "Dipotšišo",
            "tiny_mission_title" to "THOMO YE NYENYANE YA GO ITHUTA",
            "mission_button_work" to "Thomo: Dira gore Konopo e Šome",
            "sa_code_pipeline" to "Tsamaiso ya Khoutu ya Afrika Borwa",
            "pipeline_desc" to "Bokgoni bjo bongwe le bjo bongwe bo rutwa ka gare ga projeke ya gago:",
            "pipeline_event" to "Tiragalo\n(Kgotla)",
            "pipeline_function" to "Modiro\n(Romela)",
            "pipeline_action" to "Kgato\n(Mpshafatša UI)",
            "need_help_hints" to "O nyaka thušo? Šomiša ditlhahlo:",
            "hint_1_btn" to "Tlhahlo 1",
            "hint_2_btn" to "Tlhahlo 2",
            "hint_3_btn" to "Tlhahlo 3",
            "what_build_title" to "O NYAKA GO AGA ENG?",
            "what_build_desc" to "Kgetha sehlopha goba o hlame karata ya mathata",
            "problem_lab_btn" to "+ Problem Lab",
            "active_problem_builds" to "DIPHROJEKE TŠEO DI ŠOMAGO",
            "all_builds_filter" to "🌟 Diprojeke Ka Moka",
            "capitec_title" to "Dintlha tša Panka ya Capitec",
            "account_info" to "Nomoro ya Akhaonto: 2121743886\nPanka: Capitec Bank\nBeng: KodeMamas Academy",
            "payment_inst" to "Šomiša leina la gago bjalo ka referense.",
            "save_btn" to "Boloka Phorofaele ⚡",
            "cancel_btn" to "Khansela"
        ),
        "tn" to mapOf(
            "learn_coding" to "Ithute go khouta ka puo ya gago",
            "offline_online" to "Dithuto tsa Offline le Online",
            "built_for_sa" to "E agetswe Ditshaba tsa Aforika Borwa",
            "get_started" to "A re Simolole",
            "dashboard" to "Desheboto",
            "lessons" to "Dithuto",
            "quizzes" to "Dipotso",
            "ai_assistant" to "AI Chatbot",
            "community" to "Setshaba",
            "profile" to "Phorofaelo ya me",
            "premium" to "Kaelo",
            "total_xp" to "Palogotlhe ya XP",
            "streak" to "Malatsi a a Latelanang",
            "unlocked" to "Buletswe",
            "locked" to "Tswetswe",
            "downloaded" to "Laolotswe",
            "download_class" to "Laolla Thuto",
            "data_saver" to "Mokgwa wa go Boloka Data",
            "online_status" to "Mokgwa wa Inthanete",
            "offline_status" to "Mokgwa wa Offline",
            "ask_something" to "Mpotse potso ya khoutu...",
            "careers" to "Tshegetso ya Ditiro",
            "one_on_one" to "Kaelo ya Motho le Motho",
            "cv_builder" to "Moagi wa CV",
            "interviews" to "Ipaakanyetso Dipotsolotso",
            "networking" to "Neteweke ya Thekenoloji",
            "daily_challenges" to "Kgwetlho ya Letsatsi",
            "submit_code" to "Tsamaisa & Tlhomamisa Khoutu",
            "congrats" to "Re a go akgola! O feditse!",
            "get_certificate" to "Tsaa Setifikeiti",
            "founder_story" to "Kopana le Mosimolodi",
            "founder_desc" to "KodeMamas e simolotswe ke Nokwazi Nobuhle Xaba go tshegetsa basadi.",
            "testimonials" to "Dipolelo tsa Katlego",
            "data_saver_desc" to "Boloka data ya gago ya founu.",
            "enter_msg" to "Kwala molaetsa...",
            "in_your_language" to "Ka Setswana 🇿🇦:",
            "mobile_coding_path" to "Tsela ya Gago ya go Khouta",
            "mobile_coding_desc" to "Tlhopha thuto go aga ditsamaiso tsa spaza.",
            "unlock_all" to "Bula Tsotlhe",
            "previous_step" to "Fetileng",
            "next_step" to "Kgato e e Latelang",
            "launch_assessment" to "Simolola Tshekatsheko ⭐",
            "verify_answer" to "Tlhomamisa Karabo",
            "complete_quiz" to "Fetsa Dipotso! 🏁",
            "next_question" to "Potso e e Latelang",
            "back_to_path" to "Boela ko Mepeng ya Dithuto",
            "compiler_success" to "KHOUTU E SIAMETSE!",
            "compliance_alert" to "TSHILETSO YA KHOUTU",
            "quiz_correct_msg" to "Go siame thata! Karabo e Nepagetse! 🎉",
            "quiz_wrong_msg" to "Nnyaa! Leka gape.",
            "multiple_choice_quiz" to "DIPOTSO TSA TLHOPHO",
            "mobile_editor_title" to "MOKWADI WA KHOUTU WA MO FOUNUNG",
            "requirement_label" to "Se se tlhokegang: ",
            "concept_label" to "KGOPOLO",
            "course_label" to "Thuto: ",
            "step_label" to "Kgato",
            "quiz_label" to "Dipotso",
            "tiny_mission_title" to "THOMO E POTLANA YA GO ITHUTA",
            "mission_button_work" to "Thomo: Dira gore Konopo e Dire",
            "sa_code_pipeline" to "Tsamaiso ya Khoutu ya Aforika Borwa",
            "pipeline_desc" to "Bokgoni jotlhe bo rutiwa mo porojekeng ya gago:",
            "pipeline_event" to "Tiragalo\n(Tobetsa)",
            "pipeline_function" to "Tiro\n(Romela)",
            "pipeline_action" to "Kgato\n(Ntshafatsa UI)",
            "need_help_hints" to "O tlhoka thuso? Dirisa dikaelo:",
            "hint_1_btn" to "Kaelo 1",
            "hint_2_btn" to "Kaelo 2",
            "hint_3_btn" to "Kaelo 3",
            "what_build_title" to "O BATLA GO AGA ENG?",
            "what_build_desc" to "Tlhopha setlhopha kgotsa o dire karata ya mathata",
            "problem_lab_btn" to "+ Problem Lab",
            "active_problem_builds" to "DIPOROJEKE TSE DI DIRANG",
            "all_builds_filter" to "🌟 Diprojeke Tsotlhe",
            "capitec_title" to "Dintlha tsa Banka ya Capitec",
            "account_info" to "Nomore ya Akhaonto: 2121743886\nBanka: Capitec Bank\nBeng: KodeMamas Academy",
            "payment_inst" to "Dirisa leina la gago.",
            "save_btn" to "Boloka Phorofaelo ⚡",
            "cancel_btn" to "Khansela"
        ),
        "st" to mapOf(
            "learn_coding" to "Ithute ho khouta ka puo ya hao",
            "offline_online" to "Dithuto tsa Offline le Online",
            "built_for_sa" to "E ahetswe Setjhaba sa Afrika Borwa",
            "get_started" to "Ha re Qale",
            "dashboard" to "Desheboto",
            "lessons" to "Dithuto",
            "quizzes" to "Dipotso",
            "ai_assistant" to "AI Chatbot",
            "community" to "Setjhaba",
            "profile" to "Phaele ya ka",
            "premium" to "Tataiso",
            "total_xp" to "Kakaretso ya XP",
            "streak" to "Matsatsi a Latelanang",
            "unlocked" to "Buletswe",
            "locked" to "Kwetsoe",
            "downloaded" to "Jarollotsoe",
            "download_class" to "Jarolla Thuto",
            "data_saver" to "Mokgwa wa ho Boloka Data",
            "online_status" to "Mokgwa wa Inthanete",
            "offline_status" to "Mokgwa wa Offline",
            "ask_something" to "Mpotse potso ya khoutu...",
            "careers" to "Tshehetso ya Mesebetsi",
            "one_on_one" to "Tataiso ya Motho le Motho",
            "cv_builder" to "Moahi wa CV",
            "interviews" to "Tokiso ya Dipuisano",
            "networking" to "Netweke ya Theknoloji",
            "daily_challenges" to "Phephetso ya Letsatsi",
            "submit_code" to "Sebedisa & Netefatsa Khoutu",
            "congrats" to "Re a o lebohisa! O qetile!",
            "get_certificate" to "Nka Setifikeiti",
            "founder_story" to "Kopana le Mothehi",
            "founder_desc" to "KodeMamas e thehilwe Bloemfontein ke Nokwazi Nobuhle Xaba.",
            "testimonials" to "Dipale tsa Katleho",
            "data_saver_desc" to "Boloka data ya hao ya thekeng.",
            "enter_msg" to "Ngola molaetsa...",
            "in_your_language" to "Ka Sesotho 🇿🇦:",
            "mobile_coding_path" to "Tsela ya Hao ya ho Khouta",
            "mobile_coding_desc" to "Kgetha thuto ka tlase ho aha mananeo a spaza.",
            "unlock_all" to "Bula Tsohle",
            "previous_step" to "Fetileng",
            "next_step" to "Mohato o Latelang",
            "launch_assessment" to "Qala Tekolo ⭐",
            "verify_answer" to "Netefatsa Karabo",
            "complete_quiz" to "Qeta Dipotso! 🏁",
            "next_question" to "Potso e Latelang",
            "back_to_path" to "Khutlela Mepeng ya Dithuto",
            "compiler_success" to "KHOUTU E ATLEHILE!",
            "compliance_alert" to "TEMOSO YA KHOUTU",
            "quiz_correct_msg" to "Re a o lebohisa! Karabo e Nepahetse! 🎉",
            "quiz_wrong_msg" to "Tjhe! Leka hape.",
            "multiple_choice_quiz" to "DIPOTSO TSA KGETHO",
            "mobile_editor_title" to "MOHLOPHISI WA KHOUTU FONONG",
            "requirement_label" to "Ho hlokahalang: ",
            "concept_label" to "MOHOPOLO",
            "course_label" to "Thuto: ",
            "step_label" to "Mohato",
            "quiz_label" to "Dipotso",
            "tiny_mission_title" to "THOMO E NYENYANE YA HO ITHUTA",
            "mission_button_work" to "Thomo: Etsa hore Konopo e Sebeletse",
            "sa_code_pipeline" to "Tsamaiso ya Khoutu ya Afrika Borwa",
            "pipeline_desc" to "Tsebo e nngwe le e nngwe e rutwa kahare ho projeke ya hao:",
            "pipeline_event" to "Ketsahalo\n(Tobetsa)",
            "pipeline_function" to "Mosebetsi\n(Romela)",
            "pipeline_action" to "Ketso\n(Ntlafatsa UI)",
            "need_help_hints" to "O hloka thuso? Sebedisa ditlhahiso:",
            "hint_1_btn" to "Tlhahiso 1",
            "hint_2_btn" to "Tlhahiso 2",
            "hint_3_btn" to "Tlhahiso 3",
            "what_build_title" to "O BATLA HO AHA ENG?",
            "what_build_desc" to "Kgetha sehlopha kapa o thehe karete ya bothata",
            "problem_lab_btn" to "+ Problem Lab",
            "active_problem_builds" to "DIPROJEKE TSE SEBETSANG",
            "all_builds_filter" to "🌟 Diprojeke Tsohle",
            "capitec_title" to "Dintlha tsa Banka ya Capitec",
            "account_info" to "Nomoro ya Akhaonto: 2121743886\nBanka: Capitec Bank\nBeng: KodeMamas Academy",
            "payment_inst" to "Sebedisa lebitso la hao.",
            "save_btn" to "Boloka Phaele ⚡",
            "cancel_btn" to "Hlakola"
        ),
        "ts" to mapOf(
            "learn_coding" to "Dondzela ku khoda hi ririmi ra wena",
            "offline_online" to "Tidyondzo ta Offline na Online",
            "built_for_sa" to "Yi akeriwe Vaaki va Afrika Dzonga",
            "get_started" to "A hi Sunguleni",
            "dashboard" to "Deshibodo",
            "lessons" to "Tidyondzo",
            "quizzes" to "Swivutiso",
            "ai_assistant" to "AI Chatbot",
            "community" to "Vaaki",
            "profile" to "Phorofayili ya Mina",
            "premium" to "Vuleteri",
            "total_xp" to "Ntsengo wa XP",
            "streak" to "Masiku yo Landelelana",
            "unlocked" to "Pfuleriwile",
            "locked" to "Pfariwile",
            "downloaded" to "Kopiyiwile",
            "download_class" to "Kopiya Dyondzo",
            "data_saver" to "Ndlela yo Hlayisa Data",
            "online_status" to "Ndlela ya Inthanete",
            "offline_status" to "Ndlela ya Offline",
            "ask_something" to "Ndzi vutise xivutiso xa khodi...",
            "careers" to "Nseketelo wa Mintirho",
            "one_on_one" to "Vuleteri bya Munhu na Munhu",
            "cv_builder" to "Muaki wa CV",
            "interviews" to "Malulamiselo ya Mbulavurisano",
            "networking" to "Netiweke ya Thekinoloji",
            "daily_challenges" to "Ntlhontlho wa Siku",
            "submit_code" to "Tirhisa & Tiyisisa Khodi",
            "congrats" to "Ha ku tsakela! U hetile!",
            "get_certificate" to "Kuma Xitifiketi",
            "founder_story" to "Hlangana na Musunguri",
            "founder_desc" to "KodeMamas yi sunguriwile hi Nokwazi Nobuhle Xaba eBloemfontein.",
            "testimonials" to "Mintsakelo ya Vamana",
            "data_saver_desc" to "Hlayisa data ya wena ya foni.",
            "enter_msg" to "Tsala rungula...",
            "in_your_language" to "Hi Xitsonga 🇿🇦:",
            "mobile_coding_path" to "Ndlela ya Wena yo Khoda",
            "mobile_coding_desc" to "Hlawula dyondzo hansi ku aka tisisteme ta spaza.",
            "unlock_all" to "Pfula Hinkwaswo",
            "previous_step" to "Ndhzhaku",
            "next_step" to "Goza leri Landelaka",
            "launch_assessment" to "Sungula Nkambisiso ⭐",
            "verify_answer" to "Tiyisisa Nhlamulo",
            "complete_quiz" to "Hetisa Swivutiso! 🏁",
            "next_question" to "Xivutiso lexi Landelaka",
            "back_to_path" to "Tlhelela eka Mepe wa Tidyondzo",
            "compiler_success" to "KHODI YI PASILE!",
            "compliance_alert" to "XITSUNDZUXO XA KHODI",
            "quiz_correct_msg" to "Hi swona! Nhlamulo i Yona! 🎉",
            "quiz_wrong_msg" to "E-e! Ringeta nakambe.",
            "multiple_choice_quiz" to "SWIVUTISO SWO HLAWULA",
            "mobile_editor_title" to "MUTSARI WA KHODI EFONINI",
            "requirement_label" to "Leswi lavekaka: ",
            "concept_label" to "MUGOPOLO",
            "course_label" to "Dyondzo: ",
            "step_label" to "Goza",
            "quiz_label" to "Swivutiso",
            "tiny_mission_title" to "NTIRHO LERINTSHONGO WO DYONDZA",
            "mission_button_work" to "Ntirho: Endla Button yi Tirha",
            "sa_code_pipeline" to "Endlelo ra Khodi ra Afrika Dzonga",
            "pipeline_desc" to "Vutshila byin'wana na byin'wana byi dyondzisiwa endzeni ka phurojeke ya wena:",
            "pipeline_event" to "Xiendlakalo\n(Khomba)",
            "pipeline_function" to "Ntirho\n(Rhumela)",
            "pipeline_action" to "Goza\n(Antswisa UI)",
            "need_help_hints" to "U lava mpfuno? Tirhisa switsundzuxo:",
            "hint_1_btn" to "Xitsundzuxo 1",
            "hint_2_btn" to "Xitsundzuxo 2",
            "hint_3_btn" to "Xitsundzuxo 3",
            "what_build_title" to "U LAVA KU AKA YINI?",
            "what_build_desc" to "Hlawula ntlawa kumbe u endla khadi ra xiphiqo",
            "problem_lab_btn" to "+ Problem Lab",
            "active_problem_builds" to "TIPHUROJEKE LETI TIRHAKO",
            "all_builds_filter" to "🌟 Tipurojeke Hinkwato",
            "capitec_title" to "Vuxokoxoko bya Banki ya Capitec",
            "account_info" to "Nomboro ya Akhawunti: 2121743886\nBanki: Capitec Bank\nN'wini: KodeMamas Academy",
            "payment_inst" to "Tirhisa vito ra wena.",
            "save_btn" to "Hlayisa Phorofayili ⚡",
            "cancel_btn" to "Khansela"
        ),
        "ss" to mapOf(
            "learn_coding" to "Fundza kukhoda ngelulwimi lwakho",
            "offline_online" to "Tifundvo te-Offline nete-Online",
            "built_for_sa" to "Yakhelwe Imiphakatsi yaseNingizimu Afrika",
            "get_started" to "Asicale Nyalo",
            "dashboard" to "Ideshibhodi",
            "lessons" to "Tifundvo",
            "quizzes" to "Imibuto",
            "ai_assistant" to "AI Chatbot",
            "community" to "Umphakatsi",
            "profile" to "Iphrofayili Yami",
            "premium" to "Beluleki",
            "total_xp" to "Inani le-XP",
            "streak" to "Emalanga Lalandzelanako",
            "unlocked" to "Kuvuliwe",
            "locked" to "Kuvaliwe",
            "downloaded" to "Kulandziwe",
            "download_class" to "Landza Sifundvo",
            "data_saver" to "Indlela Yekonga Idatha",
            "online_status" to "Indlela ye-Inthanethi",
            "offline_status" to "Indlela ye-Offline",
            "ask_something" to "Ngibute umbuto wekukhoda...",
            "careers" to "Kusekelwa Kwemisebenti",
            "one_on_one" to "Kwelulekwa Ngamunye",
            "cv_builder" to "Umakhi we-CV",
            "interviews" to "Kutilungiselela Inhlolokhono",
            "networking" to "Inethiwekhi Yebuchwepheshe",
            "daily_challenges" to "Inselelo Yosuku",
            "submit_code" to "Sebentisa & Cinisekisa Ikhodi",
            "congrats" to "Siyakuhalalisela! Ucedzile!",
            "get_certificate" to "Tfola Sitifiketi",
            "founder_story" to "Hlangana Nemsunguli",
            "founder_desc" to "KodeMamas yacalwa nguNokwazi Nobuhle Xaba eBloemfontein.",
            "testimonials" to "Tindzaba Tentsakalo",
            "data_saver_desc" to "Konga idatha yelucingo lwakho.",
            "enter_msg" to "Bhala umbiko...",
            "in_your_language" to "NgesiSwati 🇿🇦:",
            "mobile_coding_path" to "Indlela Yakho Yekukhoda",
            "mobile_coding_desc" to "Khetsa sifundvo ngaphansi kwakha tinhlelo te-spaza.",
            "unlock_all" to "Vula Konkhe",
            "previous_step" to "Lokwendlulile",
            "next_step" to "Sinyatselo Lesilandzelako",
            "launch_assessment" to "Cala Kuhlola ⭐",
            "verify_answer" to "Cinisekisa Imphendvulo",
            "complete_quiz" to "Cedza Imibuto! 🏁",
            "next_question" to "Umbuto Lolandzelako",
            "back_to_path" to "Buyela Ebalaveni Letifundvo",
            "compiler_success" to "IKHODI IPHUMELELE!",
            "compliance_alert" to "SICWAYISO SEKODI",
            "quiz_correct_msg" to "Halala! Imphendvulo Ilungile! 🎉",
            "quiz_wrong_msg" to "Cha! Yetama futsi.",
            "multiple_choice_quiz" to "IMIBUTO YEKUKHETSA",
            "mobile_editor_title" to "SIHLELI SEKODI EFONINI",
            "requirement_label" to "Lokudzingekako: ",
            "concept_label" to "SICOPHO",
            "course_label" to "Sifundvo: ",
            "step_label" to "Sinyatselo",
            "quiz_label" to "Imibuto",
            "tiny_mission_title" to "INHLOSO LENCANE YEKUFUNDZA",
            "mission_button_work" to "Inhloso: Yenta Inkinobho Isebente",
            "sa_code_pipeline" to "Indlela Yekusebenta Kwekhodi yase-SA",
            "pipeline_desc" to "Likhono linye ngalinye lifundziswa ngekhatsi kwephrojekthi yakho:",
            "pipeline_event" to "Sehlakalo\n(Chofoza)",
            "pipeline_function" to "Umsebenti\n(Tfumela)",
            "pipeline_action" to "Sento\n(Vusetela UI)",
            "need_help_hints" to "Ufuna lusito? Sebentisa ticebiso:",
            "hint_1_btn" to "Sicebiso 1",
            "hint_2_btn" to "Sicebiso 2",
            "hint_3_btn" to "Sicebiso 3",
            "what_build_title" to "UFUNA KWAKHANI?",
            "what_build_desc" to "Khetsa sigaba noma wakhe likhadi lenkinga",
            "problem_lab_btn" to "+ Problem Lab",
            "active_problem_builds" to "TINTO LETAKHIWAKO",
            "all_builds_filter" to "🌟 Tonkhe Takhiwo",
            "capitec_title" to "Imininingwane yeBhange laseCapitec",
            "account_info" to "Inombolo ye-Akhawunti: 2121743886\nIBhange: Capitec Bank\nUmnikati: KodeMamas Academy",
            "payment_inst" to "Sebentisa ligama lakho.",
            "save_btn" to "Gcina Iphrofayili ⚡",
            "cancel_btn" to "Khansela"
        ),
        "ve" to mapOf(
            "learn_coding" to "Gudani u khouda nga luambo lwanu",
            "offline_online" to "Ngudo dza Offline na Online",
            "built_for_sa" to "Zwo fhatelwa Zwitshavha zwa Afrika Tshipembe",
            "get_started" to "Kha ri Thome",
            "dashboard" to "Bodo",
            "lessons" to "Ngudo",
            "quizzes" to "Mbudziso",
            "ai_assistant" to "AI Chatbot",
            "community" to "Tshitshavha",
            "profile" to "Phorofayili Yanga",
            "premium" to "Vhulayeli",
            "total_xp" to "Thothala ya XP",
            "streak" to "Maduvha a u Tevhelelana",
            "unlocked" to "Zwo Vulea",
            "locked" to "Zwo Valiwa",
            "downloaded" to "Zwo Kopiwa",
            "download_class" to "Kopiani Ngudo",
            "data_saver" to "Mugovho wa u Vhulunga Data",
            "online_status" to "Mugovho wa Inthanethe",
            "offline_status" to "Mugovho wa Offline",
            "ask_something" to "Mbudziseni mbudziso ya u khouda...",
            "careers" to "Thikhedzo ya Mishumo",
            "one_on_one" to "Vhulayeli ha Muthihi nga Muthihi",
            "cv_builder" to "Mufhati wa CV",
            "interviews" to "Ndzudzanyo ya Mbambedzo",
            "networking" to "Netiweke ya Thekinoledzhi",
            "daily_challenges" to "Khaedu ya Duvha",
            "submit_code" to "Shumisani & Khwathisedzani Khoudi",
            "congrats" to "Ri a vha fhululedza! No fhedza!",
            "get_certificate" to "Dzhiani Tsethifikhethi",
            "founder_story" to "Tangananani na Muvhumbi",
            "founder_desc" to "KodeMamas yo thomiwa Bloemfontein nga Nokwazi Nobuhle Xaba.",
            "testimonials" to "Zwiwo zwa Mvelaphanda",
            "data_saver_desc" to "Vhulungani data yanu ya lutingo.",
            "enter_msg" to "Nwalani mulaedza...",
            "in_your_language" to "Nga Tshivenda 🇿🇦:",
            "mobile_coding_path" to "Nndila Yanu ya u Khouda",
            "mobile_coding_desc" to "Nangani ngudo u fhasa zwishumiswa zwa spaza.",
            "unlock_all" to "Vulani Zwotlhe",
            "previous_step" to "Zwo Fhiraho",
            "next_step" to "Vhudato Vhu Tevhelaho",
            "launch_assessment" to "Thoma Mulingo ⭐",
            "verify_answer" to "Khwathisedzani Phindulo",
            "complete_quiz" to "Fhedzani Mbudziso! 🏁",
            "next_question" to "Mbudziso i Tevhelaho",
            "back_to_path" to "Humelani Mepeni ya Ngudo",
            "compiler_success" to "KHOUDI YO BVELELA!",
            "compliance_alert" to "TSIWULUSO YA KHOUDI",
            "quiz_correct_msg" to "Zwo luga vhukuma! Phindulo yo luga! 🎉",
            "quiz_wrong_msg" to "Hai! Lingedzani hafhu.",
            "multiple_choice_quiz" to "MBUDZISO DZO FHANGANELANAHO",
            "mobile_editor_title" to "MUTENGISI WA KHOUDI LUNTINGONI",
            "requirement_label" to "Zwi todwaho: ",
            "concept_label" to "MIHUMBULO",
            "course_label" to "Ngudo: ",
            "step_label" to "Vhudato",
            "quiz_label" to "Mbudziso",
            "tiny_mission_title" to "MUSHUMO MUTHUKHI WA U GUDA",
            "mission_button_work" to "Mushumo: Itani uri Buthoni i Shume",
            "sa_code_pipeline" to "Ndalukanyo ya Khoudi ya Afrika Tshipembe",
            "pipeline_desc" to "Vhukoni vhunwe na vhunwe vhu gudiwa ngomu ha phurodzekiti yanu:",
            "pipeline_event" to "Tshiitea\n(Pfutsa)",
            "pipeline_function" to "Mushumo\n(Rumela)",
            "pipeline_action" to "Vhukoni\n(Vhudzadza UI)",
            "need_help_hints" to "Ni toda thikhedzo? Shumisani themendelo:",
            "hint_1_btn" to "Themendelo 1",
            "hint_2_btn" to "Themendelo 2",
            "hint_3_btn" to "Themendelo 3",
            "what_build_title" to "NI TODA U FHATA MINI?",
            "what_build_desc" to "Nangani khethekanyo kana ni vhumbe garata ya thaidzo",
            "problem_lab_btn" to "+ Problem Lab",
            "active_problem_builds" to "ZWIFHATIWA ZWI SHUMAHO",
            "all_builds_filter" to "🌟 Zwifhatiwa Zwotlhe",
            "capitec_title" to "Zwidodombedzwa zwa Banka ya Capitec",
            "account_info" to "Nomboro ya Akhaundi: 2121743886\nBanka: Capitec Bank\nMune: KodeMamas Academy",
            "payment_inst" to "Shumisani dzina lanu.",
            "save_btn" to "Vhulungani Phorofayili ⚡",
            "cancel_btn" to "Khanselani"
        ),
        "nr" to mapOf(
            "learn_coding" to "Funda ukukhoda ngelimi lakho",
            "offline_online" to "Izifundo ze-Offline ne-Online",
            "built_for_sa" to "Yakhelwe Imiphakathi yeSewula Afrika",
            "get_started" to "Akhesithome",
            "dashboard" to "Ideshibhodi",
            "lessons" to "Izifundo",
            "quizzes" to "Imibuzo",
            "ai_assistant" to "AI Chatbot",
            "community" to "Umphakathi",
            "profile" to "Iphrofayili Yami",
            "premium" to "Abaluleki",
            "total_xp" to "Inani le-XP",
            "streak" to "Amalanga Abalelwako",
            "unlocked" to "Kuvuliwe",
            "locked" to "Kuvaliwe",
            "downloaded" to "Kudawunilodiwe",
            "download_class" to "Dawuniloda Isifundo",
            "data_saver" to "Indlela Yokonga Idatha",
            "online_status" to "Indlela ye-Inthanethi",
            "offline_status" to "Indlela ye-Offline",
            "ask_something" to "Ngibuze umbuzo wokukhoda...",
            "careers" to "Isekelo yeMisebenzi",
            "one_on_one" to "Ubeluleki Womuntu Nomuntu",
            "cv_builder" to "Umakhi we-CV",
            "interviews" to "Ukulungiselela I-Interview",
            "networking" to "Inethiwekhi yeTheknoloji",
            "daily_challenges" to "Isitjhijilo seLanga",
            "submit_code" to "Sebenzisa & Qinisekisa Ikhodi",
            "congrats" to "Siyakuthokozisa! Uqedile!",
            "get_certificate" to "Thola Isitifiketi",
            "founder_story" to "Hlangana noMsunguli",
            "founder_desc" to "KodeMamas yasungulwa eBloemfontein nguNokwazi Nobuhle Xaba.",
            "testimonials" to "Iindaba Zepumelelo",
            "data_saver_desc" to "Konga idatha yefowuni yakho.",
            "enter_msg" to "Tlola umlayezo...",
            "in_your_language" to "NgesiNdebele 🇿🇦:",
            "mobile_coding_path" to "Indlela Yakho Yokukhoda",
            "mobile_coding_desc" to "Khetha isifundo ngepasi ukwakha amapulani we-spaza.",
            "unlock_all" to "Vula Koke",
            "previous_step" to "Okudlulileko",
            "next_step" to "Igadango Elilandelako",
            "launch_assessment" to "Thoma Ukuhlola ⭐",
            "verify_answer" to "Qinisekisa Iphendulo",
            "complete_quiz" to "Qeda Imibuzo! 🏁",
            "next_question" to "Umbuzo Olandelako",
            "back_to_path" to "Buyela Ebalazweni Lezifundo",
            "compiler_success" to "IKHODI IPHELELE YAPHUMELELA!",
            "compliance_alert" to "ISILUMKISO SEKHODI",
            "quiz_correct_msg" to "Halala! Iphendulo Ilungile! 🎉",
            "quiz_wrong_msg" to "Awa! Linga godu.",
            "multiple_choice_quiz" to "IMIBUZO YOKUKHETHA",
            "mobile_editor_title" to "UMHLELI WEKHODI EFOWUNINI",
            "requirement_label" to "Okudingekako: ",
            "concept_label" to "UMBONO",
            "course_label" to "Isifundo: ",
            "step_label" to "Igadango",
            "quiz_label" to "Imibuzo",
            "tiny_mission_title" to "ITHUMO ELINCANI LOKUFUNDA",
            "mission_button_work" to "Ithumo: Yenza Ikinobho Isebenze",
            "sa_code_pipeline" to "Indlela Yokusebenza Kwekhodi yeSewula Afrika",
            "pipeline_desc" to "Loke ikhono lifundiswa ngaphakathi kwephrojekthi yakho:",
            "pipeline_event" to "Isenzakalo\n(Gandelela)",
            "pipeline_function" to "Umsebenzi\n(Thumela)",
            "pipeline_action" to "Igadango\n(Buyekeza UI)",
            "need_help_hints" to "Ufuna isizo? Sebenzisa iinyeleliso:",
            "hint_1_btn" to "Iyeleliso 1",
            "hint_2_btn" to "Iyeleliso 2",
            "hint_3_btn" to "Iyeleliso 3",
            "what_build_title" to "UFUNA UKWAKHANI?",
            "what_build_desc" to "Khetha isigaba namkha wakhe ikhadi lomraro",
            "problem_lab_btn" to "+ Problem Lab",
            "active_problem_builds" to "IZAKHIWO EZISEBENZAKO",
            "all_builds_filter" to "🌟 Zoke Izakhiwo",
            "capitec_title" to "Imininingwana yeBanka yeCapitec",
            "account_info" to "Inomboro ye-Akhawunti: 2121743886\nIBanka: Capitec Bank\nUmnikazi: KodeMamas Academy",
            "payment_inst" to "Sebenzisa igama lakho.",
            "save_btn" to "Bulunga Iphrofayili ⚡",
            "cancel_btn" to "Cima"
        ),
        "sasl" to mapOf(
            "learn_coding" to "Learn coding in SASL Sign Language",
            "offline_online" to "[Sign] Offline + Online Lessons",
            "built_for_sa" to "Built for Deaf & Hearing SA Communities",
            "get_started" to "Let's Begin (Sign)",
            "dashboard" to "Visual Dashboard",
            "lessons" to "Signed Lessons",
            "quizzes" to "Visual Quizzes",
            "ai_assistant" to "Visual AI Assistant",
            "community" to "Deaf Tech Community",
            "profile" to "Visual Profile",
            "premium" to "Signed Mentorship",
            "total_xp" to "Visual Score XP",
            "streak" to "Daily Video Streak",
            "unlocked" to "Unlocked Video",
            "locked" to "Locked Video",
            "downloaded" to "Saved Offline",
            "download_class" to "Download Video",
            "data_saver" to "Video Data Saver",
            "online_status" to "Online Stream",
            "offline_status" to "Offline Storage",
            "ask_something" to "Ask code (Signs or Text)...",
            "careers" to "Deaf Careers Hub",
            "one_on_one" to "Signed 1-on-1 Help",
            "cv_builder" to "Visual Portfolio Builder",
            "interviews" to "Deaf Interview Prep",
            "networking" to "SA Sign-Tech Network",
            "daily_challenges" to "Daily Visual Challenge",
            "submit_code" to "Submit Code & Verify",
            "congrats" to "Thumbs up! Wave! (Completed!)",
            "get_certificate" to "Claim Signed Certificate",
            "founder_story" to "Who Made KodeMamas?",
            "founder_desc" to "Formed in Bloemfontein by Nokwazi Nobuhle Xaba for Deaf and hearing empowerment.",
            "testimonials" to "Deaf Success Stories",
            "data_saver_desc" to "Uses compressed video signages to protect your mobile data.",
            "enter_msg" to "Select sign/type...",
            "in_your_language" to "In Sign Language (SASL) 🇿🇦:",
            "mobile_coding_path" to "Your Visual Coding Pathway",
            "mobile_coding_desc" to "Select an interactive signed course below to build applications.",
            "unlock_all" to "Unlock All Videos",
            "previous_step" to "Previous Video",
            "next_step" to "Next Video Step",
            "launch_assessment" to "Launch Visual Quiz ⭐",
            "verify_answer" to "Verify Answer",
            "complete_quiz" to "Complete Visual Quiz! 🏁",
            "next_question" to "Next Question",
            "back_to_path" to "Back to Visual Map",
            "compiler_success" to "VISUAL COMPILER SUCCESS!",
            "compliance_alert" to "VISUAL CODE ALERT",
            "quiz_correct_msg" to "Thumbs Up! Hand Wave! (Correct!) 🎉",
            "quiz_wrong_msg" to "Not quite right. Try again.",
            "multiple_choice_quiz" to "VISUAL MULTIPLE CHOICE QUIZ",
            "mobile_editor_title" to "KODEMAMAS VISUAL EDITOR",
            "requirement_label" to "Visual Requirement: ",
            "concept_label" to "CONCEPT",
            "course_label" to "Signed Course: ",
            "step_label" to "Video Step",
            "quiz_label" to "Quiz",
            "tiny_mission_title" to "VISUAL LEARNING MISSION",
            "mission_button_work" to "Mission: Make Button Work",
            "sa_code_pipeline" to "South African Visual Code Pipeline",
            "pipeline_desc" to "Every skill is visually taught inside your project:",
            "pipeline_event" to "Event\n(Tap/Click)",
            "pipeline_function" to "Function\n(Execute)",
            "pipeline_action" to "Action\n(Update Visuals)",
            "need_help_hints" to "Need help? Use visual tiered hints:",
            "hint_1_btn" to "Visual Hint 1",
            "hint_2_btn" to "Visual Hint 2",
            "hint_3_btn" to "Visual Hint 3",
            "what_build_title" to "WHAT DO YOU WANT TO BUILD?",
            "what_build_desc" to "Select an intent category or create a custom problem card",
            "problem_lab_btn" to "+ Problem Lab",
            "active_problem_builds" to "ACTIVE VISUAL BUILDS",
            "all_builds_filter" to "🌟 All Visual Builds",
            "capitec_title" to "Capitec Bank Details",
            "account_info" to "Account Number: 2121743886\nBank: Capitec Bank\nHolder: KodeMamas Academy",
            "payment_inst" to "Use your name as reference.",
            "save_btn" to "Save Offline Profile ⚡",
            "cancel_btn" to "Cancel"
        )
    )
}
