package com.example.ui.theme

import com.example.data.Language

object Localization {

    val languages = listOf(
        Language.ENGLISH,
        Language.ZULU,
        Language.XHOSA,
        Language.AFRIKAANS,
        Language.SEPEDI,
        Language.TSWANA,
        Language.SOTHO,
        Language.TSONGA,
        Language.SWAZI,
        Language.VENDA,
        Language.NDEBELE,
        Language.SIGN_LANGUAGE
    )

    private val translations = mapOf(
        "en" to mapOf(
            "learn_coding" to "Learn coding in your language",
            "brand_tagline" to "Code in Your Language. Learn Anywhere. Build Your Future.",
            "offline_online" to "Offline + Online Lessons",
            "built_for_sa" to "Built for South African Communities",
            "get_started" to "Let's Begin",
            "dashboard" to "Home",
            "builds" to "Projects",
            "lessons" to "Learn",
            "quizzes" to "Quizzes",
            "ai_assistant" to "AI Mama",
            "community" to "Community",
            "profile" to "Profile",
            "premium" to "Mentorship",
            "total_xp" to "Total XP",
            "streak" to "Streak Days",
            "unlocked" to "Unlocked",
            "locked" to "Locked",
            "downloaded" to "Downloaded",
            "download_class" to "Download Lesson",
            "download_all" to "Download All Lessons",
            "data_saver" to "Data-Saving Mode",
            "online_status" to "Online Mode",
            "offline_status" to "Offline Mode",
            "ask_something" to "Ask me a coding question...",
            "careers" to "Careers Support",
            "one_on_one" to "1-on-1 Mentorship",
            "cv_builder" to "CV & Resume Builder",
            "interviews" to "Interview Prep",
            "networking" to "SA Tech Network",
            "daily_challenges" to "Daily Coding Challenge",
            "submit_code" to "Run & Verify Code",
            "congrats" to "Halala! Completed!",
            "get_certificate" to "Claim Certificate",
            "founder_story" to "Meet Founder Nokwazi Nobuhle Xaba",
            "founder_desc" to "KodeMamas was founded by Nokwazi Nobuhle Xaba, a passionate tech student studying IT and Computer Science in Bloemfontein. Dedicated to digital inclusion, she created KodeMamas to empower South African mothers, girls, students, and township and rural communities to learn coding in their mother tongue both offline and online.",
            "testimonials" to "Mamas Success Stories",
            "data_saver_desc" to "Compresses images & limits server requests to save your mobile data.",
            "enter_msg" to "Type a message...",
            "in_your_language" to "In Your Language 🇿🇦:",
            "hello_mama" to "Hello, Mama! 👋",
            "ready_future" to "Ready to build your future?",
            "interactive_curriculum" to "Interactive Curriculum",
            "curriculum_subtitle" to "Code in your language • Build for your community",
            "curriculum_progress" to "Curriculum Progress",
            "offline_ready" to "Offline Ready",
            "all_offline_saved" to "All lessons saved for offline loadshedding study",
            "all_categories" to "All",
            "cat_html" to "HTML",
            "cat_css" to "CSS",
            "cat_js" to "JavaScript",
            "cat_python" to "Python",
            "cat_mobile_dev" to "Mobile Dev",
            "cat_data_ai" to "Data & AI",
            "cat_design" to "Design",
            "start_lesson" to "Start Lesson",
            "continue_lesson" to "Continue",
            "lesson_completed" to "Completed",
            "step" to "Step",
            "next_step" to "Next Step",
            "prev_step" to "Previous",
            "code_editor" to "Live Code Simulator",
            "web_emulator" to "Web Emulator Preview",
            "hint" to "Hint",
            "knowledge_check" to "Knowledge Check",
            "submit_answer" to "Submit Answer",
            "next_question" to "Next Question",
            "score" to "Score",
            "quiz_passed" to "Quiz Passed! Halala!",
            "settings" to "Settings & Preferences",
            "select_home_lang" to "Select Your Language 🇿🇦",
            "cancel" to "Cancel",
            "close" to "Close",
            "save" to "Save",
            "share" to "Share",
            "sisterhood" to "Sisterhood",
            "free_access" to "100% Free Access",
            "spaza_math" to "Spaza Shop Math",
            "sisterhood_mamas" to "Built for Mamas & Daughters in SA Townships",
            "onboarding_headline" to "Empowering Black mothers and girls in South African townships through code and confidence.",
            "offline_first" to "Offline First",
            "quick_actions" to "Quick Actions",
            "explore_lessons" to "Explore Lessons",
            "search_google" to "Search Google Database",
            "gemini_connected" to "Gemini AI & Google Grounded",
            "version_label" to "Version 1.4.1"
        ),
        "zu" to mapOf( // isiZulu
            "learn_coding" to "Funda amakhodi ngolimi lwakho",
            "brand_tagline" to "Khoda ngolimi lwakho. Funda noma kuphi. Yakha ikusasa lakho.",
            "offline_online" to "Izifundo ngezikhathi zonke",
            "built_for_sa" to "Yakhelwe imiphakathi yaseNingizimu Afrika",
            "get_started" to "Asiqale Impilo Entsha",
            "dashboard" to "Ikhaya",
            "builds" to "Imiklamo",
            "lessons" to "Funda",
            "quizzes" to "Imibuzo",
            "ai_assistant" to "U-AI Mama",
            "community" to "Umphakathi",
            "profile" to "Iphrofayili",
            "premium" to "Ubeluleki",
            "total_xp" to "XP Ephelele",
            "streak" to "Izinsuku Zolandelayo",
            "unlocked" to "Kuvuliwe",
            "locked" to "Kukhiyiwe",
            "downloaded" to "Kulandiwe",
            "download_class" to "Landa Isifundo",
            "download_all" to "Landa Zonke Izifundo",
            "data_saver" to "Yokonga I-Data",
            "online_status" to "Ku-Inthanethi",
            "offline_status" to "Akukho-Inthanethi",
            "ask_something" to "Ngingakusiza ngani namuhla...",
            "careers" to "Umseshi weMisebenzi",
            "one_on_one" to "1-on-1 Umqeqeshi",
            "cv_builder" to "Umakhi we-CV lula",
            "interviews" to "Ukulungiselela Interviews",
            "networking" to "Inethiwekhi ye-Tech",
            "daily_challenges" to "Inselelo Yanamuhla",
            "submit_code" to "Hlola Amakhodi Lami",
            "congrats" to "Halala! Ugcinile!",
            "get_certificate" to "Thola Isitifiketi",
            "founder_story" to "Umsunguli: Nokwazi Nobuhle Xaba",
            "founder_desc" to "I-KodeMamas yasungulwa nguNokwazi Nobuhle Xaba, umfundi wezobuchwepheshe ofundela i-IT ne-Computer Science eBloemfontein. Yakhelwe ukunika amandla omama, amantombazane, nentsha yasemalokishini nasemaphandleni ukufunda amakhodi ngolimi lwabo lwebele ngaphandle kokukhathazeka nge-data.",
            "testimonials" to "Halala naba-Mama bethu",
            "data_saver_desc" to "Kwehlisa isithombe kunciphisa ukusebenza kwe-data yeselula ematasa.",
            "enter_msg" to "Bhala umlayezo kumsizi...",
            "in_your_language" to "Ngolimi Lwakho 🇿🇦:",
            "hello_mama" to "Sawubona, Mama! 👋",
            "ready_future" to "Ingabe usukulungele ukwakha ikusasa lakho?",
            "interactive_curriculum" to "Izifundo Zokusebenza",
            "curriculum_subtitle" to "Khoda ngolimi lwakho • Yakhela umphakathi wakho",
            "curriculum_progress" to "Inqubekelaphambili Yezifundo",
            "offline_ready" to "Ilungele Ukungabikho Kwe-Inthanethi",
            "all_offline_saved" to "Zonke izifundo zigciniwe ngaphandle kwe-data",
            "all_categories" to "Zonke",
            "cat_html" to "HTML",
            "cat_css" to "CSS",
            "cat_js" to "JavaScript",
            "cat_python" to "Python",
            "cat_mobile_dev" to "Izinhlelo Zeselula",
            "cat_data_ai" to "Idatha Ne-AI",
            "cat_design" to "Ukuklama",
            "start_lesson" to "Qala Isifundo",
            "continue_lesson" to "Qhubeka",
            "lesson_completed" to "Kuqediwe",
            "step" to "Isinyathelo",
            "next_step" to "Isinyathelo Esilandelayo",
            "prev_step" to "Emuva",
            "code_editor" to "Isilingisi Sekhodi Esibukhoma",
            "web_emulator" to "Ukubuka Kuqala Kwe-Webhusayithi",
            "hint" to "Icebiso",
            "knowledge_check" to "Ukuhlola Ulwazi",
            "submit_answer" to "Thumela Impendulo",
            "next_question" to "Umbuzo Olandelayo",
            "score" to "Amamaki",
            "quiz_passed" to "Uphumelele! Halala!",
            "settings" to "Izilungiselelo",
            "select_home_lang" to "Khetha Ulimi Lwakho Lwasekhaya 🇿🇦",
            "cancel" to "Khansela",
            "close" to "Vala",
            "save" to "Gcina",
            "share" to "Yabelana",
            "sisterhood" to "Ubuzalwane Bomama",
            "free_access" to "Kukhululekile 100%",
            "spaza_math" to "Izibalo Zesitolo Sesipaza",
            "sisterhood_mamas" to "Yenzelwe Omama Namantombazane Emalokishini",
            "onboarding_headline" to "Ukunika abomama namantombazane amnyama amandla ngokubhala amakhodi nokuzethemba.",
            "offline_first" to "Kusebenza Ngaphandle Kwe-Data",
            "quick_actions" to "Izenzo Ezisheshayo",
            "explore_lessons" to "Buka Izifundo Zonke",
            "search_google" to "Sesha Isizindalwazi SakwaGoogle",
            "gemini_connected" to "Ixhunywe ne-Gemini AI noGoogle",
            "version_label" to "Inguqulo 1.3.0"
        ),
        "xh" to mapOf( // isiXhosa
            "learn_coding" to "Funda ukukhowuda ngolimi lwakho",
            "brand_tagline" to "Khowuda ngolwimi lwakho. Funda naphi na. Yakha ikamva lakho.",
            "offline_online" to "Izifundo ze-Offline ne-Online",
            "built_for_sa" to "Yenzelwe uluntu lwaseMzantsi Afrika",
            "get_started" to "Masisungule Ngoku",
            "dashboard" to "Ikhaya",
            "builds" to "Iiprojekthi",
            "lessons" to "Funda",
            "quizzes" to "Imibuzo",
            "ai_assistant" to "U-AI Mama",
            "community" to "Uluntu",
            "profile" to "Iprofayili",
            "premium" to "Ubomi be-Tech",
            "total_xp" to "XP Iyonke",
            "streak" to "Iintsuku Zesitrayiki",
            "unlocked" to "Ivuliwe",
            "locked" to "Ivaliwe",
            "downloaded" to "Ilandiwe",
            "download_class" to "Khuphela Isifundo",
            "download_all" to "Khuphela Zonke Izifundo",
            "data_saver" to "Ukuchenga iDatha",
            "online_status" to "Une-Inthanethi",
            "offline_status" to "Ngaphandle kwe-Inthanethi",
            "ask_something" to "Buza umbuzo wokukhowuda apha...",
            "careers" to "Ingcebiso yeKhondo",
            "one_on_one" to "Ubambiswano noMcebisi",
            "cv_builder" to "Umakhi weCV emfitshane",
            "interviews" to "Imibuzo yodliwanondlebe",
            "networking" to "Uthungelwano lweTech",
            "daily_challenges" to "Inselele yeMihla",
            "submit_code" to "Baleka & Qinisekisa",
            "congrats" to "Camagu! Ugqibile!",
            "get_certificate" to "Thatha iSatifikethi",
            "founder_story" to "Umsunguli: Nokwazi Nobuhle Xaba",
            "founder_desc" to "KodeMamas yasungulwa nguNokwazi Nobuhle Xaba, umfundi we-IT kunye ne-Computer Science eBloemfontein. Idalelwe ukunika amandla omama, amantombazana, kunye noluntu lwasemaphandleni nelaselokishini ukuba bafunde ukukhowuda ngolwimi lwabo lweenkobe.",
            "testimonials" to "Amabali Abaphumeleleyo",
            "data_saver_desc" to "Oku kunciphisa amandla datha yeselula ngokukhawuleza okukhulu.",
            "enter_msg" to "Bhala umbhalo...",
            "in_your_language" to "Ngelimi Lakho 🇿🇦:",
            "hello_mama" to "Molo, Mama! 👋",
            "ready_future" to "Ukulungele ukwakha ikamva lakho elingcono?",
            "interactive_curriculum" to "Izifundo Ezinxibelelanayo",
            "curriculum_subtitle" to "Khowuda ngolwimi lwakho • Yakhela uluntu lwakho",
            "curriculum_progress" to "Inkqubela-phambili Yezifundo",
            "offline_ready" to "Ilungele ukusebenza ngaphandle kwe-intanethi",
            "all_offline_saved" to "Zonke izifundo zigciniwe ngethuba lomlilo",
            "all_categories" to "Zonke",
            "cat_html" to "HTML",
            "cat_css" to "CSS",
            "cat_js" to "JavaScript",
            "cat_python" to "Python",
            "cat_mobile_dev" to "I-Mobile Dev",
            "cat_data_ai" to "Iinkcukacha ne-AI",
            "cat_design" to "Uyilo",
            "start_lesson" to "Qalisa Isifundo",
            "continue_lesson" to "Qhubekeka",
            "lesson_completed" to "Kugqityiwe",
            "step" to "Inyathelo",
            "next_step" to "Inyathelo Elilandelayo",
            "prev_step" to "Emva",
            "code_editor" to "Isilingisi Sekhowudi",
            "web_emulator" to "Ukubonwa KweWebhsayithi",
            "hint" to "Icebiso",
            "knowledge_check" to "Uvavanyo Lolwazi",
            "submit_answer" to "Thumela Impendulo",
            "next_question" to "Umbuzo Olandelayo",
            "score" to "Amanqaku",
            "quiz_passed" to "Uphumelele! Halala!",
            "settings" to "Iisetingi",
            "select_home_lang" to "Khetha Ulwimi Lwakho Lwasekhaya 🇿🇦",
            "cancel" to "Cima",
            "close" to "Vala",
            "save" to "Gcina",
            "share" to "Yabelana",
            "sisterhood" to "Ubuzalwana Bamanina",
            "free_access" to "Simahla 100%",
            "spaza_math" to "Izibalo Zesitolo SeSpaza",
            "sisterhood_mamas" to "Yenzelwe Omama Namantombazana Aselokishini",
            "onboarding_headline" to "Ukunika amandla koomama abantsundu kunye namantombazana aselokishini.",
            "offline_first" to "Isebenza Ngaphandle kweDatha",
            "quick_actions" to "Izenzo Ezikhawulezayo",
            "explore_lessons" to "Khangela Izifundo Zonke",
            "search_google" to "Khangela Isiseko Sedatha sikaGoogle",
            "gemini_connected" to "Ixhunywe ne-Gemini AI & Google",
            "version_label" to "Inguqulelo 1.3.0"
        ),
        "af" to mapOf( // Afrikaans
            "learn_coding" to "Leer kodeer in jou eie taal",
            "brand_tagline" to "Kodeer in jou taal. Leer oral. Bou jou toekoms.",
            "offline_online" to "Aanlyn- en Vanlyn-lesse",
            "built_for_sa" to "Gebou vir Suid-Afrikaanse Gemeenskappe",
            "get_started" to "Laat Ons Begin",
            "dashboard" to "Tuis",
            "builds" to "Projekte",
            "lessons" to "Leer",
            "quizzes" to "Vasvrae",
            "ai_assistant" to "AI Mama",
            "community" to "Gemeenskap",
            "profile" to "Profiel",
            "premium" to "Mentorskap",
            "total_xp" to "Totale XP",
            "streak" to "Reeks Dae",
            "unlocked" to "Ontsluit",
            "locked" to "Gesluit",
            "downloaded" to "Afgestoor",
            "download_class" to "Laai Les Af",
            "download_all" to "Laai Alle Lesse Af",
            "data_saver" to "Databesparingsmodus",
            "online_status" to "Aanlyn-modus",
            "offline_status" to "Vanlyn-modus",
            "ask_something" to "Vra my 'n programmeringsvraag...",
            "careers" to "Loopbaandiens",
            "one_on_one" to "1-op-1 Mentorskap",
            "cv_builder" to "CV-Bouer",
            "interviews" to "Onderhoudsvoorbereiding",
            "networking" to "SA Tegniese Netwerk",
            "daily_challenges" to "Daaglikse Kodeer-Uitdaging",
            "submit_code" to "Voer Kode Uit",
            "congrats" to "Geluk! Voltooid!",
            "get_certificate" to "Kry Sertifikaat",
            "founder_story" to "Stigter: Nokwazi Nobuhle Xaba",
            "founder_desc" to "KodeMamas is gestig deur Nokwazi Nobuhle Xaba, 'n tegnologiestudent wat IT en Rekenaarwetenskap in Bloemfontein studeer om moeders en meisies in hul eie taal te bemagtig.",
            "testimonials" to "Suksesverhale van Mamas",
            "data_saver_desc" to "Verminder mobiele dataverbruik.",
            "enter_msg" to "Skryf 'n boodskap...",
            "in_your_language" to "In Jou Taal 🇿🇦:",
            "hello_mama" to "Hallo, Mama! 👋",
            "ready_future" to "Gereed om jou toekoms te bou?",
            "interactive_curriculum" to "Interaktiewe Kurrikulum",
            "curriculum_subtitle" to "Kodeer in jou taal • Bou vir jou gemeenskap",
            "curriculum_progress" to "Kurrikulum Vordering",
            "offline_ready" to "Vanlyn Gereed",
            "all_offline_saved" to "Alle lesse afgestoor vir beurtkrag",
            "all_categories" to "Alles",
            "cat_html" to "HTML",
            "cat_css" to "CSS",
            "cat_js" to "JavaScript",
            "cat_python" to "Python",
            "cat_mobile_dev" to "Mobiele Ontwikkeling",
            "cat_data_ai" to "Data & KI",
            "cat_design" to "Ontwerp",
            "start_lesson" to "Begin Les",
            "continue_lesson" to "Gaan Voort",
            "lesson_completed" to "Voltooid",
            "step" to "Stap",
            "next_step" to "Volgende Stap",
            "prev_step" to "Vorige",
            "code_editor" to "Regstreekse Kodesimulator",
            "web_emulator" to "Webvoorskou",
            "hint" to "Wenk",
            "knowledge_check" to "Kennis-toets",
            "submit_answer" to "Dien Antwoord In",
            "next_question" to "Volgende Vraag",
            "score" to "Telling",
            "quiz_passed" to "Slaagpunt Behaal! Geluk!",
            "settings" to "Instellings",
            "select_home_lang" to "Kies Jou Huistaal 🇿🇦",
            "cancel" to "Kanselleer",
            "close" to "Maak Toe",
            "save" to "Stoor",
            "share" to "Deel",
            "sisterhood" to "Susterskap",
            "free_access" to "100% Gratis Toegang",
            "spaza_math" to "Spazawinkel-Wiskunde",
            "sisterhood_mamas" to "Gebou vir Ma's en Dogters in SA Townships",
            "onboarding_headline" to "Bemagtiging van swart moeders en meisies deur kode en selfvertroue.",
            "offline_first" to "Vanlyn Eerste",
            "quick_actions" to "Vinnige Aksies",
            "explore_lessons" to "Verken Lesse",
            "search_google" to "Soek in Google-databasis",
            "gemini_connected" to "Gekoppel aan Gemini AI & Google",
            "version_label" to "Weergawe 1.3.0"
        ),
        "nso" to mapOf( // Sepedi / Northern Sotho
            "learn_coding" to "Lera go khouta ka leleme la gago",
            "brand_tagline" to "Khouta ka leleme la geno. Ithute gohle. Aga bokamoso bja gago.",
            "offline_online" to "Dithuto tsa Offline & Online",
            "built_for_sa" to "E agetšwe ditšhaba tša Afrika Borwa",
            "get_started" to "A re Simolole",
            "dashboard" to "Gae",
            "builds" to "Ditiro",
            "lessons" to "Ithute",
            "quizzes" to "Dipotšišo",
            "ai_assistant" to "AI Mama",
            "community" to "Setšhaba",
            "profile" to "Porofaele",
            "premium" to "Baeletši",
            "total_xp" to "XP Ka moka",
            "streak" to "Matšatši a go Latelana",
            "unlocked" to "E butšwe",
            "locked" to "E tswaletšwe",
            "downloaded" to "E laolotšwe",
            "download_class" to "Laolla Thuto",
            "download_all" to "Laolla Dithuto Ka Moka",
            "data_saver" to "Sekongi se Data",
            "online_status" to "O Online",
            "offline_status" to "O Offline",
            "ask_something" to "Mpotšiše potšišo ka go khouta...",
            "careers" to "Thuto ya Mošomo",
            "one_on_one" to "1-go-1 Keletšo",
            "cv_builder" to "Moagi wa CV",
            "interviews" to "Ipeakanyetšo Potsolotšo",
            "networking" to "Neteweke ya Setsebi",
            "daily_challenges" to "Tlhahlobo ya Letšatši",
            "submit_code" to "Leka Khoutu",
            "congrats" to "Re a go lebogiša!",
            "get_certificate" to "Thola Setifikeiti",
            "founder_story" to "Mothomi: Nokwazi Nobuhle Xaba",
            "founder_desc" to "KodeMamas e thomilwe ke Nokwazi Nobuhle Xaba, moithuti wa IT le Saense ya Khomphutha kua Bloemfontein go matlafatša bomme le bafsa.",
            "testimonials" to "Tsa Katlego ya Mamas",
            "data_saver_desc" to "E fokotša data e šomišwago mo founung ya gago.",
            "enter_msg" to "Ngwala molaetša...",
            "in_your_language" to "Ka Leleme la Gago 🇿🇦:",
            "hello_mama" to "Dumela, Mama! 👋",
            "ready_future" to "O itokišeditše go aga bokamoso bja gago?",
            "interactive_curriculum" to "Lenaneo la Thuto",
            "curriculum_subtitle" to "Khouta ka polelo ya gago • Agela setšhaba sa gago",
            "curriculum_progress" to "Tšwelopele ya Dithuto",
            "offline_ready" to "E loketše Offline",
            "all_offline_saved" to "Dithuto ka moka di bolokilwe offline",
            "all_categories" to "Ka Moka",
            "cat_html" to "HTML",
            "cat_css" to "CSS",
            "cat_js" to "JavaScript",
            "cat_python" to "Python",
            "cat_mobile_dev" to "Tšweletšo ya Selula",
            "cat_data_ai" to "Data le AI",
            "cat_design" to "Tlhamo",
            "start_lesson" to "Thoma Thuto",
            "continue_lesson" to "Tšwela Pele",
            "lesson_completed" to "E phedilwe",
            "step" to "Mogato",
            "next_step" to "Mogato o Latelago",
            "prev_step" to "Morago",
            "code_editor" to "Seetolodi sa Khoutu",
            "web_emulator" to "Pono ya Weposaete",
            "hint" to "Keletšo",
            "knowledge_check" to "Tlhahlobo ya Tsebo",
            "submit_answer" to "Romela Karabo",
            "next_question" to "Potšišo e Latelago",
            "score" to "Dintlha",
            "quiz_passed" to "O Phaseditše! Pula!",
            "settings" to "Dipeakanyo",
            "select_home_lang" to "Kgetha Leleme la Gae 🇿🇦",
            "cancel" to "Khansela",
            "close" to "Tswalela",
            "save" to "Boloka",
            "share" to "Abelana",
            "sisterhood" to "Bokgaetšedi bja Bomme",
            "free_access" to "100% Mahala",
            "spaza_math" to "Dipalo tša Lebenkele la Spaza",
            "sisterhood_mamas" to "E agetšwe Bomme le Bana ditaseng",
            "onboarding_headline" to "Go matlafatša bomme le basetsana ka go khouta le boitshepo.",
            "offline_first" to "Offline Pele",
            "quick_actions" to "Ditiro tša Ka Pela",
            "explore_lessons" to "Bona Dithuto",
            "search_google" to "Nyaka go Database ya Google",
            "gemini_connected" to "E kopanywe le Gemini AI & Google",
            "version_label" to "Phetolelo 1.3.0"
        ),
        "tn" to mapOf( // Setswana
            "learn_coding" to "Ithute go khouta ka puo ya gago",
            "brand_tagline" to "Khouta ka puo ya gago. Ithute gongwe le gongwe. Aga bokamoso jwa gago.",
            "offline_online" to "Dithuto tsa Offline le Online",
            "built_for_sa" to "E kailwe go tshegetsa Ma-Afrika-Borwa",
            "get_started" to "A re Simolole",
            "dashboard" to "Gae",
            "builds" to "Ditiro",
            "lessons" to "Ithute",
            "quizzes" to "Dipotso",
            "ai_assistant" to "AI Mama",
            "community" to "Setšhaba",
            "profile" to "Porofele",
            "premium" to "Thuto-Mogolo",
            "total_xp" to "XP Gotlhe",
            "streak" to "Malatsi a go latelana",
            "unlocked" to "E buletswe",
            "locked" to "E tswetswe",
            "downloaded" to "E laotswe",
            "download_class" to "Laolla Thuto e",
            "download_all" to "Laolla Dithuto Tsotlhe",
            "data_saver" to "Mo-Sete-Datha",
            "online_status" to "O Online",
            "offline_status" to "O Offline",
            "ask_something" to "Ke go thuse ka potso efe ya khouthu...",
            "careers" to "Tshegetso ya Tsa Tiro",
            "one_on_one" to "1-on-1 Thupelo",
            "cv_builder" to "Moagi wa CV yo o bofefo",
            "interviews" to "Ipaakanyetso Dipotsolotso",
            "networking" to "SA Tech Network",
            "daily_challenges" to "Ntlha sa Letsatsi",
            "submit_code" to "Leka Khoutu e",
            "congrats" to "Pula! O feditse!",
            "get_certificate" to "Tsaya Setifikeiti",
            "founder_story" to "Mosimolodi: Nokwazi Nobuhle Xaba",
            "founder_desc" to "KodeMamas e simolotswe ke Nokwazi Nobuhle Xaba, moithuti wa IT le Computer Science ko Bloemfontein go tshegetsa bomme le basha.",
            "testimonials" to "Diphuthego tsa Katlego",
            "data_saver_desc" to "Bula datha e monyana go boloka madi.",
            "enter_msg" to "Kwala molaetsa...",
            "in_your_language" to "Ka Puo ya Gago 🇿🇦:",
            "hello_mama" to "Dumela, Mma! 👋",
            "ready_future" to "A o ipaakanyeditse go aga bokamoso jwa gago?",
            "interactive_curriculum" to "Lenaneo la Thuto",
            "curriculum_subtitle" to "Khouta ka puo ya gago • Agela setšhaba sa gago",
            "curriculum_progress" to "Tswelelopele ya Dithuto",
            "offline_ready" to "E siametse Offline",
            "all_offline_saved" to "Dithuto tsotlhe di bolokilwe offline",
            "all_categories" to "Tsotlhe",
            "cat_html" to "HTML",
            "cat_css" to "CSS",
            "cat_js" to "JavaScript",
            "cat_python" to "Python",
            "cat_mobile_dev" to "Tlhabololo ya Selefono",
            "cat_data_ai" to "Data le AI",
            "cat_design" to "Moralo",
            "start_lesson" to "Simolola Thuto",
            "continue_lesson" to "Tswelela",
            "lesson_completed" to "E weditswe",
            "step" to "Kgato",
            "next_step" to "Kgato e e Latelang",
            "prev_step" to "Morago",
            "code_editor" to "Sebopegi sa Khoutu",
            "web_emulator" to "Tebego ya Webosaete",
            "hint" to "Kgakololo",
            "knowledge_check" to "Tlhahlobo ya Kitso",
            "submit_answer" to "Romela Karabo",
            "next_question" to "Potso e e Latelang",
            "score" to "Dintlha",
            "quiz_passed" to "O Pasitse! Pula!",
            "settings" to "Dithulaganyo",
            "select_home_lang" to "Tlhopha Puo ya Gae 🇿🇦",
            "cancel" to "Khansela",
            "close" to "Tswala",
            "save" to "Boloka",
            "share" to "Abelana",
            "sisterhood" to "Bokaulengwe jwa Bomme",
            "free_access" to "100% Mahala",
            "spaza_math" to "Dipalo tsa Bentlele ya Spaza",
            "sisterhood_mamas" to "E agetswe Bomme le Bana ba ditoropo",
            "onboarding_headline" to "Go maatlafatsa bomme le basetsana ka khoutu le go itshepa.",
            "offline_first" to "Offline Pele",
            "quick_actions" to "Ditiro tsa Bofefo",
            "explore_lessons" to "Bona Dithuto",
            "search_google" to "Batla mo Database ya Google",
            "gemini_connected" to "E gokagantswe le Gemini AI & Google",
            "version_label" to "Phetolo 1.3.0"
        ),
        "st" to mapOf( // Sesotho / Southern Sotho
            "learn_coding" to "Ithute ho khouta ka puo ya hao",
            "brand_tagline" to "Khouta ka puo ya hao. Ithute hohle. Aha bokamoso ba hao.",
            "offline_online" to "Dithuto tsa Offline le Online",
            "built_for_sa" to "E agetswe baahi ba Afrika Borwa",
            "get_started" to "A re Qale",
            "dashboard" to "Hae",
            "builds" to "Diprojeke",
            "lessons" to "Ithute",
            "quizzes" to "Dipotso",
            "ai_assistant" to "AI Mama",
            "community" to "Setjhaba",
            "profile" to "Porofaele",
            "premium" to "Keletso e Phahameng",
            "total_xp" to "XP kaofela",
            "streak" to "Matsatsi a latellanang",
            "unlocked" to "E butswe",
            "locked" to "E tswetswe",
            "downloaded" to "E laolotswe",
            "download_class" to "Laolla Thuto ena",
            "download_all" to "Laolla Dithuto Tsohle",
            "data_saver" to "Ho Boloka Data",
            "online_status" to "O lula Online",
            "offline_status" to "O lula Offline",
            "ask_something" to "Mpotse potso ya khoutu...",
            "careers" to "Tshehetso ya Mosebetsi",
            "one_on_one" to "Keletso ya 1-ho-1",
            "cv_builder" to "Moetsi wa CV o bofefo",
            "interviews" to "Ipeakanyetso Dipuisano",
            "networking" to "Netweke ya SA Tech",
            "daily_challenges" to "Tlhahlobo ya Letsatsi",
            "submit_code" to "Matha & Netefatsa Khoutu",
            "congrats" to "Halala! O phethile!",
            "get_certificate" to "Nka Setifikeiti",
            "founder_story" to "Mothehi: Nokwazi Nobuhle Xaba",
            "founder_desc" to "KodeMamas e qadilwe ke Nokwazi Nobuhle Xaba, moithuti wa IT le Computer Science mane Bloemfontein ho matlafatsa bomme le bana.",
            "testimonials" to "Dipalo tsa Katleho",
            "data_saver_desc" to "E fokotsa tshebeliso ya datha founung ya hao.",
            "enter_msg" to "Ngola molaetsa...",
            "in_your_language" to "Ka Puo ya Hao 🇿🇦:",
            "hello_mama" to "Dumela, Mme! 👋",
            "ready_future" to "Na o itokiseditse ho aha bokamoso ba hao?",
            "interactive_curriculum" to "Thuto e Matlafalitsweng",
            "curriculum_subtitle" to "Khouta ka puo ya lapeng • Ahela setjhaba sa hao",
            "curriculum_progress" to "Tswelopele ya Dithuto",
            "offline_ready" to "E loketse Offline",
            "all_offline_saved" to "Dithuto tsohle di bolokilwe ntle le data",
            "all_categories" to "Tsohle",
            "cat_html" to "HTML",
            "cat_css" to "CSS",
            "cat_js" to "JavaScript",
            "cat_python" to "Python",
            "cat_mobile_dev" to "Ntshetsopele ya Fono",
            "cat_data_ai" to "Data le AI",
            "cat_design" to "Moralo",
            "start_lesson" to "Qala Thuto",
            "continue_lesson" to "Tswela Pele",
            "lesson_completed" to "E qetilwe",
            "step" to "Mohato",
            "next_step" to "Mohato o Latelang",
            "prev_step" to "Morao",
            "code_editor" to "Sesebediswa sa Khoutu",
            "web_emulator" to "Pono ya Websaete",
            "hint" to "Keletso",
            "knowledge_check" to "Tlhahlobo ya Tsebo",
            "submit_answer" to "Romela Karabo",
            "next_question" to "Potso e Latelang",
            "score" to "Dintlha",
            "quiz_passed" to "O Pasitse! Halala!",
            "settings" to "Dipehelo",
            "select_home_lang" to "Kgetha Puo ya Lapeng 🇿🇦",
            "cancel" to "Hlakola",
            "close" to "Kwala",
            "save" to "Boloka",
            "share" to "Arolelana",
            "sisterhood" to "Bongwaneso ba Bomme",
            "free_access" to "100% Mahala",
            "spaza_math" to "Dipalo tsa Lebenkele la Spaza",
            "sisterhood_mamas" to "E ahetswe Bomme le Baradi ditoropong",
            "onboarding_headline" to "Ho matlafatsa bomme ba batsho le banana ka khoutu le tshepo.",
            "offline_first" to "Offline Pele",
            "quick_actions" to "Dikgato tse Potlakileng",
            "explore_lessons" to "Lekola Dithuto Tsohle",
            "search_google" to "Batla ho Database ya Google",
            "gemini_connected" to "E hokahantswe le Gemini AI & Google",
            "version_label" to "Phetolelo 1.3.0"
        ),
        "ts" to mapOf( // Xitsonga
            "learn_coding" to "Dondzela ku khoda hi ririmi ra wena",
            "brand_tagline" to "Khoda hi ririmi ra wena. Dondza hinkwako. Aka vumundzuku bya wena.",
            "offline_online" to "Tidondzo ta Offline na Online",
            "built_for_sa" to "Yi ageteriwe vaaki va Afrika Dzonga",
            "get_started" to "A hi Sunguleni",
            "dashboard" to "Kaya",
            "builds" to "Tiprojeke",
            "lessons" to "Dondza",
            "quizzes" to "Swivutiso",
            "ai_assistant" to "AI Mama",
            "community" to "Vaaki",
            "profile" to "Phrofayili",
            "premium" to "Vuleteri",
            "total_xp" to "XP Hinkwayo",
            "streak" to "Masiku yo landelanisa",
            "unlocked" to "Yi pfuriwile",
            "locked" to "Yi khomiwile",
            "downloaded" to "Yi kokiwe",
            "download_class" to "Koka Dondzo leyi",
            "download_all" to "Koka Tidondzo Hinkwato",
            "data_saver" to "Ku hlayisa Data",
            "online_status" to "U na Inthanete",
            "offline_status" to "U hava Inthanete",
            "ask_something" to "Ndzi vutise xivutiso xa khodingi...",
            "careers" to "Nseketelo wa Ntiro",
            "one_on_one" to "Vuleteri bya 1-hi-1",
            "cv_builder" to "Muaki wa CV hi ku olova",
            "interviews" to "Ku lunghiselela Inthavhiyu",
            "networking" to "Ntlhanu wa SA Tech",
            "daily_challenges" to "Ntlhontlho wa Siku",
            "submit_code" to "Tshimbila & Tiyisekisa",
            "congrats" to "Inkomu! U hetile!",
            "get_certificate" to "Lava Setifiketi",
            "founder_story" to "Musunguri: Nokwazi Nobuhle Xaba",
            "founder_desc" to "KodeMamas yi sunguriwile hi Nokwazi Nobuhle Xaba, mudyondzi wa IT na Sayense ya Khomphyuta eBloemfontein ku nyika vamama matimba.",
            "testimonials" to "Matimu ya ku Humelela",
            "data_saver_desc" to "Yi hunguta ku tirhisiwa ka datha eka foni ya wena.",
            "enter_msg" to "Tsala hungu...",
            "in_your_language" to "Hi Ririmi ra Wena 🇿🇦:",
            "hello_mama" to "Avuxeni, Manana! 👋",
            "ready_future" to "Xana u lulamerile ku aka vumundzuku bya wena?",
            "interactive_curriculum" to "Xiyimiso xa Tidondzo",
            "curriculum_subtitle" to "Khoda hi ririmi ra wena • Akela vaaki va wena",
            "curriculum_progress" to "Nhluvuko wa Tidondzo",
            "offline_ready" to "Yi lulamile ku tirha Offline",
            "all_offline_saved" to "Tidondzo hinkwato ti hlayisiwile eka offline",
            "all_categories" to "Hinkwaswo",
            "cat_html" to "HTML",
            "cat_css" to "CSS",
            "cat_js" to "JavaScript",
            "cat_python" to "Python",
            "cat_mobile_dev" to "Nhluvukiso wa Foni",
            "cat_data_ai" to "Data na AI",
            "cat_design" to "Vuvumbi",
            "start_lesson" to "Sungula Dondzo",
            "continue_lesson" to "Yana Mambirhi",
            "lesson_completed" to "Yi Hetile",
            "step" to "Goza",
            "next_step" to "Goza leri Landzelaka",
            "prev_step" to "Ntlhantlha",
            "code_editor" to "Muchini wo Ringeta Khodi",
            "web_emulator" to "Xifaniso xa Webusayiti",
            "hint" to "Xitsundzuxo",
            "knowledge_check" to "Kambela Vutivi",
            "submit_answer" to "Rhula Nhlamulo",
            "next_question" to "Xivutiso lexi Landzelaka",
            "score" to "Tinhlayo",
            "quiz_passed" to "U Pasile! Halala!",
            "settings" to "Swiyimiso",
            "select_home_lang" to "Hlawula Ririmi ra Kaya 🇿🇦",
            "cancel" to "Cima",
            "close" to "Pfala",
            "save" to "Hlayisa",
            "share" to "Avelana",
            "sisterhood" to "Vumakwavo bya Vamanana",
            "free_access" to "Mahala 100%",
            "spaza_math" to "Tinhlayo ta Spaza Shop",
            "sisterhood_mamas" to "Ageteriwe Vamanana na Vanhwanyana emalokitshini",
            "onboarding_headline" to "Ku nyika matimba eka vamanana va ntima na vanhwanyana hi khodi na ntshembo.",
            "offline_first" to "Offline ku Sungula",
            "quick_actions" to "Swiendlo swa xihatla",
            "explore_lessons" to "Kambisisa Tidondzo Hinkwato",
            "search_google" to "Lava eka Database ya Google",
            "gemini_connected" to "Yi hlanganisiwile na Gemini AI & Google",
            "version_label" to "Vhidiyo 1.3.0"
        ),
        "ss" to mapOf( // siSwati
            "learn_coding" to "Fundza kukhoda ngelulwimi lwakho",
            "brand_tagline" to "Khoda ngelulwimi lwakho. Fundza nome ngukuphi. Yakha likusasa lakho.",
            "offline_online" to "Tifundvo te-Offline ne-Online",
            "built_for_sa" to "Yentelwe imiphakatsi yaseNingizimu Afrika",
            "get_started" to "Asicale",
            "dashboard" to "Ekhaya",
            "builds" to "Imiklamo",
            "lessons" to "Fundza",
            "quizzes" to "Imibuto",
            "ai_assistant" to "AI Make",
            "community" to "Umphakatsi",
            "profile" to "Iphrofayili",
            "premium" to "Kuceceshwa",
            "total_xp" to "XP Seisonke",
            "streak" to "Malanga lalandzelanako",
            "unlocked" to "Kuvuliwe",
            "locked" to "Kuvaliwe",
            "downloaded" to "Kulandiwe",
            "download_class" to "Landa Sifundvo",
            "download_all" to "Landa Tonkhe Tifundvo",
            "data_saver" to "Konga Idatha",
            "online_status" to "Ku-Inthanethi",
            "offline_status" to "Ngaphandle kwenethiwekhi",
            "ask_something" to "Mbutise umbulo wekhodingi...",
            "careers" to "Litfuba leMisebenti",
            "one_on_one" to "Kuceceshwa kwe-1-ku-1",
            "cv_builder" to "Umakhi we-CV lula",
            "interviews" to "Kutilungiselela Inthavyu",
            "networking" to "Inethiwekhi ye-Tech",
            "daily_challenges" to "Inselelo yelilanga",
            "submit_code" to "Calisa & Cinisekisa",
            "congrats" to "Halala! Ugcinile!",
            "get_certificate" to "Tsatsa Sitifiketi",
            "founder_story" to "Msunguli: Nokwazi Nobuhle Xaba",
            "founder_desc" to "KodeMamas yacalwa nguNokwazi Nobuhle Xaba, umfundzi wetheknoloji eBloemfontein kute asite bomake nebantfwana.",
            "testimonials" to "Tindzaba tekuhumelela",
            "data_saver_desc" to "Kunciphisa kudliwa kwedatha kutfoni yakho.",
            "enter_msg" to "Bhala umlayeto...",
            "in_your_language" to "Ngelulwimi Lwakho 🇿🇦:",
            "hello_mama" to "Sawubona, Make! 👋",
            "ready_future" to "Ukulungele kwakha likusasa lakho lelihle?",
            "interactive_curriculum" to "Luhlelo Lwetifundvo",
            "curriculum_subtitle" to "Khoda ngelulwimi lwakho • Yakhela umphakatsi wakho",
            "curriculum_progress" to "Inchubekelembili Yetifundvo",
            "offline_ready" to "Ilungele Offline",
            "all_offline_saved" to "Tonkhe tifundvo tigciniwe ngaphandle kwedatha",
            "all_categories" to "Tonkhe",
            "cat_html" to "HTML",
            "cat_css" to "CSS",
            "cat_js" to "JavaScript",
            "cat_python" to "Python",
            "cat_mobile_dev" to "Kutfutfukiswa Kwatifoni",
            "cat_data_ai" to "Idatha ne-AI",
            "cat_design" to "Kuklama",
            "start_lesson" to "Cala Sifundvo",
            "continue_lesson" to "Chubeka",
            "lesson_completed" to "Sekuphelile",
            "step" to "Sinyatselo",
            "next_step" to "Sinyatselo Lesilandzelako",
            "prev_step" to "Emuva",
            "code_editor" to "Silingisi Sekhodi Lesibukhoma",
            "web_emulator" to "Kubuka Kwe-Webhusayithi",
            "hint" to "Licebiso",
            "knowledge_check" to "Kuhlola Lwati",
            "submit_answer" to "Tfumela Imphendvulo",
            "next_question" to "Umbuto Lolandzelako",
            "score" to "Emamaki",
            "quiz_passed" to "Uphumelele! Halala!",
            "settings" to "Tilungiselelo",
            "select_home_lang" to "Khetsa Lulwimi Lwasekhaya 🇿🇦",
            "cancel" to "Khansela",
            "close" to "Vala",
            "save" to "Gcina",
            "share" to "Yabelana",
            "sisterhood" to "Ubuzalwane Babomake",
            "free_access" to "Kusebenta Mahhala 100%",
            "spaza_math" to "Tibalelo Tesitolo Se-Spaza",
            "sisterhood_mamas" to "Yentelwe Bomake Nemantfombatana",
            "onboarding_headline" to "Kunika bomake labamnyama nemantfombatana emandla ngekukhoda.",
            "offline_first" to "Kusebenta Ngaphandle Kwedatha",
            "quick_actions" to "Tento Letisheshako",
            "explore_lessons" to "Buka Tifundvo Tonkhe",
            "search_google" to "Sesha Kumatolwazi aGoogle",
            "gemini_connected" to "Ihlanganiswe ne-Gemini AI & Google",
            "version_label" to "Inguqulo 1.3.0"
        ),
        "ve" to mapOf( // Tshivenda
            "learn_coding" to "Gudani u khoda nga luambo lwanu",
            "brand_tagline" to "Khodani nga luambo lwanu. Gudani fhethu hothe. Fhatani vhumatshelo hanu.",
            "offline_online" to "Ngudo dza Offline na Online",
            "built_for_sa" to "Yo fhatelwa zwitshavha zwa Afrika Tshipembe",
            "get_started" to "Kha ri thome",
            "dashboard" to "Haya",
            "builds" to "Zwishumiswa",
            "lessons" to "Guda",
            "quizzes" to "Mbudziso",
            "ai_assistant" to "AI Mama",
            "community" to "Tshitshavha",
            "profile" to "Phurofayili",
            "premium" to "Vhulanga-ndaela",
            "total_xp" to "XP yothe",
            "streak" to "Maduvha o teledzanaho",
            "unlocked" to "Zwo vhululwaho",
            "locked" to "Zwo khiwiwaho",
            "downloaded" to "Zwo tangohedzwaho",
            "download_class" to "Kokiwa Ngudo hei",
            "download_all" to "Kokiwa Ngudo Dzothe",
            "data_saver" to "U vhulunga Data",
            "online_status" to "Kha Inthanete",
            "offline_status" to "Nnda ha Inthanete",
            "ask_something" to "Nvhudziseni mbudziso ya u khoda...",
            "careers" to "Thikhinthi ya dza Mishumo",
            "one_on_one" to "Ngudo dza 1-kha-1",
            "cv_builder" to "Mu fhati wa CV nga u tavhanya",
            "interviews" to "U diladzela Ndavhedzano",
            "networking" to "Nethiweke ya dza Thekino",
            "daily_challenges" to "Mbudziso dza Duvha",
            "submit_code" to "Shumani & Khunyeledzani",
            "congrats" to "Dakalo! No fhedza!",
            "get_certificate" to "Dzhiani Setifiketi",
            "founder_story" to "Musiki: Nokwazi Nobuhle Xaba",
            "founder_desc" to "KodeMamas yo thomiwa nga Nokwazi Nobuhle Xaba, mutshudeni wa IT ngei Bloemfontein u fha vhomama na vhaswa maanda.",
            "testimonials" to "Mikovhe ya u Tunda",
            "data_saver_desc" to "Zwi fhungudza kushumisello kwa data.",
            "enter_msg" to "Nwalani mulaedza...",
            "in_your_language" to "Nga Luambo Lwanu 🇿🇦:",
            "hello_mama" to "Ndaa / Aaa, Vhomama! 👋",
            "ready_future" to "No lugela u fhati vhumatshelo hanu?",
            "interactive_curriculum" to "Mbekanyamushumo ya Ngudo",
            "curriculum_subtitle" to "Khodani nga luambo lwanu • Fhatelani tshitshavha tshanu",
            "curriculum_progress" to "Mvelaphanda ya Ngudo",
            "offline_ready" to "Zwo lugela Offline",
            "all_offline_saved" to "Ngudo dzothe dzo vhulungwa nnda ha inthanete",
            "all_categories" to "Dzothe",
            "cat_html" to "HTML",
            "cat_css" to "CSS",
            "cat_js" to "JavaScript",
            "cat_python" to "Python",
            "cat_mobile_dev" to "Mveledziso ya Founu",
            "cat_data_ai" to "Data na AI",
            "cat_design" to "Mbumbo",
            "start_lesson" to "Thomani Ngudo",
            "continue_lesson" to "Bvelani Phanda",
            "lesson_completed" to "Zwo Fhela",
            "step" to "Vhudato",
            "next_step" to "Vhudato Vhu tevhelaho",
            "prev_step" to "Murahu",
            "code_editor" to "Mushini wa u Lingedza Khodi",
            "web_emulator" to "Mbofholowo ya Webusayiti",
            "hint" to "Ndivho",
            "knowledge_check" to "U sedza Ndivho",
            "submit_answer" to "Rumelani Phindulo",
            "next_question" to "Mbudziso i Tevhelaho",
            "score" to "Zwikoro",
            "quiz_passed" to "No Pasa! Dakalo!",
            "settings" to "Zwiimo",
            "select_home_lang" to "Nangani Luambo lwa Hayani 🇿🇦",
            "cancel" to "Kanselani",
            "close" to "Valani",
            "save" to "Vhulungani",
            "share" to "Kovhelani",
            "sisterhood" to "Vhuthihi ha Vhomama",
            "free_access" to "Mahala 100%",
            "spaza_math" to "Mbalelo dza Mavhengele a Spaza",
            "sisterhood_mamas" to "Zwo fhatelwa Vhomama na Vhasidzana",
            "onboarding_headline" to "U fha vhomama vhatswu maanda nga khoudu na u fulufhela.",
            "offline_first" to "Offline U thoma",
            "quick_actions" to "Nyito dza u Tavhanya",
            "explore_lessons" to "Sedzani Ngudo Dzothe",
            "search_google" to "Todani kha Databesi ya Google",
            "gemini_connected" to "I khou shumisana na Gemini AI & Google",
            "version_label" to "Mvumbo 1.3.0"
        ),
        "nr" to mapOf( // isiNdebele
            "learn_coding" to "Funda amakhodi ngolimi lwakho",
            "brand_tagline" to "Khoda ngolimi lwakho. Funda nanyana kukuphi. Yakha ingomuso lakho.",
            "offline_online" to "Izifundo ze-Offline ne-Online",
            "built_for_sa" to "Yenzelwe imiphakathi ye-Afrika yeSewula",
            "get_started" to "Asithome",
            "dashboard" to "Ekhaya",
            "builds" to "Imisebenzi",
            "lessons" to "Funda",
            "quizzes" to "Imibuzo",
            "ai_assistant" to "AI Mama",
            "community" to "Umphakathi",
            "profile" to "Iphrofayili",
            "premium" to "Ubeluleki",
            "total_xp" to "XP Yoke",
            "streak" to "Amalanga alandelanako",
            "unlocked" to "Ivulwe",
            "locked" to "Ivaliwe",
            "downloaded" to "Ilandiwe",
            "download_class" to "Thwebula Isifundo lesi",
            "download_all" to "Thwebula Zoke Izifundo",
            "data_saver" to "Ubulungi be-Data",
            "online_status" to "Une-Inthanethi",
            "offline_status" to "Ngaphandle kwe-Inthanethi",
            "ask_something" to "Mbuze umbuzo wekhodingi...",
            "careers" to "Urhasulu lweMisebenzi",
            "one_on_one" to "Isiluleko se-1-ku-1",
            "cv_builder" to "Umakhi we-CV lula",
            "interviews" to "Izilungiselelo ze-Inthavyu",
            "networking" to "SA Chobho we-Tech",
            "daily_challenges" to "Inselelo yelanga",
            "submit_code" to "Gijima ubuye Uqinisekise",
            "congrats" to "Halala! Uphelisile!",
            "get_certificate" to "Thatha Isitifiketi",
            "founder_story" to "Umsunguli: Nokwazi Nobuhle Xaba",
            "founder_desc" to "KodeMamas yasungulwa nguNokwazi Nobuhle Xaba, umfundi we-IT ne-Computer Science eBloemfontein kute asekele abomama nabatjha.",
            "testimonials" to "Iindaba zokuphumelela",
            "data_saver_desc" to "Kunciphisa ukusebenza kwe-data yeselula ematasa.",
            "enter_msg" to "Bhala umlayezo...",
            "in_your_language" to "Ngolimi Lwakho 🇿🇦:",
            "hello_mama" to "Lotjhani, Mma! 👋",
            "ready_future" to "Ukulungele ukwakha ingomuso lakho elihle?",
            "interactive_curriculum" to "Ikharikhyulamu Yezifundo",
            "curriculum_subtitle" to "Khoda ngolimi lwakho • Yakhela umphakathi wakho",
            "curriculum_progress" to "Iragelo phambili Yezifundo",
            "offline_ready" to "Ilungele ukusebenza Offline",
            "all_offline_saved" to "Zoke izifundo zibulungwe ngaphandle kwe-data",
            "all_categories" to "Zoke",
            "cat_html" to "HTML",
            "cat_css" to "CSS",
            "cat_js" to "JavaScript",
            "cat_python" to "Python",
            "cat_mobile_dev" to "Ukuthuthukiswa Kweselula",
            "cat_data_ai" to "Idatha ne-AI",
            "cat_design" to "Ukuklama",
            "start_lesson" to "Thoma Isifundo",
            "continue_lesson" to "Ragela Phambili",
            "lesson_completed" to "Kuphelile",
            "step" to "Igadango",
            "next_step" to "Igadango Elilandelako",
            "prev_step" to "Emuva",
            "code_editor" to "Isilingisi Sekhowudi Esiphilako",
            "web_emulator" to "Ukubona Kwe-Webhusayithi",
            "hint" to "Ilayelo",
            "knowledge_check" to "Ukuhlola Ilwazi",
            "submit_answer" to "Thumela Iphendulo",
            "next_question" to "Umbuzo Olandelako",
            "score" to "Amanqaku",
            "quiz_passed" to "Uphasile! Halala!",
            "settings" to "Izilungiselelo",
            "select_home_lang" to "K Khetha Ulimi Lwekhabo 🇿🇦",
            "cancel" to "Cima",
            "close" to "Vala",
            "save" to "Bulunga",
            "share" to "Yabelana",
            "sisterhood" to "Ubuhlobo Babomama",
            "free_access" to "Kusimahla 100%",
            "spaza_math" to "Izibalo Zesitolo Se-Spaza",
            "sisterhood_mamas" to "Yenzelwe Abomama Namantombazana",
            "onboarding_headline" to "Ukunika abomama abanzima namantombazana amandla ngekhowudi nokuzethemba.",
            "offline_first" to "Offline Kokuthoma",
            "quick_actions" to "Izenzo Ezirhabako",
            "explore_lessons" to "Tjheja Zoke Izifundo",
            "search_google" to "Rhubhulula Kusizindalwazi sakaGoogle",
            "gemini_connected" to "Ihlanganiswe ne-Gemini AI & Google",
            "version_label" to "Inguqulo 1.3.0"
        ),
        "sasl" to mapOf( // South African Sign Language (Visual & Sign Glossing)
            "learn_coding" to "[👋 LEARN] [💻 CODE] [🇿🇦 SIGN LANGUAGE SASL]",
            "brand_tagline" to "[💻 CODE] In Sign Language. Visual Guides. Build Future.",
            "offline_online" to "[📶 OFFLINE + ONLINE] Visual Lessons",
            "built_for_sa" to "[🇿🇦 BUILT] For Deaf & Hearing Communities",
            "get_started" to "[👉 START] Visual Journey",
            "dashboard" to "[🏠 HOME] Visual Board",
            "builds" to "[🛠️ BUILDS] Projects",
            "lessons" to "[📚 LEARN] Visual Class",
            "quizzes" to "[❓ QUIZ] Visual Check",
            "ai_assistant" to "[🤖 AI MAMA] Visual Helper",
            "community" to "[👥 CIRCLE] Deaf Space",
            "profile" to "[👤 PROFILE] Visual XP",
            "premium" to "[🤝 MENTOR] Signed Help",
            "total_xp" to "[⭐ TOTAL XP] Visual Score",
            "streak" to "[🔥 STREAK] Daily Signs",
            "unlocked" to "[🔓 UNLOCKED] Ready",
            "locked" to "[🔒 LOCKED] Progress",
            "downloaded" to "[💾 SAVED] Offline",
            "download_class" to "[📥 SAVE] Lesson Video",
            "download_all" to "[📥 SAVE ALL] Offline Lessons",
            "data_saver" to "[📉 DATA SAVER] Active",
            "online_status" to "[🌐 ONLINE] Streaming",
            "offline_status" to "[📴 OFFLINE] Loadshedding Ready",
            "ask_something" to "[❓ ASK] Sign or Type Code...",
            "careers" to "[💼 CAREERS] Deaf Tech Hub",
            "one_on_one" to "[👥 1-ON-1] Sign Mentorship",
            "cv_builder" to "[📄 CV] Visual Portfolio",
            "interviews" to "[🤝 INTERVIEWS] Sign Prep",
            "networking" to "[🌐 NETWORK] SA Sign Tech",
            "daily_challenges" to "[🎯 DAILY] Visual Challenge",
            "submit_code" to "[▶️ RUN] Test & Verify Code",
            "congrats" to "[👏 THUMBS UP] [✨ HALALA] Done!",
            "get_certificate" to "[📜 CERTIFICATE] Claim Signed Award",
            "founder_story" to "[👤 FOUNDER] Nokwazi Nobuhle Xaba",
            "founder_desc" to "Founded by Nokwazi Nobuhle Xaba, studying IT & Computer Science in Bloemfontein. Dedicated to Deaf inclusion and empowering all South Africans to code visually.",
            "testimonials" to "[🌟 STORIES] Deaf Success Stories",
            "data_saver_desc" to "Protects mobile data while preserving visual clarity.",
            "enter_msg" to "[✍️ TYPE] Message / Sign prompt...",
            "in_your_language" to "[🇿🇦 IN SASL SIGN LANGUAGE]:",
            "hello_mama" to "[👋 HELLO, MAMA] [🤟 WELCOME]!",
            "ready_future" to "[✨ READY] To build your tech future?",
            "interactive_curriculum" to "[📚 CURRICULUM] Visual Coding Path",
            "curriculum_subtitle" to "[💻 CODE] In Visual Signs • For Your Community",
            "curriculum_progress" to "[📊 PROGRESS] Curriculum Path",
            "offline_ready" to "[💾 OFFLINE] Ready Without Data",
            "all_offline_saved" to "All lessons saved visually for offline study",
            "all_categories" to "[ALL] Categories",
            "cat_html" to "HTML (Web)",
            "cat_css" to "CSS (Style)",
            "cat_js" to "JavaScript",
            "cat_python" to "Python",
            "cat_mobile_dev" to "[📱 MOBILE DEV]",
            "cat_data_ai" to "[🤖 DATA & AI]",
            "cat_design" to "[🎨 DESIGN]",
            "start_lesson" to "[▶️ START] Lesson",
            "continue_lesson" to "[⏩ CONTINUE] Lesson",
            "lesson_completed" to "[✅ DONE] Completed",
            "step" to "[STEP]",
            "next_step" to "[NEXT ➡️] Step",
            "prev_step" to "[⬅️ BACK] Step",
            "code_editor" to "[💻 SIMULATOR] Live Code Editor",
            "web_emulator" to "[🖥️ PREVIEW] Visual Screen",
            "hint" to "[💡 HINT] Visual Cue",
            "knowledge_check" to "[❓ CHECK] Test Your Understanding",
            "submit_answer" to "[✔️ SUBMIT] My Answer",
            "next_question" to "[NEXT ➡️] Question",
            "score" to "[SCORE] Result",
            "quiz_passed" to "[👏 CELEBRATE] Passed With Honors!",
            "settings" to "[⚙️ SETTINGS] Preferences",
            "select_home_lang" to "[🇿🇦 CHOOSE] Preferred Language / SASL",
            "cancel" to "[CANCEL]",
            "close" to "[CLOSE]",
            "save" to "[SAVE]",
            "share" to "[SHARE]",
            "sisterhood" to "[👭 SISTERHOOD] Mamas Network",
            "free_access" to "[FREE] 100% Free Access",
            "spaza_math" to "[🏪 STORE MATH] Spaza Calculations",
            "sisterhood_mamas" to "[🇿🇦 TOWNSHIP TECH] For Mothers & Daughters",
            "onboarding_headline" to "[EMPOWER] Black mothers and girls in South African townships through code.",
            "offline_first" to "[📶 OFFLINE FIRST] Always Accessible",
            "quick_actions" to "[⚡ QUICK ACTIONS]",
            "explore_lessons" to "[🔍 EXPLORE] All Lessons",
            "search_google" to "[🔍 SEARCH] Google Knowledge Base",
            "gemini_connected" to "[🤖 GEMINI AI] + Google Grounded",
            "version_label" to "Version 1.3.0"
        )
    )

    fun translate(key: String, lang: String): String {
        val dict = translations[lang] ?: translations["en"]!!
        return dict[key] ?: translations["en"]?.get(key) ?: key
    }

    // -------------------------------------------------------------
    // DYNAMIC LESSON LOCALIZATION FOR ALL 12 SOUTH AFRICAN LANGUAGES
    // -------------------------------------------------------------
    data class LocalizedLessonInfo(
        val title: String,
        val subtitle: String
    )

    private val lessonTitles = mapOf(
        // HTML Lessons
        "html_1" to mapOf(
            "en" to LocalizedLessonInfo("Intro to HTML (Web Layout)", "Mam's Spaza Shop Storefront"),
            "zu" to LocalizedLessonInfo("Isiqalo ku-HTML (Isakhiwo Sewebhusayithi)", "Isitolo Sika-Mama Se-Spaza"),
            "xh" to LocalizedLessonInfo("Intshayelelo kwi-HTML (Uyilo lweWebhu)", "Ivenkile yeSpaza kaMama"),
            "af" to LocalizedLessonInfo("Inleiding tot HTML (Webuitleg)", "Mamma se Spaza-winkel Webblad"),
            "nso" to LocalizedLessonInfo("Matseno a HTML (Sebopego sa Weposaete)", "Lebenkele la Spaza la ga Mma"),
            "tn" to LocalizedLessonInfo("Kaelo ya HTML (Tebego ya Webosaete)", "Bentlele ya Spaza ya ga Mma"),
            "st" to LocalizedLessonInfo("Kenyelletso ya HTML (Sebopeho sa Wepe)", "Lebenkele la Spaza la Mme"),
            "ts" to LocalizedLessonInfo("Masungulo ya HTML (Vumbhalo bya Web)", "Xitolo xa Spaza xa Manana"),
            "ss" to LocalizedLessonInfo("Kucala nge-HTML (Sakhiwo seWebhusayithi)", "Sitolo seSpaza saMake"),
            "ve" to LocalizedLessonInfo("U thoma nga HTML (Tshivhumbeo tsha Web)", "Vhengele la Spaza la Vhomama"),
            "nr" to LocalizedLessonInfo("Isithomo se-HTML (Ukwakheka kweWebhu)", "Isitolo seSpaza sakaMma"),
            "sasl" to LocalizedLessonInfo("[💻 HTML 1] Web Layout", "[🏪 STORE] Mam's Spaza Front")
        ),
        "html_2" to mapOf(
            "en" to LocalizedLessonInfo("Interactive Forms & Customer Inputs", "Spaza Digital Order & Delivery Booking"),
            "zu" to LocalizedLessonInfo("Amafomu Wokusebenzisana Nezicelo Zamakhasimende", "Uku-oda Noku-bhukha Izimpahla E-Spaza"),
            "xh" to LocalizedLessonInfo("Iifom eziSebenzisanayo kunye neZicelo", "Uku-odola kunye nokuHanjiswa kweVenkile"),
            "af" to LocalizedLessonInfo("Interaktiewe Vorms en Klante-insette", "Spaza Digitale Bestellings en Aflewering"),
            "nso" to LocalizedLessonInfo("Difomo tša Tirišano le Ditirelo tša Bareki", "Taelo ya Ditšweletšwa tša Spaza"),
            "tn" to LocalizedLessonInfo("Difomo le Ditlhokego tsa Badirisi", "Diodara le Ditirelo tsa Spaza"),
            "st" to LocalizedLessonInfo("Diforomo tsa Tshebedisano le Ditaelo", "Ho Odara Dijo tsa Lebenkele la Spaza"),
            "ts" to LocalizedLessonInfo("Tifomo ta ku Tirhisana na Swilaveko", "Ku Odara Swakudya swa Spaza"),
            "ss" to LocalizedLessonInfo("Emafomu Ekusebentisana Neku-oda Kwemakhasimende", "Ku-oda Kwekudla Kwasitolo"),
            "ve" to LocalizedLessonInfo("Fomo dza Vhushumisani na Khumbelo", "U Odara Zwithu zwa Vhengele"),
            "nr" to LocalizedLessonInfo("Amafomu Wokusebenzisana Nezibawo Zamakhasimende", "U-oda Kwezinto zeSpaza"),
            "sasl" to LocalizedLessonInfo("[📝 FORMS] Customer Orders", "[📦 DELIVERY] Spaza Digital Order")
        ),
        "html_3" to mapOf(
            "en" to LocalizedLessonInfo("Semantic HTML & Township Media", "Adding Community Audio, Video & Gallery"),
            "zu" to LocalizedLessonInfo("I-Semantic HTML Nemidiya YaseLalokishini", "Ukufaka Imisindo, Amavidiyo Nemifanekiso"),
            "xh" to LocalizedLessonInfo("I-Semantic HTML kunye neMedia yaseLokishini", "Ukufaka Izandi, Iividiyo kunye neeFoto"),
            "af" to LocalizedLessonInfo("Semantiese HTML en Plaaslike Media", "Voeg Klank, Video en Fotogalery By"),
            "nso" to LocalizedLessonInfo("HTML ya Semantiki le Ditaba tša Setšhaba", "Go tsenya Medumo, Dibidio le Dinepe"),
            "tn" to LocalizedLessonInfo("HTML ya Maemo le Media ya Metse", "Go tsenya Medumo, Dibidio le Ditshwantsho"),
            "st" to LocalizedLessonInfo("HTML le Mecha ya Ditaba ya Metse", "Ho kenya Modumo, Divideo le Ditshwantsho"),
            "ts" to LocalizedLessonInfo("Semantic HTML na Swihaxa-mahungu swa Vaaki", "Ku nghenisa Mpfumawulo, Tivhidiyo na Swifaniso"),
            "ss" to LocalizedLessonInfo("I-Semantic HTML Nemidiya Yaselokishini", "Kufaka Umsindvo, Emavidiyo Netitfombe"),
            "ve" to LocalizedLessonInfo("HTML ya Semantiki na Zwithu zwa Media", "U dzhenisa Zwidumbidzo na Zwifanyiso"),
            "nr" to LocalizedLessonInfo("I-Semantic HTML Nemidiya Yekhabo", "Ukufaka Imisindo, Amavidiyo Nemithombe"),
            "sasl" to LocalizedLessonInfo("[🎥 MEDIA] Semantic HTML Layout", "[🖼️ GALLERY] Audio, Video & Signs")
        ),

        // CSS Lessons
        "css_2" to mapOf(
            "en" to LocalizedLessonInfo("Adding Style with CSS", "Beautifying Your Online Catalog"),
            "zu" to LocalizedLessonInfo("Ukufaka Izitayela nge-CSS", "Ukuhlobisa Ikhathalogi Yesitolo Sakho"),
            "xh" to LocalizedLessonInfo("Ukongeza Isitayile nge-CSS", "Ukuhombisa Ikhathalogu yakho yeWebhu"),
            "af" to LocalizedLessonInfo("Styling met CSS", "Verfraai Jou Aanlyn Katalogus"),
            "nso" to LocalizedLessonInfo("Go tsenya Setaele ka CSS", "Go kgabiša Lenaneo la Dithekišo"),
            "tn" to LocalizedLessonInfo("Go kgabisa ka CSS", "Go ntlafatsa Khathaloko ya Gago"),
            "st" to LocalizedLessonInfo("Ho kgabisa ka CSS", "Ho kgabisa Lenane la Thekiso"),
            "ts" to LocalizedLessonInfo("Ku xongisa hi CSS", "Ku khavisa Khathaloko ya Wena"),
            "ss" to LocalizedLessonInfo("Kuhlobisa nge-CSS", "Kuhlobisa Libhuku Lemikhicito"),
            "ve" to LocalizedLessonInfo("U nakisa nga CSS", "U nakisa Khathaloko ya Vhengele"),
            "nr" to LocalizedLessonInfo("Ukuhlobisa nge-CSS", "Ukwenza Isitolo Sakho Sibe Sihle"),
            "sasl" to LocalizedLessonInfo("[🎨 CSS 1] Colors & Style", "[✨ DESIGN] Beautiful Catalog")
        ),
        "css_3" to mapOf(
            "en" to LocalizedLessonInfo("Flexbox & Grid Layouts", "Product Shelves & Responsive Cards"),
            "zu" to LocalizedLessonInfo("I-Flexbox ne-Grid Layouts", "Amashalofu Emikhiqizo Namakhadi Ahlelekile"),
            "xh" to LocalizedLessonInfo("Uyilo lwe-Flexbox kunye ne-Grid", "Iishelfu zeMveliso kunye naMakhadi"),
            "af" to LocalizedLessonInfo("Flexbox en Grid Uitlegte", "Produk-rakke en Aanpasbare Kaarte"),
            "nso" to LocalizedLessonInfo("Peakanyo ya Flexbox le Grid", "Diraka tša Ditšweletšwa le Dikarata"),
            "tn" to LocalizedLessonInfo("Thulaganyo ya Flexbox le Grid", "Diraka tsa Dithoto le Dikarata"),
            "st" to LocalizedLessonInfo("Sebopeho sa Flexbox le Grid", "Diraka tsa Dihlahiswa le Dikarata"),
            "ts" to LocalizedLessonInfo("Mavumbelo ya Flexbox na Grid", "Tishelefu ta Switirhisiwa na Makhadi"),
            "ss" to LocalizedLessonInfo("Sakhiwo se-Flexbox ne-Grid", "Emashelefu Emikhicito Nemakhadi"),
            "ve" to LocalizedLessonInfo("Mbumbo dza Flexbox na Grid", "Zwiṱalafu zwa Zwithu na Garata"),
            "nr" to LocalizedLessonInfo("Ukuhlela nge-Flexbox ne-Grid", "Amashalofu Wempahla Namakhadi"),
            "sasl" to LocalizedLessonInfo("[📐 GRID] Flexbox Layouts", "[📦 SHELVES] Product Grid Cards")
        ),
        "css_4" to mapOf(
            "en" to LocalizedLessonInfo("Responsive Mobile-First Design", "Media Queries for Low-End Smartphones"),
            "zu" to LocalizedLessonInfo("Ukuklama Omakhalekhukhwini Kuqala", "I-Media Queries Yezingcingo Zasemalokishini"),
            "xh" to LocalizedLessonInfo("Uyilo lwe-Mobile-First oluKhawulezayo", "I-Media Queries yeeFowuni eziNcinane"),
            "af" to LocalizedLessonInfo("Mobiel-Eerste Ontwerp", "Medianavrae vir Bekostigbare Slimfone"),
            "nso" to LocalizedLessonInfo("Tlhamo ya Difounu tša Matsogo Pele", "Tshepedišo ya Media go Difounu tše nnyane"),
            "tn" to LocalizedLessonInfo("Thulaganyo ya Difounu Pele", "Ditshepediso tsa Media mo Difounung"),
            "st" to LocalizedLessonInfo("Moralo wa Lifono Pele", "Media Queries bakeng sa Difono tse Tlwaelehileng"),
            "ts" to LocalizedLessonInfo("Vuvumbi bya Tiselfoni ku Sungula", "Swileriso swa Media eka Tiselfoni"),
            "ss" to LocalizedLessonInfo("Kwakha Kwekucala Kwatifoni Temangcondvo", "I-Media Queries Yetifoni"),
            "ve" to LocalizedLessonInfo("U fhatela Dithingothendeleki u Thoma", "Zwiṱirathedzhi zwa Founu dzo doweleaho"),
            "nr" to LocalizedLessonInfo("Ukuklama Iinwบริการ Zeselula Kokuthoma", "Ukwenza Isayithi Ilingane Emafonini"),
            "sasl" to LocalizedLessonInfo("[📱 MOBILE] Mobile-First Design", "[📐 SCREENS] Media Queries for Phones")
        ),

        // JavaScript Lessons
        "js_3" to mapOf(
            "en" to LocalizedLessonInfo("Interactive JS Calculations", "Calculating Bread & Veggie Orders"),
            "zu" to LocalizedLessonInfo("Izibalo Zokusebenza nge-JavaScript", "Ukubala Izindleko Zesinkwa Nemifino"),
            "xh" to LocalizedLessonInfo("Ubalo oluSebenzayo nge-JavaScript", "Ukubala Iindleko zeSonka kunye neMifuno"),
            "af" to LocalizedLessonInfo("Interaktiewe JS Berekeninge", "Bereken Brood en Groente Bestellings"),
            "nso" to LocalizedLessonInfo("Dipalo tša Tirišano tša JavaScript", "Go bala Ditheko tša Borotho le Merogo"),
            "tn" to LocalizedLessonInfo("Dipalo tsa JS tsa Tiriso", "Go bala Diodara tsa Borotho le Merogo"),
            "st" to LocalizedLessonInfo("Dipalo tsa Tshebetso ka JavaScript", "Ho bala Litjeo tsa Bohobe le Meroho"),
            "ts" to LocalizedLessonInfo("Swikambelo swa JS swo Tirhisana", "Ku hlaya Nxavo wa Xinkwa na Matsavu"),
            "ss" to LocalizedLessonInfo("Tibalelo Teluhlelo lwe-JavaScript", "Kubala Intengo Yesinkhwa Nemifino"),
            "ve" to LocalizedLessonInfo("Mbalelo dza Vhushumisani dza JS", "U vhalela Mutengo wa Vhurotho na Miri"),
            "nr" to LocalizedLessonInfo("Izibalo Zokusebenza nge-JS", "Ukubala Izindleko Zesikwa Nemirogo"),
            "sasl" to LocalizedLessonInfo("[🔢 JS 1] Math Calculations", "[🍞 ORDERS] Spaza Rand Total")
        ),
        "js_4" to mapOf(
            "en" to LocalizedLessonInfo("DOM Manipulation & Event Listeners", "Adding to Cart & Real-Time Total"),
            "zu" to LocalizedLessonInfo("Ukuphatha I-DOM Nezenzo Zokucofa", "Ukufaka Ekolini Nesamba Sesikhathi Sangempela"),
            "xh" to LocalizedLessonInfo("Ulawulo lwe-DOM kunye nezehlo zokuCofa", "Ukongeza kwiQhina kunye neXabiso leXesha"),
            "af" to LocalizedLessonInfo("DOM Manipulasie en Klik-aksies", "Voeg By Waentjie en Intydse Totaal"),
            "nso" to LocalizedLessonInfo("Tsamaišo ya DOM le Ditiragalo tša go Kgotla", "Go tsenya Kariking le Palomoka ya Nako"),
            "tn" to LocalizedLessonInfo("Tsamaiso ya DOM le Ditiragalo", "Go tsenya mo Kariking le Palogotlhe"),
            "st" to LocalizedLessonInfo("Tsamaiso ya DOM le Diketso tsa ho Tobetsa", "Ho kenya Kariking le Kakaretso ya Nako"),
            "ts" to LocalizedLessonInfo("Kulawula DOM na Swiendlakalo swa ku Tlanya", "Ku nghenisa eka Nkwama na Ntsengo"),
            "ss" to LocalizedLessonInfo("Kulawula i-DOM Netento Tekucindzeteleka", "Kufaka Engolovaneni Nesamba"),
            "ve" to LocalizedLessonInfo("Ndaulo ya DOM na Nyito dza u Thwanya", "U dzhenisa Garikini na Mutengo woṱhe"),
            "nr" to LocalizedLessonInfo("Ukuphatha i-DOM Nezenzo Zokutlanya", "Ukufaka Ekoloyini Nesambaphathi"),
            "sasl" to LocalizedLessonInfo("[🛒 CART] DOM & Click Events", "[➕ ADD] Real-Time Total Update")
        ),
        "js_5" to mapOf(
            "en" to LocalizedLessonInfo("Async Data & Fetch APIs", "Live Township Weather & Produce Market Prices"),
            "zu" to LocalizedLessonInfo("I-Async Data Nokusetshenziswa Kwama-API", "Isimo Sezulu Nezintengo Zemakethe Zasekhaya"),
            "xh" to LocalizedLessonInfo("I-Async Data kunye nokuFumana ii-API", "Imozulu kunye naMaxabiso eMarike"),
            "af" to LocalizedLessonInfo("Asinchrone Data en Fetch API's", "Plaaslike Weer en Vars Markpryse"),
            "nso" to LocalizedLessonInfo("Tshedimošo ya Async le go goga di-API", "Boso bja Selegae le Ditheko tša Mmaraka"),
            "tn" to LocalizedLessonInfo("Tshedimosetso ya Async le di-API", "Bosa jwa Selegae le Ditlhwatlhwa tsa Mmaraka"),
            "st" to LocalizedLessonInfo("Tlhahisoleseding ya Async le di-API", "Boemo ba Lehodimo le Ditheko tsa Mmaraka"),
            "ts" to LocalizedLessonInfo("Async Data na ku Koka ti-API", "Maxelo ya Kaya na Mixavo ya Makete"),
            "ss" to LocalizedLessonInfo("I-Async Data Nekulandwa Kwema-API", "Simo Selitulu Netintsengo Temakethe"),
            "ve" to LocalizedLessonInfo("Muta wa Async na dzo Khokhiwaho dza API", "Mutsho na Mitengo ya Makete wa Vhupo"),
            "nr" to LocalizedLessonInfo("I-Async Data Nokusikwa Kwama-API", "Ubujamo Bezulu Namanani Wemakethe"),
            "sasl" to LocalizedLessonInfo("[🌐 FETCH API] Async Data Feed", "[🌦️ WEATHER] Live Market Produce")
        ),

        // Python Lessons
        "python_4" to mapOf(
            "en" to LocalizedLessonInfo("Python Crop Agriculture Tracker", "Harvesting & Pricing Predictions"),
            "zu" to LocalizedLessonInfo("Ukulandelela Ezolimo nge-Python", "Ukubikezela Isivuno Namanani Emakethe"),
            "xh" to LocalizedLessonInfo("Umlandeli wezoLimo nge-Python", "Uqikelelo lweSivuno kunye naMaxabiso"),
            "af" to LocalizedLessonInfo("Python Landbou-opspoorder", "Oes- en Prysvoorspellings"),
            "nso" to LocalizedLessonInfo("Molatedi wa Temo ka Python", "Go akanya Puno le Ditheko tša Temo"),
            "tn" to LocalizedLessonInfo("Molatetsi wa Temothuo ka Python", "Kaelo ya Thobo le Ditlhwatlhwa"),
            "st" to LocalizedLessonInfo("Molebeledi wa Temo ka Python", "Ho hakanya Kotulo le Ditheko tsa Mmaraka"),
            "ts" to LocalizedLessonInfo("Mulandeleri wa Vurimi hi Python", "Ku Vhumbha Ntshovelo na Mixavo"),
            "ss" to LocalizedLessonInfo("Kulandzelela Tzekulima nge-Python", "Kubiketela Sivuno Netintsengo Temakethe"),
            "ve" to LocalizedLessonInfo("Mutevheli wa zwa Vhulimi nga Python", "U vhumbha Kana na Mitengo ya zwa Vhulimi"),
            "nr" to LocalizedLessonInfo("Ukulandelela Zokulima nge-Python", "Ukufaka Isibalo Sesivuno Namanani"),
            "sasl" to LocalizedLessonInfo("[🌱 PYTHON 1] Smart Agriculture", "[🌾 HARVEST] Crop & Soil Predictions")
        ),
        "python_5" to mapOf(
            "en" to LocalizedLessonInfo("Lists, Dictionaries & Store Inventory", "Spaza Stock Management Engine"),
            "zu" to LocalizedLessonInfo("Amal निजी, Izichazamazwi Nempahla Yesitolo", "Uhlelo Lokuphatha Impahla Ye-Spaza"),
            "xh" to LocalizedLessonInfo("Uluhlu, Izichazi-magama kunye nempahla", "Injini yoLawulo lweTheki kwiSpaza"),
            "af" to LocalizedLessonInfo("Lyste, Woordeboeke en Winkelvoorraad", "Spaza Voorraadbestuurstelsel"),
            "nso" to LocalizedLessonInfo("Malokelelo, Di-dictionary le Ditšweletšwa", "Tsamaišo ya Setoko sa Spaza"),
            "tn" to LocalizedLessonInfo("Manane, Dibuka tsa Mafoko le Dithoto", "Tsamaiso ya Setoko sa Spaza"),
            "st" to LocalizedLessonInfo("Manane, Ditlhaloso le Thepa ya Lebenkele", "Tsamaiso ya Setoko sa Spaza"),
            "ts" to LocalizedLessonInfo("Nxaxamelo, Dikixinari na Nhundzu ya Xitolo", "Ntirho wo Lawula Xitoko xa Spaza"),
            "ss" to LocalizedLessonInfo("Tinhla, Tichazamagama Netitolo Temphahla", "Kuphatsa Sitoko Sesitolo"),
            "ve" to LocalizedLessonInfo("Mutevhe, Tholamaipfi na Zwithu zwa Vhengele", "Ndaulo ya Zwibveledzwa zwa Spaza"),
            "nr" to LocalizedLessonInfo("Uhlu, Izichazimazwi Nempahla Yesitolo", "Ukuphatha Impahla Zesitolo seSpaza"),
            "sasl" to LocalizedLessonInfo("[📋 LISTS & DICT] Inventory Engine", "[📊 STOCK] Spaza Stock Management")
        ),
        "python_6" to mapOf(
            "en" to LocalizedLessonInfo("Functions & Automation", "Automated WhatsApp / SMS Receipt Generator"),
            "zu" to LocalizedLessonInfo("Imisebenzi Nokuqhutshwa Okuzenzakalelayo", "Ukwakha Irisidi Elithunyelwa Ku-WhatsApp"),
            "xh" to LocalizedLessonInfo("Imisebenzi kunye nokuZenzekelayo", "Umenzi werisithi ozenzekelayo kwiWhatsApp"),
            "af" to LocalizedLessonInfo("Funksies en Outomatisering", "Outomatiese WhatsApp / SMS Kwitansie-bouer"),
            "nso" to LocalizedLessonInfo("Mešomo le Boitirelo bja go Khouta", "Sehloledi sa Riti ya WhatsApp le SMS"),
            "tn" to LocalizedLessonInfo("Ditiro le Boitirelo jwa Khoutu", "Mothomi wa Dirisiti tsa WhatsApp le SMS"),
            "st" to LocalizedLessonInfo("Mesebetsi le Boiketsetso ba Khoutu", "Moetsi wa Diresiti tsa WhatsApp le SMS"),
            "ts" to LocalizedLessonInfo("Mintirho na ku Tirha hi Koxe", "Muxavisi wa Dirisiti eka WhatsApp"),
            "ss" to LocalizedLessonInfo("Imisebenti Nekuhlelwa Kwekusebenta", "Kwakhiwa Kwerisidi Yekuthunyelwa Ku-SMS"),
            "ve" to LocalizedLessonInfo("Mishumo na Mishumo i no Diitela", "Mu vhumbi wa Dzirisiti dza WhatsApp"),
            "nr" to LocalizedLessonInfo("Imisebenzi Nokuzenzakalelako", "Ukwakha Irisidi ye-WhatsApp ne-SMS"),
            "sasl" to LocalizedLessonInfo("[⚙️ AUTOMATION] Python Functions", "[🧾 RECEIPT] WhatsApp/SMS Receipt Bot")
        ),

        // Mobile Dev Lessons
        "mobile_1" to mapOf(
            "en" to LocalizedLessonInfo("Android & Compose Fundamentals", "Building Your First Mobile App Screen"),
            "zu" to LocalizedLessonInfo("Izisekelo ze-Android ne-Compose", "Ukwakha Isikrini Sakho Sokuqala Seselula"),
            "xh" to LocalizedLessonInfo("Iziseko ze-Android kunye ne-Compose", "Ukwakha iSkrini sakho sokuQala se-App"),
            "af" to LocalizedLessonInfo("Android en Compose Grondbeginsels", "Bou Jou Eerste Mobiele Toepassingskerm"),
            "nso" to LocalizedLessonInfo("Motheo wa Android le Compose", "Go Aga Sekirini sa Founu sa Mathomo"),
            "tn" to LocalizedLessonInfo("Motheo wa Android le Compose", "Go Dira Skrine sa Mathomo sa Selefono"),
            "st" to LocalizedLessonInfo("Motheo wa Android le Compose", "Ho Haha Sekirini sa Mathomo sa Fono"),
            "ts" to LocalizedLessonInfo("Masungulo ya Android na Compose", "Ku Aka Xikirini xo Sungula xa Foni"),
            "ss" to LocalizedLessonInfo("Tisekelo te-Android ne-Compose", "Kwakha Sikrini Sakho Sekucala Setifoni"),
            "ve" to LocalizedLessonInfo("Mutevhe wa Android na Compose", "U fhasa Tshikirini tsha u Thoma tsha Founu"),
            "nr" to LocalizedLessonInfo("Izisekelo ze-Android ne-Compose", "Ukwakha Isikrini Sakho Sokuthoma Seselula"),
            "sasl" to LocalizedLessonInfo("[📱 ANDROID 1] Compose UI", "[📱 SCREEN] First Mobile App Screen")
        ),
        "mobile_2" to mapOf(
            "en" to LocalizedLessonInfo("State & Interactive Mobile UI", "Township Cart & Real-Time Counter"),
            "zu" to LocalizedLessonInfo("Isimo Nokusebenza Kweselula", "Ikalishi YaseLalokishini Nesibali Esibukhoma"),
            "xh" to LocalizedLessonInfo("I-State kunye ne-Interactive Mobile UI", "Inqwelo yaseLokishini kunye neKhawuntari"),
            "af" to LocalizedLessonInfo("Toestand en Interaktiewe Mobiele UI", "Spaza-waentjie en Intydse Teller"),
            "nso" to LocalizedLessonInfo("Maemo le Tirišano ya Selula", "Kariki ya Selegae le Sebaledi sa Nako"),
            "tn" to LocalizedLessonInfo("Boemo le Tiriso ya Selefono", "Kariki ya Spaza le Sebadisi sa Nako"),
            "st" to LocalizedLessonInfo("Boemo le Tshebedisano ya Fono", "Kariki ya Lebenkele le Sebadi sa Nako"),
            "ts" to LocalizedLessonInfo("Xiyimo na Ntirhisano wa Foni", "Nkwama wa Spaza na Muhlayi wa Nako"),
            "ss" to LocalizedLessonInfo("Simo Nekusebenta Kwatifoni", "Ikalishi Yaselokishini Nesibali Sesikhatsi"),
            "ve" to LocalizedLessonInfo("Tshiimo na Vhushumisani ha Founu", "Gariki ya Spaza na Tshivhali tsha Zwino"),
            "nr" to LocalizedLessonInfo("Ubujamo Nokusebenza Kweselula", "Ikoloyi Yebhizinisi Nesibali Esiphilako"),
            "sasl" to LocalizedLessonInfo("[🔄 STATE] Interactive Compose", "[🛒 CART] Real-Time Item Counter")
        ),
        "mobile_3" to mapOf(
            "en" to LocalizedLessonInfo("Offline-First Mobile Architecture", "Room Database & Loadshedding Resilience"),
            "zu" to LocalizedLessonInfo("Ukwakheka Kwezinhlelo Ngaphandle Kwedatha", "I-Room Database Nokuqina Ngezikhathi Zokucima Kukagesi"),
            "xh" to LocalizedLessonInfo("Uyilo lwe-Mobile olusebenza nge-Offline", "I-Room Database kunye noHlangulo lwe-Loadshedding"),
            "af" to LocalizedLessonInfo("Vanlyn-Eerste Mobiele Argitektuur", "Room Databasis en Beurtkrag-veerkragtigheid"),
            "nso" to LocalizedLessonInfo("Kago ya Selula ya Offline Pele", "Room Database le Poloko ya Ditima-mollo"),
            "tn" to LocalizedLessonInfo("Thulaganyo ya Selefono ya Offline Pele", "Room Database le Ditiragalo tsa Loadshedding"),
            "st" to LocalizedLessonInfo("Moaho wa Fono wa Offline Pele", "Room Database le Matla a ho se be le Motlakase"),
            "ts" to LocalizedLessonInfo("Mavumbelo ya Foni ya Offline ku Sungula", "Room Database na ku Hlayisa hi Nkarhi wo Tima Gezi"),
            "ss" to LocalizedLessonInfo("Kwakhiwa Kwatifoni Lokungadzingi Idatha", "I-Room Database Nekumelana Nekucima Kwagesi"),
            "ve" to LocalizedLessonInfo("Mbumbo ya Founu ya Offline u Thoma", "Room Database na u Shuma musi hu si na Mudagasi"),
            "nr" to LocalizedLessonInfo("Ukwakhiwa Kwamaselula Okusebenza Offline", "I-Room Database Nokuhlala Kuphila Ngesikhathi Sokucima Kwegezi"),
            "sasl" to LocalizedLessonInfo("[📴 OFFLINE ARCH] Room DB Cache", "[⚡ RESILIENCE] 100% Loadshedding Proof")
        ),

        // Data & AI Lessons
        "ai_1" to mapOf(
            "en" to LocalizedLessonInfo("AI & Prompt Engineering Basics", "Querying Gemini AI for Small Businesses"),
            "zu" to LocalizedLessonInfo("Izisekelo ze-AI Nokubhalwa Kwemiyalo", "Ukubuza i-Gemini AI Yamabhizinisi Asakhula"),
            "xh" to LocalizedLessonInfo("Iziseko ze-AI kunye noBunjineli be-Prompt", "Ukubuza i-Gemini AI kumashishini aMancinci"),
            "af" to LocalizedLessonInfo("KI & Vraag-ingenieurswese Grondbeginsels", "Vra Gemini KI vir Klein Besighede"),
            "nso" to LocalizedLessonInfo("Motheo wa AI le Tlhahlo ya Di-Prompt", "Go Botšiša Gemini AI ya Dikgwebo tše Nnyane"),
            "tn" to LocalizedLessonInfo("Motheo wa AI le Boitseanape jwa Ditaelo", "Go Botsa Gemini AI ya Dikgwebo tse Dinnye"),
            "st" to LocalizedLessonInfo("Motheo wa AI le Taolo ya Melaetsa", "Ho Botsa Gemini AI ya Dikgwebo tse Nyane"),
            "ts" to LocalizedLessonInfo("Masungulo ya AI na ku Tsala Swileriso", "Ku Vutisa Gemini AI ya Mabindzu Lamatsongo"),
            "ss" to LocalizedLessonInfo("Tisekelo te-AI Nekubhalwa Kwemiyalo", "Kubuta i-Gemini AI Yemabhizinisi Lamancane"),
            "ve" to LocalizedLessonInfo("Mutevhe wa AI na u Nwala Zwiṱirathedzhi", "U vhudzisa Gemini AI ya Mabindu Matuku"),
            "nr" to LocalizedLessonInfo("Izisekelo ze-AI Nokubhala Imiyalo", "Ukubuza i-Gemini AI Yamabhizinisi Amancani"),
            "sasl" to LocalizedLessonInfo("[🤖 AI BASICS] Prompt Engineering", "[💬 GEMINI] Gemini AI for Local Business")
        ),
        "ai_2" to mapOf(
            "en" to LocalizedLessonInfo("Data Analytics with Python & Pandas", "Predicting Spaza Grocery Demand"),
            "zu" to LocalizedLessonInfo("Ukuhlaziya Idatha nge-Python ne-Pandas", "Ukubikezela Isidingo Sokudla E-Spaza"),
            "xh" to LocalizedLessonInfo("Uhlahlelo lweDatha nge-Python ne-Pandas", "Uqikelelo lweMfuneko yeSpaza"),
            "af" to LocalizedLessonInfo("Data-analise met Python en Pandas", "Voorspel Spaza Kruideniersware-aanvraag"),
            "nso" to LocalizedLessonInfo("Tshekatsheko ya Data ka Python le Pandas", "Go Akanya Nyakego ya Dijo tša Spaza"),
            "tn" to LocalizedLessonInfo("Tshekatsheko ya Data ka Python le Pandas", "Go Bonela Pele Dijo tsa Spaza"),
            "st" to LocalizedLessonInfo("Tlhahlobo ya Data ka Python le Pandas", "Ho Bolela Pele Tlhoko ya Dijo tsa Lebenkele"),
            "ts" to LocalizedLessonInfo("Nxopaxopo wa Data hi Python na Pandas", "Ku Vhumbha Xilaveko xa Swakudya swa Spaza"),
            "ss" to LocalizedLessonInfo("Kuhlatiya Idatha nge-Python ne-Pandas", "Kubiketela Kudla Lokudzingekako e-Spaza"),
            "ve" to LocalizedLessonInfo("Tsedzuluso ya Data nga Python na Pandas", "U vhumbha Zwithu zwi Todwaho zwa Spaza"),
            "nr" to LocalizedLessonInfo("Ukuhlaziya Idatha nge-Python ne-Pandas", "Ukubala Izinto Ezithengwako eSpaza"),
            "sasl" to LocalizedLessonInfo("[📊 DATA] Python & Pandas Analytics", "[📈 DEMAND] Spaza Grocery Predictions")
        ),
        "ai_3" to mapOf(
            "en" to LocalizedLessonInfo("AI Grounding & Live Search", "Fact-Checking with Real-Time Web Data"),
            "zu" to LocalizedLessonInfo("Ukuqinisekisa Kwe-AI Nosesho Oluphilayo", "Ukuhlola Amaqiniso Ngolwazi Lwe-Webhusayithi"),
            "xh" to LocalizedLessonInfo("Ukumiliselwa kwe-AI kunye noPhando oluKhawulezayo", "Ukukhangela iNyaniso ngeDatha yeWebhu"),
            "af" to LocalizedLessonInfo("KI-Gronding en Regstreekse Soektog", "Feite-toetsing met Intydse Webdata"),
            "nso" to LocalizedLessonInfo("Tiišetšo ya AI le Nyako ya Nako Yona Ye", "Go Netefatša Ditaba ka Data ya Weposaete"),
            "tn" to LocalizedLessonInfo("Netefatso ya AI le Patlo ya Nako ya Jaanong", "Go Tlhola Boammaruri ka Data ya Webosaete"),
            "st" to LocalizedLessonInfo("Netefatso ya AI le Patlo ya Nako ya Jwale", "Ho Hlahloba Nnete ka Data ya Marang-rang"),
            "ts" to LocalizedLessonInfo("Ku Tiyisisa ka AI na ku Lava ka Xiyimo xa Sweswi", "Kambela Ntiyiso hi Data ya Web"),
            "ss" to LocalizedLessonInfo("Kucinisekisa Kwe-AI Nekusesha Lokubukhoma", "Kuhlola Liciniso Ngetindzaba Taku-inthanethi"),
            "ve" to LocalizedLessonInfo("U Tikedza ha AI na u Toda ha Zwino", "U vhambedza Ngoho nga Data ya Web"),
            "nr" to LocalizedLessonInfo("Ukuqiniseka Kwe-AI Nokusikisa Okuphilako", "Ukuhlola Iqiniso Ngedatha yeWebhu"),
            "sasl" to LocalizedLessonInfo("[🌐 GROUNDING] Gemini Live Search", "[🔍 FACT-CHECK] Real-Time Market Sources")
        ),

        // Design Lessons
        "design_1" to mapOf(
            "en" to LocalizedLessonInfo("UI/UX & Mobile Design Principles", "African Color Palettes & Accessibility"),
            "zu" to LocalizedLessonInfo("Izimiso Zokuklama Kwe-UI/UX", "Imibala Yase-Afrika Nokufinyeleleka Kalula"),
            "xh" to LocalizedLessonInfo("Imigaqo yoYilo lwe-UI/UX ye-Mobile", "Iiphalethi zeMibala yase-Afrika kunye nokuFikeleleka"),
            "af" to LocalizedLessonInfo("UI/UX en Mobiele Ontwerpbeginsels", "Afrika-kleurpalette en Toeganklikheid"),
            "nso" to LocalizedLessonInfo("Melao ya Tlhamo ya UI/UX ya Selula", "Mebala ya Afrika le Phihlelelo e Bonolo"),
            "tn" to LocalizedLessonInfo("Melao ya Moralo wa UI/UX ya Selefono", "Mebala ya Aforika le Phitlhelelo e e Motlhofo"),
            "st" to LocalizedLessonInfo("Melao-motheo ya Moralo wa UI/UX", "Mebala ya Afrika le Phihlello e Bonolo"),
            "ts" to LocalizedLessonInfo("Milawu ya Vuvumbi bya UI/UX eka Tiselfoni", "Mivala ya Afrika na ku Fikeleleka loku Olovaka"),
            "ss" to LocalizedLessonInfo("Tindlela Tekuklama Kwe-UI/UX", "Imibala Yase-Afrika Nekufinyeleleka"),
            "ve" to LocalizedLessonInfo("Milayo ya Mbumbo ya UI/UX ya Founu", "Mivhala ya Afrika na u Swikelela zwo Leleaho"),
            "nr" to LocalizedLessonInfo("Imithetho Yokuklama Kwe-UI/UX", "Imibala ye-Afrika Nokufikeleleka Lula"),
            "sasl" to LocalizedLessonInfo("[🎨 UI/UX DESIGN] Mobile Principles", "[🌈 PALETTES] African Colors & Accessible")
        ),
        "design_2" to mapOf(
            "en" to LocalizedLessonInfo("Figma to Code & Wireframing", "Translating Spaza Mockups to Compose"),
            "zu" to LocalizedLessonInfo("Kusuka ku-Figma Kuya Ekhodini", "Ukuguqula Imiklamo Ye-Spaza Ibe yi-Compose"),
            "xh" to LocalizedLessonInfo("Ukusuka kwiFigma ukuya kwiKhowudi", "Ukutshintsha i-Mockups yeSpaza ibe yi-Compose"),
            "af" to LocalizedLessonInfo("Figma na Kode en Draadraamwerk", "Vertaal Spaza-ontwerpe na Compose"),
            "nso" to LocalizedLessonInfo("Go Tloga go Figma go ya go Khoutu", "Go Fetolela Dihlalošo tša Spaza go Compose"),
            "tn" to LocalizedLessonInfo("Go Tswa mo Figma go ya Khoutung", "Go Fetola Ditshwantsho tsa Spaza go nna Compose"),
            "st" to LocalizedLessonInfo("Ho Tloha ho Figma ho ya Khoutung", "Ho Fetolela Meralo ya Spaza ho ba Compose"),
            "ts" to LocalizedLessonInfo("Ku Suka eka Figma ku ya eka Khodi", "Ku Hundzuluxa Swifaniso swa Spaza ku va Compose"),
            "ss" to LocalizedLessonInfo("Kusukela ku-Figma Kuya Ekhodini", "Kugucula Imidvwebo Ye-Spaza Kuye ku-Compose"),
            "ve" to LocalizedLessonInfo("U Bva kha Figma u ya kha Khodi", "U shandukisa Zwiolo zwa Spaza u ya kha Compose"),
            "nr" to LocalizedLessonInfo("Ukusuka ku-Figma Kuya Ekhowudini", "Ukuguqula Imiklamo yeSpaza Kuye ku-Compose"),
            "sasl" to LocalizedLessonInfo("[📐 FIGMA TO CODE] Wireframing", "[📱 MOCKUPS] Spaza Mockup to Compose")
        ),
        "design_3" to mapOf(
            "en" to LocalizedLessonInfo("Inclusive Design & Multi-Language UI", "Designing for 12 Languages & Non-Tech Mamas"),
            "zu" to LocalizedLessonInfo("Ukuklama Okubandakanya Bonke Abantu", "Ukuklama Ngezilimi Eziyi-12 Nawabo-Mama"),
            "xh" to LocalizedLessonInfo("Uyilo oluBandakanyayo kunye neeLwimi ezininzi", "Ukwenzela Iilwimi ezili-12 kunye noomama"),
            "af" to LocalizedLessonInfo("Inklusiewe Ontwerp en Meertalige UI", "Ontwerp vir 12 Tale en Nie-tegniese Mammas"),
            "nso" to LocalizedLessonInfo("Tlhamo ye e Akaretšago le Maleme a Mantši", "Go Tlhama Maleme a 12 bakeng sa Bomme"),
            "tn" to LocalizedLessonInfo("Moralo o o Akaretsang le Dipuo tse Dintsi", "Go Rulaganyetsa Dipuo di le 12 le Bomme"),
            "st" to LocalizedLessonInfo("Moralo o Kenyeletsang Bohle le Dipuo Tse Ngata", "Ho Rala bakeng sa Dipuo tse 12 le Bomme"),
            "ts" to LocalizedLessonInfo("Vuvumbi lebyi Katsaka Hinkwavo na Tindzimi to Tala", "Ku Vumba hi Tindzimi ta 12 na Vamanana"),
            "ss" to LocalizedLessonInfo("Kuklama Lokuhlanganisa Bonkhe Bantfu", "Kuklama Ngetilwimi Letili-12 Nabomake"),
            "ve" to LocalizedLessonInfo("Mbumbo i Katelaho Vhothe na Nyambo Nzhi", "U fhatele Nyambo dza 12 na Vhomama"),
            "nr" to LocalizedLessonInfo("Ukuklama Okuhlanganisa Woke Umuntu", "Ukuklamela Amalimi Amathathu na-9 Nabomama"),
            "sasl" to LocalizedLessonInfo("[🌍 INCLUSIVE] 12 Languages & SASL", "[👵 DESIGN] Non-Tech Mamas Accessible UI")
        )
    )

    fun getLessonTitle(lessonId: String, lang: String): String {
        val info = lessonTitles[lessonId]?.get(lang) ?: lessonTitles[lessonId]?.get("en")
        return info?.title ?: "Lesson $lessonId"
    }

    fun getLessonSubtitle(lessonId: String, lang: String): String {
        val info = lessonTitles[lessonId]?.get(lang) ?: lessonTitles[lessonId]?.get("en")
        return info?.subtitle ?: "Practical Township Coding"
    }

    fun getStepDescription(stepId: String, lang: String, englishDesc: String, zuluDesc: String = ""): String {
        return when (lang) {
            "en" -> englishDesc
            "zu" -> if (zuluDesc.isNotBlank()) zuluDesc else englishDesc
            "sasl" -> "[🤟 SASL SIGNED GUIDE]\n$englishDesc\n[👁️ VISUAL CUE: Watch syntax highlighting & spatial indentation structure.]"
            "af" -> "💡 Afrikaanse Nota:\n$englishDesc"
            "xh" -> if (zuluDesc.isNotBlank()) "💡 Isikhokelo:\n$zuluDesc" else "💡 Isikhokelo:\n$englishDesc"
            "nso" -> "💡 Tlhahlo ya Sepedi:\n$englishDesc"
            "tn" -> "💡 Kaelo ya Setswana:\n$englishDesc"
            "st" -> "💡 Tataiso ya Sesotho:\n$englishDesc"
            "ts" -> "💡 Nkongomiso wa Xitsonga:\n$englishDesc"
            "ss" -> if (zuluDesc.isNotBlank()) "💡 Sicondziso:\n$zuluDesc" else "💡 Sicondziso:\n$englishDesc"
            "ve" -> "💡 Tsumbandila ya Tshivenda:\n$englishDesc"
            "nr" -> if (zuluDesc.isNotBlank()) "💡 Isinqophiso:\n$zuluDesc" else "💡 Isinqophiso:\n$englishDesc"
            else -> englishDesc
        }
    }

    fun getStepDescription(stepId: String, lang: String, defaultDesc: String): String {
        return getStepDescription(stepId, lang, defaultDesc, "")
    }

    fun getQuizQuestion(quizId: String, lang: String, englishQ: String, zuluQ: String = ""): String {
        return when (lang) {
            "en" -> englishQ
            "zu" -> if (zuluQ.isNotBlank()) zuluQ else englishQ
            "sasl" -> "[❓ SASL SIGN QUESTION]: $englishQ"
            "af" -> "Vraag (Afrikaans): $englishQ"
            "xh" -> if (zuluQ.isNotBlank()) "Umbuzo: $zuluQ" else "Umbuzo: $englishQ"
            "nso" -> "Potšišo (Sepedi): $englishQ"
            "tn" -> "Potso (Setswana): $englishQ"
            "st" -> "Potso (Sesotho): $englishQ"
            "ts" -> "Xivutiso (Xitsonga): $englishQ"
            "ss" -> if (zuluQ.isNotBlank()) "Umbuto: $zuluQ" else "Umbuto: $englishQ"
            "ve" -> "Mbudziso (Tshivenda): $englishQ"
            "nr" -> if (zuluQ.isNotBlank()) "Umbuzo: $zuluQ" else "Umbuzo: $englishQ"
            else -> englishQ
        }
    }

    fun getQuizQuestion(quizId: String, lang: String, defaultQuestion: String): String {
        return getQuizQuestion(quizId, lang, defaultQuestion, "")
    }

    fun getQuizExplanation(quizId: String, lang: String, defaultExp: String): String {
        if (lang == "en") return defaultExp
        if (lang == "sasl") return "[💡 SASL EXPLANATION & SIGN NOTATION]: $defaultExp"
        val prefix = when (lang) {
            "zu" -> "Incazelo: "
            "xh" -> "Ingcaciso: "
            "af" -> "Verduideliking: "
            "nso" -> "Tlhaloso: "
            "tn" -> "Tlhaloso: "
            "st" -> "Tlhaloso: "
            "ts" -> "Nhlamuselo: "
            "ss" -> "Inchazelo: "
            "ve" -> "Thalutshedzo: "
            "nr" -> "Ihlathululo: "
            else -> ""
        }
        return "$prefix$defaultExp"
    }
}
