package com.example.ui.theme

object Localization {

    val languages = listOf(
        com.example.data.Language.ENGLISH,
        com.example.data.Language.ZULU,
        com.example.data.Language.XHOSA,
        com.example.data.Language.AFRIKAANS,
        com.example.data.Language.SEPEDI,
        com.example.data.Language.TSWANA,
        com.example.data.Language.SOTHO,
        com.example.data.Language.TSONGA,
        com.example.data.Language.SWAZI,
        com.example.data.Language.VENDA,
        com.example.data.Language.NDEBELE,
        com.example.data.Language.SIGN_LANGUAGE
    )

    private val translations = mapOf(
        "en" to mapOf(
            "learn_coding" to "Learn coding in your language",
            "offline_online" to "Offline + Online Lessons",
            "built_for_sa" to "Built for South African Communities",
            "get_started" to "Let's Begin",
            "dashboard" to "Dashboard",
            "lessons" to "Lessons",
            "quizzes" to "Quizzes",
            "ai_assistant" to "AI Chatbot",
            "community" to "Community",
            "profile" to "My Profile",
            "premium" to "Mentorship",
            "total_xp" to "Total XP",
            "streak" to "Streak Days",
            "unlocked" to "Unlocked",
            "locked" to "Locked",
            "downloaded" to "Downloaded",
            "download_class" to "Download Lesson",
            "data_saver" to "Data-Saving Mode",
            "online_status" to "Online Mode",
            "offline_status" to "Offline Mode",
            "ask_something" to "Ask me a coding question...",
            "careers" to "Careers Support",
            "one_on_one" to "1-on-1 Mentorship",
            "cv_builder" to "CV & Resume Builder",
            "interviews" to "Interview Prep",
            "networking" to "SA Tech Network",
            "daily_challenges" to "Daily Challenge",
            "submit_code" to "Run & Verify Code",
            "congrats" to "Halala! Completed!",
            "get_certificate" to "Claim Certificate",
            "founder_story" to "Meet the Founders",
            "founder_desc" to "KodeMamas was started in Soweto by Naledi and Akhona, two township dev moms who believe coding can break the cycle of poverty. We teach moms, girls, and communities to code to create their own digital futures.",
            "testimonials" to "Mamas Success Stories",
            "data_saver_desc" to "Compresses images & limits server requests to save your expensive mobile data.",
            "enter_msg" to "Type a message..."
        ),
        "zu" to mapOf( // isiZulu
            "learn_coding" to "Funda amakhodi ngolimi lwakho",
            "offline_online" to "Izifundo ngezikhathi zonke",
            "built_for_sa" to "Yakhelwe imiphakathi yaseNingizimu Afrika",
            "get_started" to "Asiqale Impilo Entsha",
            "dashboard" to "Ikhasi Lami",
            "lessons" to "Izifundo",
            "quizzes" to "Imibuzo",
            "ai_assistant" to "Umsizi we-AI",
            "community" to "I-Forum",
            "profile" to "Iphrofayili",
            "premium" to "Ubeluleki",
            "total_xp" to "XP Ephelele",
            "streak" to "Izinsuku Zolandelayo",
            "unlocked" to "Kuvuliwe",
            "locked" to "Kukhiyiwe",
            "downloaded" to "Kulandiwe",
            "download_class" to "Landa Isifundo",
            "data_saver" to "Yokonga I-Data",
            "online_status" to "Ku-Inthanethi",
            "offline_status" to "Akukho-Inthanethi",
            "ask_something" to "Ngingakusiza ngani namuhla...",
            "careers" to "Umseshi weMisebenzi",
            "one_on_one" to "1-on-1 Umqeqeshi",
            "cv_builder" to "Umakhi we-CV lula",
            "interviews" to "Ukulungiselela Interviews",
            "networking" to "Inethiwekhi ye-Tech",
            "daily_challenges" to "Inselelo Yanamuhla",
            "submit_code" to "Hlola Amakhodi Lami",
            "congrats" to "Halala! Ugcinile!",
            "get_certificate" to "Thola Isitifiketi",
            "founder_story" to "Sihlangane nabaSunguli",
            "founder_desc" to "I-KodeMamas yasungulwa eSoweto nguNaledi no-Akhona, omama ababili abanemishini yokuhlanganisa amakhodi kwethimba le-township. Bafuna ukuletha amakhono okukhiqiza emiphakathini yethu.",
            "testimonials" to "Halala naba-Mama ethu",
            "data_saver_desc" to "Kwehlisa isithombe kunciphisa ukusebenza kwe-data yeselula ematasa.",
            "enter_msg" to "Bhala umlayezo kumsizi..."
        ),
        "xh" to mapOf( // isiXhosa
            "learn_coding" to "Funda ukukhowuda ngolimi lwakho",
            "offline_online" to "Izifundo ze-Offline ne-Online",
            "built_for_sa" to "Yenzelwe uluntu lwaseMzantsi Afrika",
            "get_started" to "Masisungule",
            "dashboard" to "Ideshibhodi",
            "lessons" to "Izifundo",
            "quizzes" to "Imibuzo",
            "ai_assistant" to "Incedi ye-AI",
            "community" to "Uluntu lwethu",
            "profile" to "Ikhasi Lami",
            "premium" to "Ubomi be-Tech",
            "total_xp" to "XP Iyonke",
            "streak" to "Iintsuku Zesitrayiki",
            "unlocked" to "Ivuliwe",
            "locked" to "Ivaliwe",
            "downloaded" to "Ilandiwe",
            "download_class" to "Khuphela Isifundo",
            "data_saver" to "Ukuchenga iDatha",
            "online_status" to "Une-Inthanethi",
            "offline_status" to "Ngaphandle kwe-Inthanethi",
            "ask_something" to "Buza umbuzo wokukhowuda apha...",
            "careers" to "Ingcebiso yeKhondo",
            "one_on_one" to "Ubambiswano noMcebisi",
            "cv_builder" to "Umakhi weCV emfitshane",
            "interviews" to "Imibuzo yodliwanondlebe",
            "networking" to "Uthungelwano lweTech",
            "daily_challenges" to "Inselele yeMihla",
            "submit_code" to "Run kwaye iQinisekise",
            "congrats" to "Camagu! Ugqibile!",
            "get_certificate" to "Thatha iSatifikethi",
            "founder_story" to "Sifunde nge-Akhona noNaledi",
            "founder_desc" to "KodeMamas yaqala eSoweto ngabazali be-dev basetyhini ababelwa ukunabela uluntu lwaselokishini ukuze bakwazi ubulumko beteknoloji.",
            "testimonials" to "Amabali Abaphumeleleyo",
            "data_saver_desc" to "Oku kunciphisa amandla datha yeselula ngokukhawuleza okukhulu.",
            "enter_msg" to "Bhala umbhalo..."
        ),
        "af" to mapOf( // Afrikaans
            "learn_coding" to "Leer kodeer in jou eie taal",
            "offline_online" to "Alyn- en Vanlyn-lesse",
            "built_for_sa" to "Gebou vir Suid-Afrikaanse Gemeenskappe",
            "get_started" to "Laat Ons Begin",
            "dashboard" to "Paneelbord",
            "lessons" to "Lesse",
            "quizzes" to "Vasvrae",
            "ai_assistant" to "AI-Kletsbot",
            "community" to "Gemeenskap",
            "profile" to "My Profiel",
            "premium" to "Mentorskap",
            "total_xp" to "Totale XP",
            "streak" to "Onaaneenlopende Dae",
            "unlocked" to "Ontsluit",
            "locked" to "Gesluit",
            "downloaded" to "Afgestoor",
            "download_class" to "Laai Les Af",
            "data_saver" to "Databesparing",
            "online_status" to "Aanlyn-modus",
            "offline_status" to "Vanlyn-modus",
            "ask_something" to "Vra my 'n programmeringsvraag...",
            "careers" to "Inligtingsdiens",
            "one_on_one" to "1-op-1 Mentorskap",
            "cv_builder" to "CV-Bouer",
            "interviews" to "Onderhoudsvoorbereiding",
            "networking" to "SA Tegniese Netwerk",
            "daily_challenges" to "Daaglikse Uitdaging",
            "submit_code" to "Voer Kode Uit",
            "congrats" to "Geluk! Voltooid!",
            "get_certificate" to "Eis Sertifikaat",
            "founder_story" to "Ons Stigtersvloei",
            "founder_desc" to "KodeMamas is in Soweto gestig deur twee tegnologiese ma's wat glo kodeer-oplossings kan armoede oorwin in ons townships.",
            "testimonials" to "Suksesverhale van Mamas",
            "data_saver_desc" to "Verminder prentkwaliteit en bedienerversoeke om mobiele data te bespaar.",
            "enter_msg" to "Skryf 'n boodskap..."
        ),
        "nso" to mapOf( // Sepedi
            "learn_coding" to "Lera go khouta ka leleme la gago",
            "offline_online" to "Dithuto tsa Offline & Online",
            "built_for_sa" to "E agetšwe ditšhaba tša Afrika Borwa",
            "get_started" to "A re Simolole",
            "dashboard" to "Letlakala",
            "lessons" to "Dithuto",
            "quizzes" to "Dipotšišo",
            "ai_assistant" to "Mothuši wa AI",
            "community" to "Lekgotla",
            "profile" to "Porofele",
            "premium" to "Baeletši",
            "total_xp" to "XP Ka moka",
            "streak" to "Matšatši a go Latelana",
            "unlocked" to "E butšwe",
            "locked" to "E tswaletšwe",
            "downloaded" to "E laolotšwe",
            "download_class" to "Laolla Thuto",
            "data_saver" to "Sekongi se Data",
            "online_status" to "O Online",
            "offline_status" to "O Offline",
            "ask_something" to "Mpotšiše potšišo ka go khouta...",
            "careers" to "Thuto ya Mošomo",
            "one_on_one" to "1-go-1 Keletšo",
            "cv_builder" to "Moagi wa CV",
            "interviews" to "Ipeakanyetšo Potsolotšo",
            "networking" to "Neteweke ya Setsebi",
            "daily_challenges" to "Tlhahlobo ya Letšatši",
            "submit_code" to "Leka Khoutu",
            "congrats" to "Re go Lebola!",
            "get_certificate" to "Thola Setifikeiti",
            "founder_story" to "Meet the Founders",
            "founder_desc" to "Started in Soweto by innovative local tech moms Naledi and Akhona to expand local knowledge.",
            "testimonials" to "Tsa Katlego ya Mamas",
            "data_saver_desc" to "E fokotša data e šomišwago mo founung ya gago.",
            "enter_msg" to "Ngwala molaetša..."
        ),
        "tn" to mapOf( // Setswana
            "learn_coding" to "Ithute go khouta ka puo ya gago",
            "offline_online" to "Dithuto tsa Offline le Online",
            "built_for_sa" to "E kailwe go tshegetsa Ma-Afrika-Borwa",
            "get_started" to "A re Simolole",
            "dashboard" to "Letlhare la Taolo",
            "lessons" to "Dithuto",
            "quizzes" to "Dipotso tsa Botlhale",
            "ai_assistant" to "Mothusi wa AI",
            "community" to "Lekgotla la Rona",
            "profile" to "Porofele yame",
            "premium" to "Thuto-Mogolo",
            "total_xp" to "XP Gotlhe",
            "streak" to "Malatsi a go latelana",
            "unlocked" to "E buletswe",
            "locked" to "E tswetswe",
            "downloaded" to "E laotswe",
            "download_class" to "Laolla Thuto e",
            "data_saver" to "Mo-Sete-Datha",
            "online_status" to "O Online",
            "offline_status" to "O Offline",
            "ask_something" to "Ke go thuse ka potso efe ya khouthu...",
            "careers" to "Tshegetso ya Tsa Tiro",
            "one_on_one" to "1-on-1 Thupelo",
            "cv_builder" to "Moagi wa CV yo o bofefo",
            "interviews" to "Ipaakanyetso Dipotsolotso",
            "networking" to "SA Tech Network",
            "daily_challenges" to "Ntlha sa Letsatsi",
            "submit_code" to "Leka Khoutu e",
            "congrats" to "Pula! O feditse!",
            "get_certificate" to "Tsaya Setifikeiti",
            "founder_story" to "Batlhalami ba Rona",
            "founder_desc" to "KodeMamas e simolotswe ko Soweto ke bommè ba tech go tlisa kitso mo loagong.",
            "testimonials" to "Diphuthego tsa Phuthego",
            "data_saver_desc" to "Bula datha e monyana go boloka madi a gago.",
            "enter_msg" to "Kwala molaetsa..."
        )
    )

    fun translate(key: String, lang: String): String {
        val dict = translations[lang] ?: translations["en"]!!
        return dict[key] ?: translations["en"]!![key] ?: key
    }
}
